(affiche) ajouter l'option du texte défini par l'utilisateur
betagouv/ma-cantine pull request #1050
Opened 2022-02-11 16:28 UTC by hfroot

closes #1022 

Bugs a régler mardi :

- [x] pourquoi le legend n'est pas enlever quand `showPreviousDiagnostic=true` ?
- [ ] qu'est qu'on veut faire quand l'utilisateur n'est pas connecté ?

2022-02-14 13:49 UTC, alemangui commented on frontend/src/views/GeneratePosterPage/index.vue
> +          :rules="[(v) => !v || v.length <= 915 || '915 caractères maximum']"
Vu qu'on n'est pas en mono-space, je prendrais un peu plus de marge, genre 850
![image](https://user-images.githubusercontent.com/1225929/153876286-b1d190ec-5f5d-4596-9cc9-f1e2bb6aa268.png)

2022-02-14 13:55 UTC, alemangui requested changes

2022-02-14 13:55 UTC, alemangui commented on frontend/src/views/GeneratePosterPage/index.vue
> +          :rules="[(v) => !v || v.length <= 915 || '915 caractères maximum']"
Vu qu'on n'est pas en monospace et que des mots peuvent être longs et pas coupés par un tiret, je prendrais un peu plus de marge, genre 800

![image](https://user-images.githubusercontent.com/1225929/153876321-fa4d9172-27d9-49de-9c2a-c8c1fd9f42c4.png)

2022-02-15 13:12 UTC, hfroot commented on frontend/src/views/GeneratePosterPage/index.vue
> +          :rules="[(v) => !v || v.length <= 915 || '915 caractères maximum']"
😢 bien vu !

2022-02-15 14:30 UTC, hfroot commented on frontend/src/views/GeneratePosterPage/index.vue
> +          :rules="[(v) => !v || v.length <= 915 || '915 caractères maximum']"
J'ai ajouté quelque chose pour régler le overflow, par contre je pense peut être laisser les caractères comme ça et voir si on a des retours, parce que le cas au-dessus c'est assez particulière, je suppose que le plupart de gens vont écrire le plupart de texte en minuscule et je veux leur donner le plus d'espace possible. Qu'est-ce que tu penses ?

![Screenshot 2022-02-15 at 15 24 23](https://user-images.githubusercontent.com/9282816/154082268-f19fdfd9-9899-4221-b6ad-b68d370e4443.png)

2022-02-15 16:28 UTC, alemangui approved these changes

2022-02-16 08:49 UTC, merged