Afficher les résultats du diagnostique
betagouv/ma-cantine pull request #109
Opened 2021-02-16 12:39 UTC by hfroot

2021-02-16 17:16 UTC, Forster-Groux requested changes

2021-02-16 17:16 UTC, Forster-Groux commented on front-end/src/views/DiagnosticPage.vue
> +    <button id="summarise" @click="saveStatuses">Récapitulatif</button>
Je mettrai la sauvegarde plutôt au clic directement sur les `inputs`, plutôt qu'une sauvegarde finale. Le bouton "récapitulatif" ne serait qu'un lien vers la page mesures-phares. Ca permet de persister l'information même si on va pas au bout et c'est plus cohérent avec la suite qu'on a prévu de rajouter la sélection "fait/programmé/pas fait" sur les pages de détails des mesures.

2021-02-16 17:23 UTC, Forster-Groux commented
Je crois y'a du css qui s'est perdu en route ^^

![bug auto evaluer](https://user-images.githubusercontent.com/4048371/108098721-fd710000-7083-11eb-8bd5-3f45b53349e0.png)

2021-02-16 17:26 UTC, Forster-Groux commented on front-end/src/views/KeyMeasuresPage/KeyMeasuresHome.vue
>      </div>
On peut enlever cette partie là du coup.

2021-02-16 17:40 UTC, hfroot commented
> Je crois y'a du css qui s'est perdu en route ^^
> 
> ![bug auto evaluer](https://user-images.githubusercontent.com/4048371/108098721-fd710000-7083-11eb-8bd5-3f45b53349e0.png)

Hmmm, je ne peux pas recréer ça, est-ce que tu peux me donner plus de contexte ?

2021-02-16 17:47 UTC, Forster-Groux commented
> > Je crois y'a du css qui s'est perdu en route ^^
> 
> Hmmm, je ne peux pas recréer ça, est-ce que tu peux me donner plus de contexte ?

Ca vient du tag `fieldset` quand je mets `div` à la place ça remarche, peut être un soucis de compatibilité avec certains navigateurs.

2021-02-16 18:16 UTC, hfroot commented
> > > Je crois y'a du css qui s'est perdu en route ^^
> > 
> > 
> > Hmmm, je ne peux pas recréer ça, est-ce que tu peux me donner plus de contexte ?
> 
> Ca vient du tag `fieldset` quand je mets `div` à la place ça remarche, peut être un soucis de compatibilité avec certains navigateurs.

Même si dans Chrome Version 88.0.4324.150 (Official Build) (x86_64) MacOS ce problème n'existe pas. J'ai le donner un max-width mais je sais pas si ça le fixera, il me semble étrange que pas seulement est-ce les boutons sont trop large, mais aussi que c'est affiché en colonne et pas en rangé... Stp dis moi comment ça marche avec toi maintenant.

![Screenshot 2021-02-16 at 19 06 50](https://user-images.githubusercontent.com/9282816/108103394-2d230680-708a-11eb-9331-ce1d1ae3f846.png)

2021-02-17 11:27 UTC, Forster-Groux commented
> > > > Je crois y'a du css qui s'est perdu en route ^^
> > > 
> > > 
> > > Hmmm, je ne peux pas recréer ça, est-ce que tu peux me donner plus de contexte ?
> > 
> > 
> > Ca vient du tag `fieldset` quand je mets `div` à la place ça remarche, peut être un soucis de compatibilité avec certains navigateurs.
> 
> Même si dans Chrome Version 88.0.4324.150 (Official Build) (x86_64) MacOS ce problème n'existe pas. J'ai le donner un max-width mais je sais pas si ça le fixera, il me semble étrange que pas seulement est-ce les boutons sont trop large, mais aussi que c'est affiché en colonne et pas en rangé... Stp dis moi comment ça marche avec toi maintenant.

Alors en fait sur ma version de Linux, Chrome ne se met pas à jour automatiquement, j'ai forcé la mise à jour et là tout marche bien. Je pense pas qu'il faille qu'on se préoccupe des vieilles versions de navigateurs pour le moment donc tu peux ignorer ce soucis. On verra si un jour on nous remonte un problème similaire.

2021-02-18 11:24 UTC, Forster-Groux commented on front-end/src/views/KeyMeasuresPage/KeyMeasureScore.vue
> +<template>
J'aurais mis ce component avec les autres (`KeyMeasureDescription`, `KeyMeasureInfoCard`, ...) dans components.

2021-02-18 11:24 UTC, Forster-Groux commented on front-end/src/views/KeyMeasuresPage/KeyMeasuresHome.vue
> +    <p id="contact">Vous souhaitez nous contacter : <a href="mailto:contact@egalim.beta.gouv.fr">contact@egalim.beta.gouv.fr</a>.</p>
On peut l'enlever ça non ?

2021-02-18 11:24 UTC, Forster-Groux commented on front-end/src/views/KeyMeasuresPage/KeyMeasuresHome.vue
> +        <KeyMeasureScore :measure="measure" :stroke="4" :radius="45" />
Pourquoi définir `stroke` et `radius` ici plutôt que directement dans le component ?

2021-02-18 11:24 UTC, Forster-Groux commented on front-end/src/views/KeyMeasuresPage/KeyMeasuresHome.vue
> +          'fa-question': !status
J'hésite mais peut être mettre ça directement dans l'objet partagé `STATUSES`, tu en penses quoi ?

2021-02-18 11:24 UTC, Forster-Groux commented on front-end/src/views/KeyMeasuresPage/KeyMeasureScore.vue
> +          return { green: true };
`return "green"` ça fait pas la même chose ?

2021-02-18 11:33 UTC, Forster-Groux requested changes
Il faut mettre à jour les liens de la `LandingPage` vers le détails des mesures (ça aurait dû être fait sur la PR de navigation mais j'y ai pas pensé du coup avec la suppression de l'affichage de toutes les mesures sur la page mesures-phares les liens se sont cassés).

2021-02-19 08:43 UTC, Forster-Groux commented on front-end/src/views/KeyMeasuresPage/KeyMeasuresHome.vue
> +          'fa-question': !status
Je retire ce que j'ai dis c'est pas une bonne idée.

2021-02-19 09:04 UTC, hfroot commented on front-end/src/views/KeyMeasuresPage/KeyMeasuresHome.vue
> +        <KeyMeasureScore :measure="measure" :stroke="4" :radius="45" />
J'ai fait un changement dans une autre branche pour contrôler le `height` de `.measure-card` mieux qui depend sur le nombre du `radius`, alors j'aime declarer ça ici, mais je peux mettre `stroke` dans le component. Qu'est-ce que tu penses ?

2021-02-19 09:15 UTC, Forster-Groux commented on front-end/src/views/KeyMeasuresPage/KeyMeasuresHome.vue
> +        <KeyMeasureScore :measure="measure" :stroke="4" :radius="45" />
Du coup je pense qu'il vaut mieux avoir les deux directement dans le component, et quand tu auras besoin de le déplacer sur l'autre branche de le faire à ce moment là. En général vaut mieux éviter de coder les choses à l'avance après on se retrouve avec du code inutilisé.

2021-02-19 09:17 UTC, Forster-Groux approved these changes

2021-02-19 09:24 UTC, merged