(suivi achats) Ajouter caractéristiques de local
betagouv/ma-cantine pull request #1097
Opened 2022-02-23 09:55 UTC by hfroot

2022-02-24 14:46 UTC, alemangui requested changes

2022-02-24 14:46 UTC, alemangui commented on frontend/src/views/PurchasePage.vue
> +            <label class="body-2" for="local-definition">Définition de local</label>
```suggestion
            <label class="body-2" for="local-definition">C'est quoi votre définition de local ?</label>
```

2022-02-24 14:46 UTC, alemangui commented on frontend/src/views/PurchasePage.vue
> +        { text: "Département", value: "DEPARTMENT" },
```suggestion
        { text: "Provenant du même département", value: "DEPARTMENT" },
```

2022-02-24 14:46 UTC, alemangui commented on frontend/src/views/PurchasePage.vue
> +        { text: "Région", value: "REGION" },
```suggestion
        { text: "Provenant de la même région", value: "REGION" },
```

2022-02-24 14:46 UTC, alemangui commented on frontend/src/views/PurchasePage.vue
> +        LOCAL: { text: "Local (spécifier plus)" },
```suggestion
        LOCAL: { text: "Local" },
```
Pas sur que "spécifier plus" soit nécessaire, surtout que le champ apparaît tout de suite après et est obligatoire.

2022-02-24 14:46 UTC, alemangui commented on data/models/purchase.py
> +        max_length=255, choices=Local.choices, null=True, blank=True, verbose_name="Comment définir local"
```suggestion
        max_length=255, choices=Local.choices, null=True, blank=True, verbose_name="définition de local"
```

2022-02-25 11:22 UTC, hfroot commented on frontend/src/views/PurchasePage.vue
> +        LOCAL: { text: "Local (spécifier plus)" },
Je pensais que p-e ça rassure les utilisateurs qu'il n'y aura pas des questions additionnels pour les autres aussi

2022-02-25 13:54 UTC, hfroot commented on data/models/purchase.py
> +        max_length=255, choices=Local.choices, null=True, blank=True, verbose_name="Comment définir local"
fait [9e7123b]

2022-02-25 14:40 UTC, alemangui approved these changes

2022-02-28 13:44 UTC, merged