Ajout d'une barre de navigation pour les mesures
betagouv/ma-cantine pull request #112
Opened 2021-02-16 13:48 UTC by Forster-Groux

2021-02-16 15:02 UTC, hfroot requested changes

2021-02-16 15:16 UTC, Forster-Groux commented on front-end/src/views/KeyMeasuresPage/index.vue
> +
Fait. Par contre j'ai pas compris quelle margin tu préconises pour les écrans <700.

2021-02-16 16:47 UTC, hfroot commented on front-end/src/views/KeyMeasuresPage/index.vue
> +
Un margin pour ajouter un peu d'espace entre les liens quand ils ont un fond:
![Screenshot 2021-02-16 at 17 45 58](https://user-images.githubusercontent.com/9282816/108094288-f09ddd80-707e-11eb-8c03-1b757299bf0a.png)
![Screenshot 2021-02-16 at 17 45 21](https://user-images.githubusercontent.com/9282816/108094294-f1cf0a80-707e-11eb-933e-adf1df000ff5.png)

2021-02-18 06:46 UTC, hfroot approved these changes

2021-02-18 10:38 UTC, merged