Eviter les duplications de SIRET
betagouv/ma-cantine pull request #1229
Opened 2022-03-29 06:56 UTC by hfroot

![Uploading siret guard.gif…]()

2022-03-29 13:25 UTC, hfroot commented
Relier : https://github.com/betagouv/ma-cantine/discussions/1154#discussioncomment-2438329

2022-04-01 13:35 UTC, alemangui requested changes
:thinking: Il me semble qu'un de tests est KO avec la PR

2022-04-04 10:07 UTC, alemangui requested changes

2022-04-04 12:29 UTC, alemangui requested changes

2022-04-04 12:37 UTC, alemangui commented
Ce n'est peut-être pas lié aux changements de cette PR, mais les erreurs de validation du formulaire n’empêchent plus l'envoie de la requête POST. Par exemple, en laissant le champ _Ville_ vide, normalement on ne devrait pas envoyer la requête non ? Pourtant on l'envoie.

![form-errors-not-blocking](https://user-images.githubusercontent.com/1225929/161544891-88f26e29-9452-4473-a938-b2363ac7dc4a.gif)

2022-04-04 14:49 UTC, alemangui requested changes

2022-04-04 14:49 UTC, alemangui commented on frontend/src/views/CanteenEditor/CanteenForm.vue
> +        url: this.$router.resolve({
:thinking:  Il y a quelque chose qui me gêne dans l'idée d'envoyer un URL du frontend qui fini dans l'email du gestionnaire... je serais plus à l'aise si cet URL est construit dans le backend. Notamment ça nous permettrait d'y ajouter une clé d'auth ou éventuellement de le remplacer par un URL d'action directe.

Cette construction d'URLs publics par le backend peut se faire dans le modèle lui même. On a déjà l'`url-slug` dans le [modèle canteen.py](https://github.com/betagouv/ma-cantine/blob/staging/data/models/canteen.py#L168) Chez Peps on [avait fait un truc pareil](https://github.com/betagouv/peps/blob/master/data/models/farmer.py#L151).

Du coup ce qui serait envoyé c'est l'ID de la cantine dupliqué et non pas l'URL. Ça nous permettra aussi d'effectuer des checks additionnels et du logging plus clair.

2022-04-04 15:15 UTC, alemangui commented
J'ai essayé de simplifier les textes et actions sur [ce commit](https://github.com/betagouv/ma-cantine/pull/1229/commits/f035ce269504fb267ead000712731d162ecfeb6b) tout en gardant l'attention de l'utilisateur (car en vrai iel ne peut rien faire d'autre dans ce cas, donc autant être très explicite là-dessus):

![form-siret-duplicate](https://user-images.githubusercontent.com/1225929/161573461-b7d17b45-14ef-4183-bf92-488eaabcce55.gif)

![form-siret-duplicate-gestionnaire](https://user-images.githubusercontent.com/1225929/161575349-79200442-b2cb-453c-8e43-db7287043229.gif)

2022-04-04 15:17 UTC, alemangui commented on api/templates/canteen_join_request.html
> +    <div class="cta">
Dans l'idéal on aurait des URL d'action avec un webtoken (comme pour le parrainage du secrétariat). Je suis OK pour faire une première version sans, mais on l'ajoutera dans le backlog car ça fait une grande différence dans le parcours.

2022-04-05 13:31 UTC, hfroot commented on frontend/src/views/CanteenEditor/CanteenForm.vue
> +        // TODO: put misc inquiry types in the title of trello card directly
C'est fait, je vais le supprimer

2022-04-05 13:34 UTC, hfroot commented on api/templates/canteen_join_request.html
> +    <div class="cta">
Pour faire quoi ?

2022-04-05 14:08 UTC, hfroot commented
> Ce n'est peut-être pas lié aux changements de cette PR, mais les erreurs de validation du formulaire n’empêchent plus l'envoi de la requête POST. Par exemple, en laissant le champ _Ville_ vide, normalement on ne devrait pas envoyer la requête non ? Pourtant on l'envoie.

PR : https://github.com/betagouv/ma-cantine/pull/1258

2022-04-06 16:18 UTC, hfroot commented on frontend/src/views/CanteenEditor/CanteenForm.vue
> +        url: this.$router.resolve({
Ah oui j'ai oublié le côté sécurité de ça, bien vu ! Je vais le changer

2022-04-06 16:32 UTC, hfroot commented on api/templates/canteen_join_request.html
> +    <p>Voici son message :</p>
https://github.com/betagouv/ma-cantine/pull/1229/commits/537fa6b8df391bb49b7616c22fff3ee470943bd7

2022-04-07 09:09 UTC, alemangui commented on api/templates/canteen_join_request.html
> +    <div class="cta">
C'est ça, mais laissons pour une deuxième PR.

2022-04-07 09:13 UTC, alemangui commented on api/views/canteen.py
> +            body = {"name": canteen.name, "id": canteen.id}
Option légère possible pour un premier commit : inclure simplement le `{... detail: 'La resource que vous souhaitez créer existe déjà'}` dans la réponse tel qu'on la construit aujourd'hui

2022-04-07 12:46 UTC, alemangui commented on api/views/canteen.py
> +            body = {"name": canteen.name, "id": canteen.id}
J'ai ajouté une version minimaliste du DuplicateException ici : https://github.com/betagouv/ma-cantine/pull/1229/commits/2898bcaee11c4d08b569f1763a76e3262f1d1b50

J'ai profité pour la réutiliser sur les diagnostics et les expés. Dis-moi si ça te va comme approche ;)  @hfroot

2022-04-07 12:53 UTC, alemangui approved these changes

2022-04-08 09:08 UTC, hfroot reviewed
Merci @alemangui c'est top

2022-04-08 09:08 UTC, merged