modif texte
betagouv/ma-cantine pull request #123
Opened 2021-02-26 09:23 UTC by JenniferStephan

en cours
petit test de modif de texte

2021-03-01 08:12 UTC, JenniferStephan commented
hello 👋  j'ai des modifs de textes sur les mesures et sur la landing suivant [ce doc](https://docs.google.com/document/d/1OVxTxz5haFzbefdyeEosfTGqgGC9y-sjVB9pOaA3JhI/edit#heading=h.wg37wp4d4xkd). j'ai laissé de côté les modifs qui demandent de la mise en forme (typiquement mettre les logos des labels en puce à la place des ticks) pour éviter de tout casser :)

2021-03-01 10:31 UTC, Forster-Groux requested changes

2021-03-01 10:31 UTC, Forster-Groux commented on front-end/src/views/LandingPage/GoalBlock.vue
> +      <div class="goal-information">
Petit soucis d'indentation ici.

2021-03-01 10:31 UTC, Forster-Groux commented on front-end/src/views/LandingPage/GoalBlock.vue
> -    <div class="goal-list">
Il faut supprimer le css associé aussi.

2021-03-01 10:31 UTC, Forster-Groux commented on front-end/src/data/key-measures.json
>                  "shortTitle": "Faire des dons",
Est-ce que le `shortTitle` (qui s'affiche sur la page des résultats de diagnostiques) ne pourrait pas être lui aussi "Dons aux associations" ?

2021-03-01 10:31 UTC, Forster-Groux commented on front-end/src/data/key-measures.json
> +                "htmlDescription": "Depuis le 22 octobre 2020, les restaurations collectives qui préparent plus de 3000 repas par jour ont l’obligation de proposer une convention de dons à une associ
Ce type de mesure ça me parait un bon exemple qu'on pourrait mieux présenter, quelque chose avec :
- déjà en vigueur (depuis octobre 2020)
- seulement pour : +de 3000 repas / jour
D'ailleurs c'est voulu d'enlever la balise `<b>` ?

2021-03-01 10:31 UTC, Forster-Groux commented on front-end/src/data/key-measures.json
> +                "description": "Les gestionnaires de restauration collective doivent communiquer, informer et consulter les usagers sur le respect de la qualité alimentaire et nutritionnelle des repa
On veut rajouter ce niveau de détails ? Quelle valeur ça apporte à nos utilisateurs ? Surtout que la date d'entrée en vigueur c'est 2018 c'est perturbant non ?

2021-03-01 14:15 UTC, hfroot requested changes

2021-03-01 14:15 UTC, hfroot commented on front-end/src/data/key-measures.json
> +                "htmlDescription": "Une fois par an, <b>les convives sont informés</b> sur la part des produits de qualité et durables des repas servis et des démarches entreprises pour l’acquisition
Si c'est obligatoire d'informer par les deux façons, peut-être modifier: "Cette information peut se faire" à "Cette information doit se faire" ?

2021-03-01 14:15 UTC, hfroot commented on front-end/src/data/key-measures.json
> +                "htmlDescription": "L’infraction à cette loi est susceptible d’une amende de 3 750 €.",
Est-ce que c'est le seul mesure avec un amende en cas de l'infraction ?

2021-03-01 14:16 UTC, hfroot commented on front-end/src/data/key-measures.json
> +",
Je vais changer un autre petit chose, alors je vais changer ça à le même moment

2021-03-01 14:18 UTC, Forster-Groux commented on front-end/src/data/key-measures.json
> +                "htmlDescription": "Un produit de qualité et durable doit bénéficier d’un des labels suivants : \n\n<i class='fas fa-check-square'></i> Label rouge - Signe national qui atteste qu’un
Je pensais plutôt à une liste des logos avec la description qui apparaitrait au "hover" dans une infobulle sinon vous en pensez quoi ?

2021-03-01 14:19 UTC, Forster-Groux commented on front-end/src/data/key-measures.json
> +                "htmlDescription": "L’infraction à cette loi est susceptible d’une amende de 3 750 €.",
Oui

2021-03-01 17:04 UTC, Forster-Groux approved these changes

2021-03-02 15:40 UTC, hfroot approved these changes

2021-03-02 15:42 UTC, merged