Générer affiche convives
betagouv/ma-cantine pull request #124
Opened 2021-03-01 11:29 UTC by hfroot

2021-03-01 11:36 UTC, hfroot commented
Je pense qu'on veut envoyer les données quand on génère l'affiche à Matomo, mais peut-être c'est un nouveau PR ? Aussi, je pense que ce sera mieux si on valide le commune avec l'API https://geo.api.gouv.fr/adresse mais aussi, je propose que ça c'est un nouveau PR.

2021-03-02 11:44 UTC, Forster-Groux requested changes

2021-03-02 11:44 UTC, Forster-Groux commented on front-end/src/views/GeneratePosterPage/index.vue
> +          dans <label for="school">la cantine du </label>
Il vaut mieux enlever le "du" ici, par exemple on pourrait avoir "école Jules Ferry".

2021-03-02 11:44 UTC, Forster-Groux commented on front-end/src/views/GeneratePosterPage/CanteenPoster.vue
> +      <p class="percentage" v-if="equitableNumber"><span id="equitable-percent" class="number">{{ equitablePercent }} %</span> produits issus du commerce équitable</p>
`equitablePercent` ne se remet pas à vide si on supprime le montant dans le formulaire.

2021-03-02 11:44 UTC, Forster-Groux commented on front-end/src/views/GeneratePosterPage/CanteenPoster.vue
> +          <p>Nous servons {{ servingsNumber || "___" }} repas par jour</p>
Le nombre de couvert à 1 "keydown" de retard par rapport au formulaire.

2021-03-02 11:44 UTC, Forster-Groux commented on front-end/src/views/GeneratePosterPage/index.vue
> +          </select>
Vu qu'on utilise pas cette partie pour la création de l'affiche, je suis pas bien sûr que ce soit pertinent. Peut être juste mettre : "je représente la cantine ___"

2021-03-02 11:44 UTC, Forster-Groux commented on front-end/src/views/GeneratePosterPage/index.vue
> +        const opt = {
Peut être avoir des noms de variables plus explicites pour une meilleure lisibilité du code, comme `htmlPoster` et "pdfOptions"

2021-03-02 11:44 UTC, Forster-Groux commented on front-end/src/views/GeneratePosterPage/index.vue
> +        html2pdf().from(element).set(opt).save();
Il vaut mieux rajouter "return" ici je pense

2021-03-02 11:44 UTC, Forster-Groux commented on front-end/src/views/GeneratePosterPage/CanteenPoster.vue
> +    <div id="poster-contents">
On peut pas avoir juste une seule div ici ?

2021-03-02 11:44 UTC, Forster-Groux commented on front-end/src/views/GeneratePosterPage/index.vue
> +        const element = document.getElementById('poster-contents');
Est-ce que c'est possible d'avoir une div avec l'id de l'element voulu dans ce component ? Quelque chose comme :
```
<div id="poster-preview">
  <CanteenPoster v-bind="form" />
</div>
```
Et de faire : `document.getElementById('poster-preview');`
Ca complexifie beaucoup la lecture futur du code sinon d'avoir cette dépendance à l'id d'une div dans un autre component que celui-là.

2021-03-02 12:41 UTC, hfroot commented on front-end/src/views/GeneratePosterPage/index.vue
> +          </select>
Oui... j'ai discuter ça avec Jenn et elle a dit que c'est interessant pour nous de savoir qui remplit le formulaire, mais bien-sûr à ce moment nous ne gardons pas les données alors maintenant la profession n'est pas utilisée. Je vais redemander

2021-03-02 12:42 UTC, hfroot commented on front-end/src/views/GeneratePosterPage/index.vue
> +        html2pdf().from(element).set(opt).save();
Où ?

2021-03-02 12:44 UTC, hfroot commented on front-end/src/views/GeneratePosterPage/CanteenPoster.vue
> +    <div id="poster-contents">
Il y a du styling que je ne veux pas dans le PDF (comme le border et margin) alors j'ai ajouter deux divs

2021-03-02 12:46 UTC, Forster-Groux commented
Qu'est ce que tu penses de sauvegarder les données du formulaire dans le localStorage ?

2021-03-02 12:54 UTC, hfroot commented
> Qu'est ce que tu penses de sauvegarder les données du formulaire dans le localStorage ?

Je suis d'acc mais peut-être dans un nouveau PR comme une amélioration afin de merger ça plus vite ?

2021-03-02 13:01 UTC, hfroot commented on front-end/src/views/GeneratePosterPage/CanteenPoster.vue
> +    <div id="poster-contents">
Peut-être c'était résoudre avec le changement après le commentaire dessus

2021-03-02 13:03 UTC, Forster-Groux commented on front-end/src/views/GeneratePosterPage/index.vue
> +        html2pdf().from(element).set(opt).save();
`return html2pdf().from(element).set(opt).save();`

2021-03-02 16:26 UTC, Forster-Groux approved these changes

2021-03-02 16:30 UTC, merged