Champ fonction utilisateur
betagouv/ma-cantine pull request #1339
Opened 2022-04-29 08:17 UTC by hfroot

2022-04-29 10:01 UTC, hfroot commented
@JenniferStephan tu penses quoi du design au-dessus ? 
Et tu veux que j'attends la liste finalisée avant le finir et passer en staging ?

2022-05-05 08:32 UTC, alemangui requested changes

2022-05-05 08:32 UTC, alemangui commented on frontend/src/constants.js
> +      text: "Direction Achat Société de restauration",
```suggestion
      text: "Direction achat société de restauration",
```
Juste pour de la cohérence par rapport aux majuscules et minuscules. Je ne pense pas que ça soit nécessaire de le faire dans le backend aussi.

2022-05-05 08:32 UTC, alemangui commented on frontend/src/views/AccountSummaryPage/AccountEditor.vue
> +          <v-col cols="9">
Je pense que ce champ peut utiliser toute la largeur de l'écran pour les xs et sm : 
![image](https://user-images.githubusercontent.com/1225929/166886691-af598da1-0fe2-4f6f-ac8c-139c806d8832.png)

2022-05-05 08:32 UTC, alemangui commented on frontend/src/views/ManagementPage/index.vue
> +            <p class="text--body-2 primary--text mb-0">Veuillez completer votre profil :</p>
`text--body-2` n'applique pas le style _body-2_, juste `body-2` suffit. D'ailleurs, vu qu'aujourd'hui tout le texte en couleur _primary_ est cliquable, je me demande si c'est pas mieux d'utiliser un texte noir comme les autres, surtout que le badge vert attire déjà pas mal l'attention.

2022-05-05 08:35 UTC, alemangui requested changes

2022-05-05 08:35 UTC, alemangui commented on frontend/src/views/ManagementPage/index.vue
> +            <v-col cols="7">
Ici aussi je pense qu'on peut utiliser toute la largeur de l'ecran en `xs`et `sm`

2022-05-05 08:38 UTC, alemangui commented on frontend/src/views/ManagementPage/index.vue
> +            <v-col cols="7">
Dans [ce commit](https://github.com/betagouv/ma-cantine/pull/1339/commits/7eccf0e5a4edc02b1f226a7b671bc4b9d8f498a8) j'ai mis une largeur plus grand pour le champ pour les petites écrans :

![image](https://user-images.githubusercontent.com/1225929/166888960-d77fb8c6-9f61-40c9-bf9a-c97c583e3e0b.png)

2022-05-05 08:39 UTC, alemangui commented on frontend/src/views/ManagementPage/index.vue
> +            <p class="text--body-2 primary--text mb-0">Veuillez completer votre profil :</p>
Dans [ce commit](https://github.com/betagouv/ma-cantine/pull/1339/commits/8cb62ee05816258af0f1a9f53e8febe057b4e543) j'ai effectué quelques modifs de style dans le header, t'en penses quoi ? 
![image](https://user-images.githubusercontent.com/1225929/166889165-0d7f0691-94db-479d-a1c5-1c0188d07148.png)

2022-05-05 08:40 UTC, alemangui commented on frontend/src/views/AccountSummaryPage/AccountEditor.vue
> +          <v-col cols="9">
L'utilisation complète de l'écran pour `sm` et `xs` est ici : https://github.com/betagouv/ma-cantine/pull/1339/commits/0b3bba3b13ce123909aa42026bc35343513c0b01 Dis-moi qu'est-ce que t'en penses ;)
![image](https://user-images.githubusercontent.com/1225929/166889285-f3e6ff2b-1244-4499-bc00-68cd08d5e9da.png)

2022-05-06 12:12 UTC, hfroot commented
Merci pour tes changements géniaux :D je valide, et toi ?

2022-05-06 12:13 UTC, hfroot commented
@alemangui  Merci pour tes changements géniaux :D je valide, et toi ?

2022-05-06 12:30 UTC, merged