Ajouter crisp aux pages d'authentification
betagouv/ma-cantine pull request #1340
Opened 2022-04-29 09:35 UTC by hfroot

2022-04-29 12:18 UTC, hfroot commented
https://ma-cantine.beta.gouv.fr/accueil/

2022-05-02 08:25 UTC, alemangui commented
L'issue référencé dans la description n'est pas le bon. Cette PR ferme https://github.com/betagouv/ma-cantine/issues/1296, et non pas #1293 (validation téléphone)

2022-05-02 08:26 UTC, alemangui requested changes
Crisp est censé être dispo seulement dans les pages de création de compte et de création de cantine. J'ai l'impression qu'en ce moment c'est partout non ? https://github.com/betagouv/ma-cantine/issues/1296

2022-05-02 09:08 UTC, alemangui requested changes

2022-05-02 09:08 UTC, alemangui commented on frontend/src/App.vue
> +    if (this.$store.state.loggedUser) {
La requête contenant le loggedUser peut ne pas retourner avant le `mounted`

2022-05-02 09:15 UTC, alemangui commented
@hfroot Dans ce commit https://github.com/betagouv/ma-cantine/pull/1340/commits/0e3c8cf476550465eb90f5785a1fc465c0cd849d j'ai mis Crisp seulement dans la page de création de compte et de création de cantine. J'ai profité pour fixer le souci avec l'email vide décrit ici : https://github.com/betagouv/ma-cantine/pull/1340#discussion_r862697789 et pour ajouter _jedonnemonavis.numerique.gouv.fr_ en tant que source d'image autorisée.

Dis-moi si ça te convient.

2022-05-03 08:04 UTC, hfroot commented
Merci @alemangui c'est nickel 😍 ça te va si je la merge ?

2022-05-03 08:09 UTC, alemangui approved these changes

2022-05-03 08:10 UTC, merged