Enrichissement de l'auto-diagnostique
betagouv/ma-cantine pull request #145
Opened 2021-03-10 17:03 UTC by Forster-Groux

#125

https://ma-cantine-egalim-staging-pr145.osc-fr1.scalingo.io/

2021-03-22 08:58 UTC, hfroot requested changes
À mon avis, le bouton "Je m'évalue" apparait trop 'tôt' (car il est devant les boutons d'état). Mais peut-être c'est quelque chose on peut demander au un.e designer comment on peut l'améliorer, est changer dans une nouvelle PR.

2021-03-22 08:58 UTC, hfroot commented on front-end/src/views/GeneratePosterPage/index.vue
> +          total: qualityDiagnostic.valueTotal,
C'est très utile d'initialiser les valeurs ici, est-ce qu'on peut aussi mettre à jour les valeurs si ils sont changer/saisi premièrement dans le formulaire pour la génération d'affiche ?

2021-03-22 08:58 UTC, hfroot commented on front-end/src/views/DiagnosticPage.vue
> +        <span @click="showDiagnosticModal(measure)">Je m'évalue !</span>
Aussi, pour les petits écrans, ce sera mieux afficher si il occupe une nouvelle ligne

2021-03-23 10:03 UTC, hfroot commented on front-end/src/components/KeyMeasureDiagnostic/QualityMeasureDiagnostic.vue
> +    <input id="value-total" class="form-input" v-model="diagnostic.valueTotal" type="number">
Il faut qu'on ajoute un `min` attribute pour éviter les valeurs moins de 0 pour tous les saisis de type `number`

2021-03-24 19:10 UTC, Forster-Groux commented on front-end/src/components/KeyMeasureDiagnostic/DiversificationMeasureDiagnostic.vue
> +    <label for="value-meat-previous" class="form-label">Montant de la part viande/volailles dans vos achats 2019</label>
Ces questions ont été supprimées

2021-03-24 19:13 UTC, Forster-Groux commented on front-end/src/components/KeyMeasureDiagnostic/WasteMeasureDiagnostic.vue
> +    <input id="covenant-list" class="form-input" v-model="diagnostic.covenantList" type="text">
Question supprimée

2021-03-24 19:36 UTC, Forster-Groux commented on front-end/src/views/DiagnosticPage.vue
> +        measureDiagnosticModal: null,
Oui sinon j'ai un warning vue `Property "measureDiagnosticModal" was accessed during render but is not defined on instance. `

2021-03-24 19:50 UTC, Forster-Groux commented on front-end/src/data/KeyMeasures.js
> +      valueTotal: null,
Pour la lisibilité du code, avoir toutes les propriétés des diagnostiques visibles à un même endroit.

2021-03-24 21:15 UTC, Forster-Groux commented on front-end/src/components/KeyMeasureDiagnostic/InformationMeasureDiagnostic.vue
> +  label {
J'ai refactorisé les input basiques et les chechbox simples. Il faudrait que je refactorise les checkboxes multiples et radio mais j'attends les retours finaux parce que c'est pas simple à faire.

2021-03-24 21:16 UTC, Forster-Groux commented on front-end/src/components/KeyMeasureDiagnostic/index.vue
> +  import InformationMeasureDiagnostic from '@/components/KeyMeasureDiagnostic/InformationMeasureDiagnostic';
J'aime beaucoup, pour pas m'y perdre dans mes réécritures insessantes de commits je le ferai tout à la fin.

2021-03-24 21:17 UTC, Forster-Groux commented on front-end/src/components/KeyMeasureDiagnostic/index.vue
> +  import InformationMeasureDiagnostic from '@/components/KeyMeasureDiagnostic/InformationMeasureDiagnostic';
J'aime beaucoup par contre pour pas m'y perdre dans mes réécritures insessantes de commit je le ferai tout à la fin.

2021-03-26 14:12 UTC, hfroot requested changes

2021-03-26 14:12 UTC, hfroot commented on front-end/src/components/KeyMeasureDiagnostic/DiversificationMeasureDiagnostic.vue
> +        max-width: 105px;
Je pense qu'on peut enlever ça pour mieux utiliser l'espace disponible

2021-03-26 14:12 UTC, hfroot commented on front-end/src/components/KeyMeasureDiagnostic/DiversificationMeasureDiagnostic.vue
> +        <input id="all-vegetarians" value="allVegetarians" v-model="diagnostic.vegetarianMenuIsStandalone" type="radio" >
C'est `all-vegetarian` sans le 's'

2021-03-26 14:12 UTC, hfroot commented on front-end/src/components/KeyMeasureDiagnostic/DiversificationMeasureDiagnostic.vue
> +        <label for="vegetarian-or-meat">Un menu végétarien alternatif à un menu carné</label>
P-e le variable `vegetarianMenuIsStandalone` peut être `vegetarianMenuType` pour ne suggère pas que c'est un valeur boolean. Et `vegetarian-or-meat` peut changer au `alternative` ou `alternate-choice`

2021-03-26 14:12 UTC, hfroot commented on front-end/src/components/KeyMeasureDiagnostic/NoPlasticMeasureDiagnostic.vue
> +    :inputId="'disposable-ustensils'"
C'est `disposable-utensils` sans le 's' après le 'u'

2021-03-26 14:12 UTC, hfroot commented on front-end/src/components/KeyMeasureDiagnostic/WasteMeasureDiagnostic.vue
> +        <label for="sensitization">Sensibilisation par affichage ou autre média</label>
Plutôt `raise-awareness` que `sensitization`

2021-03-29 16:10 UTC, Forster-Groux commented on front-end/src/components/KeyMeasureDiagnostic/DiversificationMeasureDiagnostic.vue
> +        max-width: 105px;
Les textes ont tendances a prendre de l'espace sur le radio button dans certaines tailles d'écran si je l'enlève.

2021-03-29 16:28 UTC, Forster-Groux commented on front-end/src/data/KeyMeasures.js
> +      disposableUstensilsSubstituted: false,
Il n'y actuellement pas de différence métier entre `null` et `false` donc je préférait mettre `false` pour expliciter qu'on attend des booléens.

2021-03-29 16:44 UTC, Forster-Groux commented on front-end/src/components/KeyMeasureDiagnostic/InformationMeasureDiagnostic.vue
> +        <label for="other">Autre(s)</label>
C'est pas voulu pour le moment.

2021-03-31 17:26 UTC, Forster-Groux commented on front-end/src/views/GeneratePosterPage/index.vue
> +        form: {
J'ai fais un truc un peu différent sinon en faisant `this.qualityDiagnostic["2020"] = this.form;` on sauvegarde aussi les champs ville, etc dans diagnostique

2021-04-02 08:51 UTC, hfroot requested changes

2021-04-02 08:51 UTC, hfroot commented on front-end/src/components/KeyMeasureDiagnostic/DiversificationMeasure.vue
> +    :legend="'J’ai mis en place un menu végétarien dans ma cantine :'"
On n'a pas besoin du ':' quand tu n'utilises pas des variables, il y a des cas de ça dans plusieurs fichiers

2021-04-02 08:51 UTC, hfroot commented on front-end/src/components/KeyMeasureDiagnostic/QualityMeasure.vue
> +    v-model="diagnostic['2019'].valueTotal"
J'ai reçu un erreur, je pense parce que j'ai eu déjà des données en `localStorage`, dans un autre format. J'imagine qu'il y a quelques utilisateurs qui ont des données déjà aussi. Est-ce que tu as une idée d'une solution pour ça ? Peut-être on peut verifier si '2019' et '2020' existent dans diagnostic dans `data()` ?

2021-04-02 08:51 UTC, hfroot commented on front-end/src/views/GeneratePosterPage/index.vue
> +        form: {
On doit changer `CanteenPoster.vue` parce que les valeurs ne sont pas `this.bio` etc maintenant

2021-04-02 08:51 UTC, hfroot commented on front-end/src/components/KeyMeasureDiagnostic/DiversificationMeasure.vue
> +      { inputId: 'all-vegetarian', value: 'all-vegetarian', label: 'Plusieurs menus végétariens alternatifs' },
Est-ce que le valeur ici doit être 'allVegetarian' ?

2021-04-02 09:35 UTC, Forster-Groux commented on front-end/src/components/KeyMeasureDiagnostic/QualityMeasure.vue
> +    v-model="diagnostic['2019'].valueTotal"
Ca n'a jamais été déployé sur staging encore donc pas nécessaire pour l'instant, si on doit rajouter des choses oui faudra prévoir ça.

2021-04-02 09:36 UTC, Forster-Groux commented on front-end/src/components/KeyMeasureDiagnostic/DiversificationMeasure.vue
> +      { inputId: 'all-vegetarian', value: 'all-vegetarian', label: 'Plusieurs menus végétariens alternatifs' },
Une autre idée pour le nom ?

2021-04-02 09:47 UTC, hfroot commented on front-end/src/components/KeyMeasureDiagnostic/QualityMeasure.vue
> +    v-model="diagnostic['2019'].valueTotal"
Ah oui bien sûr

2021-04-02 09:48 UTC, hfroot commented on front-end/src/components/KeyMeasureDiagnostic/DiversificationMeasure.vue
> +      { inputId: 'all-vegetarian', value: 'all-vegetarian', label: 'Plusieurs menus végétariens alternatifs' },
Non, plutôt que les autres `value:` sont en camelCase, mais ici c'est kebab (maintenant `value: 'all-vegetarian'` et je propose `value: 'allVegetarian'`)

2021-04-02 10:00 UTC, Forster-Groux commented on front-end/src/components/KeyMeasureDiagnostic/DiversificationMeasure.vue
> +      { inputId: 'all-vegetarian', value: 'all-vegetarian', label: 'Plusieurs menus végétariens alternatifs' },
Ha oui en effet c'est une erreur, bien vu.

2021-04-02 10:29 UTC, hfroot approved these changes

2021-04-02 10:32 UTC, merged