Option pour l'équipe de publier les cantines importées
betagouv/ma-cantine pull request #1488
Opened 2022-06-08 11:06 UTC by hfroot

Closes https://github.com/betagouv/ma-cantine/issues/1463

2022-06-08 14:59 UTC, alemangui requested changes

2022-06-08 14:59 UTC, alemangui commented on api/views/diagnostic.py
> +                publication_status = row[20]
Je serais un peu plus restrictif ici en cas de coquille. Si jamais quelqu'un.e met "puublished" ou "Publié" ou un truc comme ça la canteen n'aura plus la valeur de la classe `PublicationStatus`.

À la limite on pourrait remplacer ça par un truc comme : 
```python
publication_status = len(row) > 20 and row[20] == "published" ? Canteen.PublicationStatus.PUBLISHED : Canteen.PublicationStatus.DRAFT
```

Ou bien retourner une erreur si ce n'est ni  "published" ni "draft"... une de deux

2022-06-08 15:52 UTC, hfroot commented on api/views/diagnostic.py
> +                publication_status = row[20]
Ah oui bien pensé. Qu'est-ce que tu pense de donner un erreur de validation si le valeur ne fait pas partie des options valides ?

2022-06-08 16:19 UTC, alemangui commented on api/views/diagnostic.py
> +                publication_status = row[20]
Oui je pense que c'est une bonne idée de retourner une erreur, ça sera plus explicite

2022-06-09 09:57 UTC, alemangui approved these changes

2022-06-09 11:00 UTC, merged