Mise en conformité l'en-tête et le pied de page
betagouv/ma-cantine pull request #1516
Opened 2022-06-14 13:50 UTC by hfroot

2022-06-14 13:55 UTC, alemangui commented
@hfroot Il me semble que les tests Vue ne passent plus

2022-06-14 14:26 UTC, hfroot commented
@alemangui c'est réglé

2022-06-14 15:01 UTC, alemangui requested changes

2022-06-14 15:01 UTC, alemangui commented on frontend/tests/unit/AppHeader.spec.js
> +      // mocking breakpoint with thanks to https://github.com/vuetifyjs/vuetify/issues/11388#issuecomment-701410577
Nice :+1:

2022-06-14 15:06 UTC, alemangui commented on frontend/src/components/AppFooter.vue
>      </v-container>
On a perdu quelques liens qui ne se trouvent plus nulle part (je pense que c'est une bonne chose, je le mentionne juste pour qu'on soit sûrs que c'est intentionnel) : 
- _Qui sommes nous ? _ qui renvoyait à notre page produit beta
- _Les startups d'État_ qui renvoyait à l'approche beta
- _Envoyer une suggestion_ vers les issues GH
- Lien vers la DGAL
- Lien vers betagouv

2022-06-15 11:26 UTC, hfroot commented on frontend/src/App.vue
> +  max-width: 73rem !important;
J'ai choisi ça car le classe DSFR .fr-container utilise 78rem (et après j'ai trouvé que ça a été vraiment trop large par rapport de nos pages maintenant)

2022-06-15 11:28 UTC, hfroot commented on frontend/src/components/AppFooter.vue
> +          licence etalab-2.0
tout à fait. Je mettrai à jour le texte et on peut en discuter plus si on veut

2022-06-15 11:29 UTC, hfroot commented on frontend/src/components/AppHeader.vue
>          <template v-slot:activator="{ on }">
Mon compte n'est pas super visité, mais j'ajouterai mes cantines, et mon compte dans le menu déroulant Gérer mes cantines

2022-06-16 12:26 UTC, alemangui requested changes

2022-06-16 12:26 UTC, alemangui commented on frontend/src/App.vue
> +  max-width: 73rem !important;
J'ai créé une carte dans le jardin (backlog technique) pour ne pas oublier de se pencher sur le sujet, notamment pour les layouts avec colonne latérale
```suggestion
  max-width: 1024px !important;
```

2022-06-17 13:26 UTC, merged