Import complet
betagouv/ma-cantine pull request #1676
Opened 2022-07-20 21:32 UTC by hfroot

# message ephemère amélioré

![Screenshot 2022-07-20 at 23 30 10](https://user-images.githubusercontent.com/9282816/180085766-b0bc9cfe-1077-4cda-b0c1-bc1598f09c37.png)
![Screenshot 2022-07-20 at 23 29 37](https://user-images.githubusercontent.com/9282816/180085771-cbe57a55-ea7f-4bfd-b369-9fa72b8d4d81.png)

# plus de guidance pour les erreurs
![Screenshot 2022-07-20 at 23 24 07](https://user-images.githubusercontent.com/9282816/180085775-27655141-1b24-4295-b066-34847b7eb46f.png)
![Screenshot 2022-07-20 at 23 22 55](https://user-images.githubusercontent.com/9282816/180085778-2715c260-fb37-414f-8131-7ddc3ec3a88c.png)

2022-08-02 17:40 UTC, hfroot commented
![Screenshot from 2022-08-02 19-04-07](https://user-images.githubusercontent.com/9282816/182439181-b04b9837-3fe1-411f-8d52-cf57d4ccebce.png)

2022-08-04 15:21 UTC, alemangui requested changes

2022-08-04 15:41 UTC, alemangui commented on api/views/diagnosticimport.py
> +# flake8: noqa: C901
Fix pour ce commentaire ici : https://github.com/betagouv/ma-cantine/pull/1676/commits/1c09511b035b861f25d5c9785eb05465a9f26bb2

Ça met le `noqa: C901` dans le bon niveau et ça fix les warnings qui étaient cachés auparavant

2022-08-04 15:53 UTC, alemangui commented on frontend/src/views/DiagnosticsImporter/index.vue
> +      <v-col cols="12" md="4" v-for="type in diagnosticTypes" :key="type.key">
Proposition dans https://github.com/betagouv/ma-cantine/pull/1676/commits/9261f78fb88f471ea8962c2a913e4f4dd8cbb391
![cards-size](https://user-images.githubusercontent.com/1225929/182891400-bd6780c6-b611-4eb9-9f6a-61eee8aa8d7e.gif)

2022-08-04 15:55 UTC, alemangui commented on api/views/diagnosticimport.py
> +        # access this to trigger an error early and loudly if missing from child class
Proposition ici : https://github.com/betagouv/ma-cantine/pull/1676/commits/ee245cb6266a36c4bea79f032a65ed49f4383242

2022-08-04 16:01 UTC, alemangui commented on frontend/src/views/DiagnosticsImporter/index.vue
> +      <v-col cols="12"><h2>Choisir le niveau d'information disponible</h2></v-col>
Pour la première partie de mon commentaire, ce petit commit sort le titre de l'encart vert : https://github.com/betagouv/ma-cantine/pull/1676/commits/5f0582dbc3738042730dac33a6ec5bca65b9fa81

2022-08-05 08:28 UTC, hfroot commented on frontend/src/views/DiagnosticsImporter/index.vue
> +      pour une experience plus guidée.
J'ai voulu souligné les avantages de ce façon de saisi (plus intuitif, meilleur validation, option de répondre aux autres mesures, plus des infos tout au long du processus...). J'ai peur que 'manuellement' suggère un processus plus lourd... tu penses quoi ?

2022-08-05 08:36 UTC, hfroot commented on api/views/diagnosticimport.py
> +            message = "Deux lignes en-tête attendues, {} trouvée. Vieullez verifier que vous voulez importer les diagnostics complèts, et assurez-vous que le format de l'en-tête suit les exemples don
J'ai fait ces suggestions dans un commit à part pour bien changer tous les instances de ces coquilles, merci :)

2022-08-05 08:37 UTC, hfroot commented on api/views/diagnosticimport.py
> +                    "year": "Ce champ doit être un nombre entier. Si vous voulez importer que la cantine, vieullez changer le type d'import et reessayer."
J'ai fait ces suggestions dans un commit à part pour bien changer tous les instances de ces coquilles, merci :)

2022-08-05 08:40 UTC, alemangui commented on api/views/diagnosticimport.py
> +                    "year": "Ce champ doit être un nombre entier. Si vous voulez importer que la cantine, vieullez changer le type d'import et reessayer."
Ça marche, sinon tu peux aussi cliquer sur "Add suggestion to batch" et ça met tous les suggestions que tu choisisses sur le même commit

2022-08-05 10:34 UTC, hfroot commented on api/views/diagnosticimport.py
> +            if row[0] and row[0].lower() == "siret":
(question envoyé par mattermost)

2022-08-05 13:33 UTC, alemangui commented on frontend/src/views/DiagnosticsImporter/index.vue
> +      pour une experience plus guidée.
Pas faux, t'en penses quoi de :
_Sinon, utilisez notre **formulaire en ligne** pour ajouter une nouvelle cantine tout en simplicité depuis votre navigateur_

2022-08-05 13:56 UTC, alemangui commented on api/views/diagnosticimport.py
> +                if os.environ.get("ENVIRONMENT") == "dev":
A-t-on besoin de ce code debug dans le repo ? Qu'est-ce qui fait cet endroit différent aux autres erreurs ?

2022-08-05 14:01 UTC, alemangui requested changes

2022-08-05 14:01 UTC, alemangui commented on frontend/src/constants.js
> +      help: "Vous voulez importer des cantines sans diagnostic",
Le titre et le help se ressemblent beaucoup, ça n'apporte pas d'info supplémentaire comme pour les autres. Est-ce que ça t'irait ?

```suggestion
      help: "Vous voulez importer des cantines sans données d'approvisionnement",
```

2022-08-05 15:32 UTC, hfroot commented on api/views/diagnosticimport.py
> +                if os.environ.get("ENVIRONMENT") == "dev":
Ça fait plusieurs fois que j'ai du avoir plus des infos en train de dévéloppement (parce que l'erreur et stack trace sont completement perdus) alors je pensais que je pourrais sauver mes temps dans l'avenir

2022-08-05 15:47 UTC, alemangui approved these changes

2022-08-09 08:24 UTC, merged