Clarifier les intitulés de boutons
betagouv/ma-cantine pull request #1701
Opened 2022-07-29 14:08 UTC by hfroot

closes #1640

2022-08-01 08:01 UTC, alemangui requested changes

2022-08-01 08:03 UTC, alemangui commented
Je veux bien un peu plus d'informations sur les PRs, je l'impression qu'il y a plus de changements que ceux décrits par l'issue et le titre (rajout de certains items, changement de position de quelques éléments, etc). Je suppose que ça vient de conversations en off, mais du coup je n'ai pas tout le contexte.

2022-08-02 14:17 UTC, alemangui commented on frontend/src/components/AppHeader.vue
> +        {
Si j'ai bien compris pour l'instant on laissera comme c'était avant (sans l'option dans le header) jusqu'à confirmation de l'équipe non ?

2022-08-03 09:21 UTC, hfroot commented on frontend/src/components/AppHeader.vue
> +          <div style="height: 90px" class="d-flex flex-column justify-center">
Bien vu :)

2022-08-03 09:34 UTC, hfroot commented on frontend/src/components/AppHeader.vue
> +        {
L'équipe a confirmé que c'est non plus utile

2022-08-04 08:32 UTC, alemangui commented
@hfroot super de voir tant de lignes supprimées :)  Du coup Pipedrive ne semble plus être utilisé, j'ai enlevé les env vars lui concernant ici : https://github.com/betagouv/ma-cantine/pull/1701/commits/ad80c4653af401c22adf93b3dd2d57512d111f94

2022-08-04 08:33 UTC, alemangui approved these changes

2022-08-05 07:18 UTC, merged