Nouveau tableau de bord enrichi
betagouv/ma-cantine pull request #182
Opened 2021-04-08 20:01 UTC by Forster-Groux

https://ma-cantine-egalim-staging-pr182.osc-fr1.scalingo.io/

2021-04-09 13:55 UTC, hfroot requested changes

2021-04-09 13:55 UTC, hfroot commented on front-end/src/views/KeyMeasuresPage/DashboardPage.vue
> +    display: flex;
Je propose que tu supprimer ça quand l'écran est plus petit (<1000px?), pour afficher les blocs dans une colonne

2021-04-09 13:55 UTC, hfroot commented on front-end/src/components/SummaryStatistics.vue
> +        <h3>Produits durables :</h3>
Plutôt "Produits de qualité et durable :" ?

2021-04-09 13:55 UTC, hfroot commented on front-end/src/views/KeyMeasuresPage/DashboardPage.vue
> +    .fa-check, .fa-times {
Est-ce que le styling pour `fa-check`, `fa-times`, et `span`, peut être définir un fois dans la fichier ?

2021-04-09 13:55 UTC, hfroot commented on front-end/src/views/KeyMeasuresPage/DashboardPage.vue
> +      text-align: left;
ces lignes pour `.x-action` et `.x-actions` sont dupliquer 3 fois, est-ce qu'on peut les définir hors de `.measure-x-y` pour les définir seulement un fois ?

2021-04-12 17:34 UTC, Forster-Groux commented on front-end/src/views/KeyMeasuresPage/DashboardPage.vue
> +      <h2>{{ qualityMeasure.shortTitle }}</h2>
Je pense que ça peut être perturbant de cliquer sur un bloc du diagnostic et d'arriver sur le détails de la mesure. Je pense qu'à terme ce qu'on aura c'est une page de diagnostic dédiée pour chaque mesure et là oui on pourra mettre le bloc en lien vers cette page.

2021-04-12 17:35 UTC, Forster-Groux commented on front-end/src/views/KeyMeasuresPage/DashboardPage.vue
> +          <KeyMeasureResource baseComponent='InformDiners'/>
On a eu un retour comme quoi même si c'était déjà complet ils auraient eu besoin de la ressource. Du coup pour l'instant j'ai préféré l'enlever. Qui plus est on a pas beaucoup de ressources et elles sont affichées par mesure et non plus tout d'un bloc.

2021-04-13 07:41 UTC, hfroot commented
Une plus grande question peut-être pour un autre PR, mais est-ce qu'il y a toujours raison pour l'état des sous-mesures ? Il me semble qu'ils sont obsolètes.

2021-04-13 08:09 UTC, hfroot commented on front-end/src/views/KeyMeasuresPage/DashboardPage.vue
> +  <div id="key-measures">
C'est aussi un problème avec `EmptyDiagnosticPage` `CanteensPage/index.vue` `KeyMeasuresHome.vue`

2021-04-13 08:10 UTC, hfroot approved these changes

2021-04-14 15:46 UTC, merged