PostgreSQL BDD setup
betagouv/ma-cantine pull request #187
Opened 2021-04-13 15:16 UTC by hfroot

2021-04-15 10:33 UTC, Forster-Groux requested changes
Concernant l'organisation des fichier, je renommerai "database" en "infrastructure".
Dans ce fichier infrastructure je rajouterai un dossier "repositories" où je mettrai "userRepository" et "canteenRepository" et je déplacerai le code qui se trouve dans create-user-and-canteen.js à l'intérieur de ces deux repositories. Qu'est ce que tu penses ?

2021-04-15 10:33 UTC, Forster-Groux commented on api/application/create-user-and-canteen.js
> +};
Je pense qu'ici on a pas besoin de `async` et `await`

2021-04-15 10:33 UTC, Forster-Groux commented on api/application/create-user-and-canteen.js
> +};
Pareil ici je pense pas qu'on est besoin de `async` et `await`

2021-04-15 10:33 UTC, Forster-Groux commented on api/application/create-user-and-canteen.js
> +  await createUser(request.payload.user, canteen.id)
On peut remplacer le dernier `await` par `return`

2021-04-15 10:33 UTC, Forster-Groux commented on api/application/create-user-and-canteen.js
> +exports.createUser = createUser;
Souvent on préfères mettre tous les exports en une fois (soit en haut soit en bas du fichier à voir) sous cette forme :
```
exports = {
  createCanteen,
  createUser,
  createUserAndCanteen
}
```

2021-04-15 10:33 UTC, Forster-Groux commented on api/application/create-user-and-canteen.js
> +exports.createUserAndCanteen = async function(request) {
Si je suppose bien le context je pense qu'on peut renommer en "createUserWithCanteen"

2021-04-15 10:33 UTC, Forster-Groux commented on api/application/create-user-and-canteen.js
> +exports.createCanteen = createCanteen;
J'aurais peut être mis cette fonction dans un autre fichier.

2021-04-15 10:33 UTC, Forster-Groux commented on api/database/models.js
> +  managesCanteen: {
Ce nom de champs il est un peu trop "métier" pour un champs de base de données, j'aurais plus mis quelque chose comme `canteenId` ou `managedCanteenId`.

2021-04-15 10:33 UTC, Forster-Groux commented on api/database/setup.js
> +// TODO: how to connect to test database when running tests, but prod normally?
Very good question ^^

2021-04-15 10:33 UTC, Forster-Groux commented on api/tests/integration/canteen-model.test.js
> +  });
Ce test il apporte pas vraiment de valeur on peut le supprimer.

2021-04-15 10:33 UTC, Forster-Groux commented on api/tests/integration/canteen-model.test.js
> +    await createCanteen(canteenPayload);
Cette méthode elle retourne pas la Canteen créée ?

2021-04-15 10:33 UTC, Forster-Groux commented on api/tests/integration/user-model.test.js
> +  });
Pas très utile celui-là

2021-04-15 10:33 UTC, Forster-Groux commented on api/tests/integration/user-model.test.js
> +  // TODO: should this test be in a different suite?
Non il est bien là.

2021-04-15 13:25 UTC, Forster-Groux commented on api/database/setup.js
> +// TODO: how to connect to test database when running tests, but prod normally?
On va avoir besoin de différencier nos environnements, ce qui nous donnerait quelque chose comme : 
`"NODE_ENV=test jest"` pour le script de lancement des tests et dans setup.js on aurait :
```
if (process.env.NODE_ENV === 'test') {
  exports.sequelize = new Sequelize(process.env.DB_TEST_NAME, process.env.DB_USERNAME, process.env.DB_PASSWORD, { ... });
}
```

2021-04-16 08:52 UTC, hfroot commented on api/tests/integration/canteen-model.test.js
> +    await createCanteen(canteenPayload);
Oui, mais dans ce test je veux vérifier si la cantine est vraiment dans le BDD, e.g. pas seulement un objet retourné par la fonction.

2021-04-16 09:01 UTC, Forster-Groux commented on api/tests/integration/canteen-model.test.js
> +    await createCanteen(canteenPayload);
Oui mais là si y'a une canteen dans a bdd qui vient d'ailleurs le test va passer, il faut s'assurer qu'elles aient le même id. Ca donnerait quelque chose comme ça :
```
const createdCanteen = await createCanteen(canteenPayload);
const persistedCanteen = await Canteen.getById(createdCanteen.id);
expect(persistedCanteen).toBe()
```

2021-04-16 11:00 UTC, Forster-Groux commented on api/tests/integration/user-model.test.js
> +  });
Les tests sur les déclarations de modèle y'a deux écoles de pensée, y'en a qui les mettent mais dans ce cas il faudrait tous les mettre : `allowNull`, `type`, `unique`, `increment`, etc du coup c'est assez vite lourd et redondant. Et comme on a pas besoin de vérifier que Sequelize fait bien le boulot on est juste en train de tester qu'on a bien déclaré nos modèles. Enfin voilà y'en a qui les mettent pour être sûr sûr et d'autres qui trouvent ça trop lourd pour ce que ça apporte. A toi de choisir ce que tu préfères.

2021-04-16 13:41 UTC, hfroot commented on api/infrastructure/models/canteen.js
> +  },
Est-ce que une commune et une ville est le même chose ? J'ai utilise department parce que c'est ça qu'on maintenant utilise pour nos-cantines mais je peux le changer bien sûr.

2021-04-16 13:46 UTC, hfroot commented on api/infrastructure/models/user.js
> +  },
J'ai choisi ça parce que je pense que c'est plus facile à migrer le BDD pour accepter `null` plus tard que migrer le BDD pour n'accepter pas `null`, et avec une déclaration c'est peut-être important d'avoir le nom afin d'aider nous avec la vérification des données.

2021-04-16 13:47 UTC, Forster-Groux commented on api/infrastructure/models/canteen.js
> +  },
Une commune c'est une petite ville, quand il s'agit d'adresse postale c'est la même chose. On a mis le département mais c'est pas très pertinent, la ville ça parlera plus dans un premier temps. Et on enrichira ensuite.

2021-04-16 13:48 UTC, hfroot commented on api/tests/integration/user-model.test.js
> +  });
Je suis d'acc avec toi, ce type de tests à aider moi avec le compréhension de sequelize mais finalement c'est pas trop utile de tester ce que sequelize doit avoir testé déjà.

2021-04-19 08:30 UTC, Forster-Groux approved these changes

2021-04-19 08:54 UTC, merged