Vidéo de présentation du calculateur
betagouv/ma-cantine pull request #192
Opened 2021-04-23 12:28 UTC by Forster-Groux

2021-04-26 08:32 UTC, hfroot requested changes

2021-04-26 08:32 UTC, hfroot commented on front-end/src/components/KeyMeasureResource/QualityMeasure.vue
> +  }
Le style du modal est different si tu l’accéder vers la page avec toutes les mesures ou la page avec la mesure appro.

2021-04-26 08:32 UTC, hfroot commented on front-end/src/components/KeyMeasureResource/QualityMeasure.vue
> +          class="calculator-video"
P-e ajouts un `title`

2021-04-26 16:52 UTC, Forster-Groux commented on front-end/src/components/KeyMeasureResource/QualityMeasure.vue
> +  }
J'arrive pas à reproduire, tu peux me donner plus de contexte ?

2021-04-27 08:17 UTC, hfroot commented on front-end/src/components/KeyMeasureResource/QualityMeasure.vue
> +  }
![Screenshot 2021-04-27 at 10 15 13](https://user-images.githubusercontent.com/9282816/116208742-81f59400-a741-11eb-9c05-401cc474ccaf.png)
![Screenshot 2021-04-27 at 10 15 07](https://user-images.githubusercontent.com/9282816/116208750-84f08480-a741-11eb-8bd6-f486d9ac43e7.png)
C'est un différence très petit : le heading est aligné au centre normalement, mais à gauche quand tu passes vers le lien sur la page détaillée.

2021-04-27 08:18 UTC, hfroot approved these changes

2021-04-27 10:54 UTC, merged