Filtrer par EPCI
betagouv/ma-cantine pull request #2000
Opened 2022-10-12 08:49 UTC by hfroot

2022-10-24 08:55 UTC, alemangui requested changes

2022-10-24 08:55 UTC, alemangui commented on frontend/src/views/PublicCanteenStatisticsPage/index.vue
> +      return jsonEpcis.map((x) => ({
Éventuellement on pourrait simplement changer notre _epci.json_ pour ne pas devoir le transformer à ce stade

2022-10-25 08:56 UTC, hfroot commented on frontend/src/views/PublicCanteenStatisticsPage/index.vue
> +      return jsonEpcis.map((x) => ({
Encore mieux - c'est possible de changer les clés utilisés par vuetify https://github.com/betagouv/ma-cantine/pull/2000/commits/5739e522f57b44c3bdc299fce800779c889f7bce

2022-11-02 17:33 UTC, hfroot commented on api/views/canteen.py
> +    def _filter_canteens(self, regions, departments, postal_codes, sectors):
J'ai enlevé les `self`s pas utilisés sans ajouter un `@staticmethod` - il me paraît logique d'utiliser le truc le plus court

2022-11-02 17:36 UTC, hfroot commented
Je teste l'erreur EPCI en coupant mon WIFI
![epci_error](https://user-images.githubusercontent.com/9282816/199561169-d83f16ab-eb5c-4b61-95a8-982f4eb894d1.gif)

2022-11-04 15:30 UTC, alemangui approved these changes

2022-11-07 08:17 UTC, merged