Rendre nos ressources plus trouvables
betagouv/ma-cantine pull request #2040
Opened 2022-10-28 13:22 UTC by hfroot

Après notre webinaire ça me parait intéressant, mais qu'est-ce que tu penses ?
![Screenshot 2022-10-28 at 15 21 26](https://user-images.githubusercontent.com/9282816/198606509-56fe991f-6598-47f1-aa75-6ff0dd0f3a28.png)

2022-11-08 11:28 UTC, hfroot commented
![Screenshot 2022-11-08 at 12 28 36](https://user-images.githubusercontent.com/9282816/200552787-5c0b7a11-40c9-4ea5-ad24-26736dc2b4fe.png)


![Screenshot 2022-11-08 at 12 21 18](https://user-images.githubusercontent.com/9282816/200551473-80f29520-70a0-495c-bb17-4b67023158ef.png)

2022-11-08 11:30 UTC, hfroot commented
https://mattermost.incubateur.net/betagouv/pl/uzjth6fndtbi3nosi9ge8cmmrw

2022-11-14 08:21 UTC, alemangui requested changes

2022-11-14 08:21 UTC, alemangui commented on frontend/src/components/AppHeader.vue
> +          text: "Éspace de gestion",
```suggestion
          text: "Espace de gestion",
```

2022-11-14 08:21 UTC, alemangui commented on frontend/src/views/ContactPage.vue
> +    <h2 class="mb-4">Votre question n'est pas répondue&nbsp;?</h2>
```suggestion
    <h2 class="mb-4">Avez-vous une autre question ?</h2>
```

2022-11-14 08:21 UTC, alemangui commented on frontend/src/views/ContactPage.vue
> +          title: "Précedents webinaires",
```suggestion
          title: "Webinaires précedents",
```

2022-11-14 08:21 UTC, alemangui commented on frontend/src/router/index.js
> +    path: "/acteurs-de-l-eco-systeme",
Dans l'idéal quand on chance une route on peut laisser la précédente avec une redirection vers la nouvelle au cas où des utilisateurs l'auraient bookmarké ou leur navigateur aurait mis l'URL en cache.

Au passage, on verra si par la suite on ajoute cette route dans le `sitemap.py` du backend

2022-11-14 08:26 UTC, alemangui commented on frontend/src/router/index.js
> +    path: "/acteurs-de-l-eco-systeme",
J'ai ajouté la redirection ici : https://github.com/betagouv/ma-cantine/pull/2040/commits/37f9d175ccaa8faeb192ca3a615fc3c7e82b4a3e,

J'ai mis une carte aussi pour vérifier le `sitemap.py` par la suite sur une autre PR

2022-11-15 08:31 UTC, merged