Parcours de publication
betagouv/ma-cantine pull request #205
Opened 2021-05-05 16:09 UTC by Forster-Groux

2021-05-11 19:44 UTC, hfroot reviewed
Il faut qu'on relier les champs pour la génération d'affichage avec les infos de la cantine

2021-05-11 19:44 UTC, hfroot commented on front-end/src/router/index.js
> +        component: CanteenInfos,
P-e CanteenInfo sans le 's'

2021-05-11 19:44 UTC, hfroot commented on front-end/src/views/PublishPage/index.vue
> +        const prefilledPublication = await fetch(`${this.$api_url}/get-prefilled-publication`, {
Je préfère get-publication-data mais c'est pas grave si tu n'es pas d'acc

2021-05-11 19:44 UTC, hfroot commented on front-end/src/views/PublishPage/index.vue
> +            'Authorization': 'Bearer ' + localStorage.getItem('jwt')
P-e ce sera mieux si on créer une fonction qui appelle `fetch`, surtout pour éviter de dupliquer le logique de génération de `Authorization` partout.

2021-05-12 07:10 UTC, hfroot commented on front-end/src/views/PublishPage/CanteenInfos.vue
> +      />
On a besoin du nombre des repas servis aussi

2021-05-12 07:14 UTC, hfroot commented on front-end/src/views/PublishPage/CanteenInfos.vue
> +      />
C'est quoi l'idée a ce moment après l'utilisatrice donne sa confirmation de publier les données - est-ce qu'ils seront automatiquement afficher ? Si oui, on doit penser comment on veut afficher la carte des régions.

2021-05-12 07:17 UTC, hfroot commented on front-end/src/views/PublishPage/CanteenInfos.vue
> +        if (response.status === 204) {
Pourquoi 204 pas 200 ?

2021-05-12 07:20 UTC, hfroot commented on front-end/src/views/PublishPage/CanteenInfos.vue
> +          console.log(error);
Est-ce qu'on doit supprimer ça avant déploiement ? Je pense qu'on doit considérer comment ces logs peuvent être envoyer au nous.

2021-05-12 07:23 UTC, hfroot commented on front-end/src/views/PublishPage/CanteenInfos.vue
> +    background-color: $dark-white;
Est-ce que c'est possible d'avoir `$orange` pour ça et les autres (avec :deep() peut-être) ? Je pense que le gris est triste. Je sais pas si tu veux des autres retours design pour l'instant, j'apprécie que tu as utilisé les mêmes components pour développer plus vite.

2021-05-13 19:36 UTC, Forster-Groux commented on front-end/src/views/PublishPage/index.vue
> +        const prefilledPublication = await fetch(`${this.$api_url}/get-prefilled-publication`, {
Je préfère avoir l'info du contexte autant que possible dans le nom de la route

2021-05-13 19:38 UTC, Forster-Groux commented on front-end/src/views/PublishPage/CanteenInfos.vue
> +      />
:+1: pour les repas servis par contre je comprends pas ce que tu veux dire par les `keyPoints`

2021-05-13 19:39 UTC, Forster-Groux commented on front-end/src/views/PublishPage/CanteenInfos.vue
> +      />
En effet il va falloir se poser la question mais l'affichage dans la partie "nos-cantines" n'est pas prévu dans cette PR

2021-05-13 19:39 UTC, Forster-Groux commented on front-end/src/views/PublishPage/CanteenInfos.vue
> +        if (response.status === 204) {
204 c'est quand y'a pas de body dans le payload de retour, c'est assez classique lors d'un update.

2021-05-13 20:23 UTC, Forster-Groux commented on front-end/src/views/PublishPage/CanteenInfos.vue
> +    background-color: $dark-white;
J'ai essayé avec le light-orange mais je suis pas convaincu du résultat.

2021-05-14 08:44 UTC, hfroot requested changes
Deux dernières suggestions : 
 - envoyer un email au l'équipe (comme beta-testeur) quand quelqu'un /complete-publication. Alors, on peut leur contacter pour completer la publication
 - ajouter un GET pour les données d'affichage génération, (et, si on générer l'affichage et après s'inscrire, preremplir la page d'inscription)
 
Mais je pense que cettes choses peuvent être faites dans autres PRs

2021-05-14 08:44 UTC, hfroot commented on front-end/src/components/TheNavbar.vue
> +        jwt: localStorage.getItem('jwt'),
Malheureusement ça ne marche pas bien si on déconnecter - c'est difficile d'avoir du réactivité avec localStorage. D'ailleurs, peut-être c'est pas nécessaire d'avoir ce lien dans le navbar

2021-05-14 08:44 UTC, hfroot commented on front-end/src/data/KeyMeasures.js
> +    valueBio: null,
C'est un dommage de répéter ce code entre le front et back end à mon avis. P-e une amélioration pour l'avenir du coup.

2021-05-14 08:44 UTC, hfroot commented on front-end/src/data/submit-actions.js
> +  subscribeBetaTester,
Il y a aussi des `fetch`s sur ConnectPage, PublishPage index, et KeyMeasures.js. P-e appelles ce fichier fetch-actions.js pour définir aussi les actions GET qui demandent authentication ?

2021-05-14 08:44 UTC, hfroot commented on front-end/src/views/KeyMeasuresPage/DashboardPage.vue
> +    <router-link class="call-to-action" v-if="jwt" :to="{ name: 'PublishPage' }">Publier mes données</router-link>
Le lien ne marche pas - j'ai réparer un bogue similaire dans ma PR en utilisant directement le nom de la page 'enfant' que je veux afficher - ici, `CanteenInfo`

2021-05-14 08:44 UTC, hfroot commented on front-end/src/views/KeyMeasuresPage/DashboardPage.vue
> -    <p v-if="jwt"><i class="fas fa-check-square"></i> Vos données ont été sauvegardées</p>
J'aime avoir une indication n'importe où que les données ont été sauvegardées après /complete-login

2021-05-14 08:44 UTC, hfroot commented on front-end/src/views/PublishPage/CanteenInfo.vue
> +    max-width: 1170px;
Je trouve ça trop large honnêtement, le texte pour le champ et le champ sont très loin

2021-05-14 08:44 UTC, hfroot commented on front-end/src/views/PublishPage/PublishMeasurePage.vue
> +    background-color: $dark-white;
Tu peux partager le CSS en définissant le CSS dans `index.vue` et utilise :deep(#diagnostic-card) {...}

2021-05-14 08:44 UTC, hfroot commented on front-end/src/views/PublishPage/SubmitPublicationPage.vue
> +        makeDataPublic: true,
Je pense que c'est dangereux d'avoir une confirmation qui est déjà `true`, c'est plus facile de le ne lire pas.

2021-05-14 08:44 UTC, hfroot commented on front-end/src/views/PublishPage/SubmitPublicationPage.vue
> +          alert("Vos données ont bien été publiées");
C'est pas claire à mon avis. Car elles ne sont pas automatiquement ajoutées au nos-cantines, peut-être utilises "Merci de publier vos données, l'équipe ma cantine contactera vous bientôt pour vérifier vos données et compléter la publication" ou qqch.

2021-05-14 08:44 UTC, hfroot commented on front-end/src/views/PublishPage/index.vue
> +    </div>
P-e ajoutes une phrase pour éxpliquer pourquoi on veut publier les données, et quoi ça veut dire. Par exemple:
"Pourquoi publier les données de ma cantine ?

Une des mesures de la loi EGAlim demande que les convives sont informés sur la part des produits de qualité et durables des repas servis et des démarches entreprises pour l’acquisition de produits issus du commerce équitable. Lisez plus : information des usagers et convives. (lien vers la page mesures-phare)

Ce site rendre le processus facile, simplement completez notre formulaire, et l'équipe ma cantine contactera vous pour vérifier vos informations et compléter le processus. Après, vos données vont afficher sur notre site, avec les autres cantines." (lien vers nos-cantines)

2021-05-14 08:44 UTC, hfroot commented on front-end/src/data/KeyMeasures.js
>    getDiagnostics,
getDiagnostics a supposé qu'on ne reçoit pas des données `previous` et `latest` afin de décider quoi afficher sur KeyMeasuresHome. Avec l'introduction des défauts dans le back-end, la logique doit être mettre à jour. (ligne 47)

2021-05-14 09:13 UTC, Forster-Groux commented on api/domain/services/diagnostic-builder.js
> +const defaultDiagnostic = function(year) {
La couche infra c'est vraiment lié bdd, les modèles métiers c'est au domain de les déclarer. D'ailleurs on le fait pas vraiment parce qu'ils sont quasiment les mêmes que ceux de la bdd mais on sera surement amener à le faire de plus en plus (cad renvoyer uniquement les attributs voulus et pas toutes les colonnes de la bdd).

2021-05-14 09:16 UTC, Forster-Groux commented on front-end/src/data/KeyMeasures.js
> +    valueBio: null,
En fait on a 2 couches infra, une back-end et une localStorage, du coup ça me parait compliqué de pas avoir toute cette logique dupliquée (ça vaut pour les valeurs par défauts mais aussi les migrations par exemple)

2021-05-14 09:18 UTC, Forster-Groux commented on front-end/src/views/PublishPage/SubmitPublicationPage.vue
> +        makeDataPublic: true,
L'idée c'est de pousser à la transparence des données par défaut, on changera en fonctions des tests utilisateurs.

2021-05-14 09:19 UTC, Forster-Groux commented on front-end/src/views/PublishPage/SubmitPublicationPage.vue
> +          alert("Vos données ont bien été publiées");
Pour l'instant on est pas parti sur une vérification manuelle de notre part, ça va donc être automatisé dès qu'on aura 2-3 cantines qui auront rentrées leurs données et on le fera avec eux.

2021-05-14 09:21 UTC, Forster-Groux commented on front-end/src/views/PublishPage/index.vue
> +    </div>
Oui je suis d'accord mais je sais pas trop où le mettre et quelle phrase exactement, je voulais mettre ça sur staging pour leur montrer et avoir leurs avis.

2021-05-14 09:31 UTC, hfroot commented on front-end/src/views/PublishPage/SubmitPublicationPage.vue
> +          alert("Vos données ont bien été publiées");
Ok, mais pour l'instant c'est pas le cas, alors p-e n'ecris pas le chose avec l'email, mais c'est assez facile de changer ce texte de clarifier la situation maintenant ? P-e c'est une question pour Val qui savent mieux les atteints des cantines avec leur données

2021-05-14 09:32 UTC, Forster-Groux commented on api/tests/unit/application/complete-publication.test.js
> +          makeDataPublic: true
Bof, ça change rien ça rend pas la suite de test plus robuste.

2021-05-14 09:37 UTC, Forster-Groux commented on front-end/src/components/TheNavbar.vue
> +        jwt: localStorage.getItem('jwt'),
Je suis d'accord que ça peut manquer de réactivité mais je pensais regarder coment faire mieux une fois que cette pr et celle de l'authentication améliorée seraient merge. Et je pense c'est important qu'on ait ça dans la navbar quand on est connecté.

2021-05-14 09:38 UTC, Forster-Groux commented on front-end/src/data/submit-actions.js
> +  subscribeBetaTester,
Complètement d'accord, pour ConnectPage je voulais pas y toucher vu que y'a une PR en cours dessus. Et pour les GET je pensais faire ça dans une autre PR.

2021-05-14 10:19 UTC, Forster-Groux commented on front-end/src/data/KeyMeasures.js
>    getDiagnostics,
Haha en effet, c'est justement pour éviter ce cas de figures qu'on privilégie 1 endPoint par contexte, ça évite les régressions de ce type. Du coup pour ne pas non plus trop complexifier pour le moment j'ai considéré qu'on affiche le tableau de bord si on est connecté ou si on a des diagnostics dans le localStorage, comme ça plus besoin de la logique sur `hasResults`

2021-05-14 10:27 UTC, Forster-Groux commented on front-end/src/views/PublishPage/SubmitPublicationPage.vue
> +          alert("Vos données ont bien été publiées");
Oui c'est pour ça je voulais leur montrer ce que ça donne et voir avec elles pour ce genre de modif, le problème c'est que je peux pas leur montrer depuis la review app vu qu'elles sont pas reliées entre elles (back et front).

2021-05-14 11:14 UTC, hfroot approved these changes

2021-05-14 11:14 UTC, hfroot commented on front-end/src/router/index.js
> +        component: CanteenInfo,
On doit ajouter
```
meta: {
  title: "Cantine - Publication"
}
```
et pour validation
```
meta: {
  title: "Validation - Publication"
}
```
et finalement, dans `PublishMeasurePage.vue`
```
  created() {
    document.title = `${this.meta.title} - Publication - ma-cantine.beta.gouv.fr`;
  }
```
(Tu peux améliorer le texte bien sûr, avec l'idée de plus spécifique -> moins spécifique)
Ça donne l'onglet un nom utile pour mieux UX et a11y.

2021-05-14 11:30 UTC, merged