Actions dans le back
betagouv/ma-cantine pull request #2053
Opened 2022-11-02 20:43 UTC by hfroot

2022-11-04 11:23 UTC, hfroot commented on api/views/canteen.py
> +    pagination_class = UserCanteensPagination
This needs to change back for the API usage

2022-11-04 14:42 UTC, alemangui requested changes

2022-11-04 14:42 UTC, alemangui commented on api/tests/test_canteens.py
> +        # ie. pub, TD, sat, complete, create
On peut refactorer ça pour ne pas manipuler l'index manuellement. T'en penses quoi ? Je le mettrai dans ce commit : https://github.com/betagouv/ma-cantine/pull/2053/commits/28bcbecee928763bd854510f98cd24c01700baca mais on peut le reverser si tu n'est pas d'accord.
```python
expected_actions = [
            (needs_satellites, "10_add_satellites"),
            (needs_last_year_diag, "20_create_diagnostic"),
            (needs_to_complete_diag, "30_complete_diagnostic"),
            (needs_td, "40_teledeclare"),
            (needs_to_publish, "50_publish"),
            (complete, "95_nothing"),
        ]
        for index, (canteen, action) in zip(range(len(expected_actions)), expected_actions):
            self.assertEqual(returned_canteens[index]["id"], canteen.id)
            self.assertEqual(returned_canteens[index]["action"], action)
```

2022-11-04 14:42 UTC, alemangui commented on api/tests/test_canteens.py
> +    def test_get_canteen_summary(self):
```suggestion
    def test_get_single_canteen_actions(self):
```

2022-11-04 14:42 UTC, alemangui commented on api/urls.py
> +    path("canteensSummary/<int:year>", CanteenActionsView.as_view(), name="canteens_summary"),
On garde _actions_ ici aussi ? On peut aussi utiliser _List_ et _Retrieve_ pour faire la différence entre les views. Genre_
```python
path("canteenActions/<int:year>", CanteenActionsListView.as_view(), name="canteen_actions"),
path("canteenActions/<int:pk>/<int:year>", CanteenActionsRetrieveView.as_view(), name="single_canteen_actions")
```

2022-11-04 14:42 UTC, alemangui commented on api/views/canteen.py
> +class CanteenActionsView(ListAPIView):
On peut l'appeller `CanteenActionsListView` pour profiter de la nomenclature de DRF

2022-11-04 14:42 UTC, alemangui commented on api/views/canteen.py
> +class CanteenSummaryView(RetrieveAPIView):
On peut la nommer `CanteenActionsRetrieveView` p-e

2022-11-04 14:42 UTC, alemangui commented on api/views/canteen.py
> +            Canteen.objects.filter(central_producer_siret=OuterRef("siret"))
Vu que cette requête se fait dans la totalité des cantines (non seulement celles gérées par l'utilisateur identifié) on peut réfléchir à ajouter un index sur `central_producer_siret`.

2022-11-04 14:42 UTC, alemangui commented on api/views/canteen.py
> +    ordering = "modification_date"
Il nous manquent les `permission_classes` non ?

2022-11-04 14:42 UTC, alemangui commented on api/views/canteen.py
> +    permission_classes = [IsAuthenticatedOrTokenHasResourceScope, IsCanteenManager]
`IsAuthenticatedOrTokenHasResourceScope` veut dire qu'on ouvrira ces endpoints dans l'API publique. Je suis pour, mais il faudra penser à rajouter la doc (on peut rajouter une carte pour en penser)

2022-11-04 14:42 UTC, alemangui commented on data/models/canteen.py
> +            return Diagnostic.objects.get(canteen=self, year=year)
Pour éviter de faire un query sur toute la table on peut faire `self.diagnostic_set.get(year=year)`

2022-11-07 08:30 UTC, hfroot commented on api/views/canteen.py
> +    pagination_class = UserCanteensPagination
No - it was is the serializer that needed to change back, already done.

2022-11-08 08:39 UTC, hfroot commented on api/views/canteen.py
> +    ordering = "modification_date"
:facepalm:

2022-11-08 09:15 UTC, hfroot commented on api/views/canteen.py
> +    permission_classes = [IsAuthenticatedOrTokenHasResourceScope, IsCanteenManager]
Je l'enlevé pour l'instant, et on pourrait en penser dans un autre temps

2022-11-08 09:16 UTC, hfroot commented on data/models/canteen.py
> +            return Diagnostic.objects.get(canteen=self, year=year)
C'est pas utilisé, alors j'ai supprimé le code

2022-11-08 15:58 UTC, alemangui approved these changes
J'approuve même si on laisse ouverte la possibilité de changer le nommage. On se tient au courant.

2022-11-09 15:34 UTC, merged