page stats avec donnees matomo et infogram
betagouv/ma-cantine pull request #206
Opened 2021-05-05 17:22 UTC by JenniferStephan

hello, j'ai créé une page stats avec pour l'instant les données du site de beta.gouv.fr, une fois qu'on aura passé nos stats en publiques on pourra changer l'id

2021-05-06 09:20 UTC, Forster-Groux reviewed
Possible de faire la PR vers staging plutôt que main ?

2021-05-06 09:20 UTC, Forster-Groux commented on front-end/package.json
> +    "yarn": "^1.22.10"
D'où viennent ces ajouts ?

2021-05-06 09:20 UTC, Forster-Groux commented on front-end/src/router/index.js
> +import ConnectPage from '@/views/ConnectPage'
Je pense tu as un linter qui fait des modifs automatiques, vaudrait mieux éviter, on a pas encore choisi de linter mais je crois qu'il vaut mieux garder les ";" en fin de ligne.

2021-05-06 09:20 UTC, Forster-Groux commented on front-end/src/views/Stats.vue
> +    <h1>Statistiques</h1>
Il me semble que c'est une mauvaise pratique d'avoir plusieurs `h1` sur une même page.

2021-05-06 09:20 UTC, Forster-Groux commented on front-end/src/views/Stats.vue
> +      // Change for 162 when public
Plus besoin de ce commentaire.

2021-05-06 09:25 UTC, Forster-Groux commented
Peut être rajouter un lien vers cette page dans le footer aussi.

2021-05-06 14:22 UTC, Forster-Groux commented
Il faut que tu checkout ton package-lock.json aussi

2021-05-07 15:53 UTC, hfroot requested changes

2021-05-07 15:53 UTC, hfroot commented on front-end/src/router/index.js
> +export default router
Aussi ici changements du linter qui ne sont pas nécessaire pour l'instant

2021-05-07 15:53 UTC, hfroot commented on front-end/src/router/index.js
> +    ],
Aussi ici (lignes 26-71) changements du linter qui ne sont pas nécessaire pour l'instant

2021-05-07 15:53 UTC, hfroot commented on front-end/src/views/Stats.vue
> +      marginwidth="0"
Pour accessibilité c'est bon d'avoir un `title` pour chaque `iframe`

2021-05-07 15:53 UTC, hfroot commented on front-end/src/views/Stats.vue
> +    script.text = `!function(e,i,n,s){var t="InfogramEmbeds",d=e.getElementsByTagName("script")[0];if(window[t]&&window[t].initialized)window[t].process&&window[t].process();else if(!e.getElementById
Est-ce que tu peux couper cette ligne et aussi 59, 62, 65, dans quelques parts sur quelques lignes pour éviter d'avoir une long ligne qui est un peu difficile a lire ?

2021-05-07 15:53 UTC, hfroot commented on front-end/src/views/Stats.vue
> +      return `https://stats.data.gouv.fr/index.php?module=Widgetize&action=iframe&disableLink=0&widget=1&moduleToWidgetize=Actions&actionToWidgetize=getPageUrls&idSite=${this.matomoId}&period=day&dat
Pour les pages visitées et les canaux, est-ce que tu peux mettre la période de temps plus grands, et idéalement ajouter du texte avec la période ?

2021-05-07 15:53 UTC, hfroot commented on front-end/src/views/Stats.vue
> +    />
Est-ce que tu as suivi les suggestions ici pour assurer que l'infographique est accessible ? https://support.infogram.com/hc/en-us/articles/360013046634-Creating-accessible-content#screen

2021-05-07 15:53 UTC, hfroot commented on front-end/src/views/Stats.vue
> +  max-width: 720px;
Peut-être 900px, pour le tableur de visites par page ?

2021-05-12 11:46 UTC, Forster-Groux approved these changes

2021-05-12 12:04 UTC, merged