Gestion de publication des satellites depuis la page CC
betagouv/ma-cantine pull request #2094
Opened 2022-11-19 19:47 UTC by hfroot

2022-11-21 11:02 UTC, alemangui requested changes

2022-11-21 11:02 UTC, alemangui commented on frontend/src/views/CanteenEditor/PublicationForm/CentralKitchen.vue
> +      satelliteTableHeaders: [
Sauf erreur de ma part il y a moyen de dire qu'une colonne n'est pas "sortable". La dernière colonne affiche la flèche lors du hover mais ne fais pas de triage 

![image](https://user-images.githubusercontent.com/1225929/203033967-0b457841-7b7e-4814-bc2a-8e217e101ac3.png)

2022-11-21 15:17 UTC, alemangui commented on frontend/src/components/SatelliteTable.vue
> +          { text: "", value: "userCanView" },
Pire cas - si jamais il n'y a pas d'option pour ne pas trier une colonne sur Vuetify - on peut la cacher avec du css avec un _last-child_ des headers (vu que c'est la dernière colonne)

2022-11-25 15:47 UTC, hfroot commented on frontend/src/views/CanteenEditor/PublicationForm/CentralKitchen.vue
> +    <p v-if="published">
https://github.com/betagouv/ma-cantine/issues/2111

2022-11-25 15:56 UTC, hfroot commented on frontend/src/views/CanteenEditor/PublicationForm/index.vue
> +    <CentralKitchen v-if="isCentralCuisine" :originalCanteen="originalCanteen" />
J'ai commencé avec le spec de gestion des `central_serving`s ici : https://github.com/betagouv/ma-cantine/issues/2113

2022-11-30 10:21 UTC, hfroot commented
à faire : document.title pour la page vos cantines satellites

2022-11-30 10:24 UTC, hfroot commented
à faire : 
![satellite-add-decalage](https://user-images.githubusercontent.com/9282816/204771526-b1b752a6-7909-4e29-bb77-730ad1d9cb63.png)

2022-12-06 09:45 UTC, alemangui commented on frontend/src/views/CanteenEditor/PublicationForm/CentralKitchen.vue
> +    <p v-if="published">
Finalement les cuisines centrales pourront être publiées

2022-12-06 09:48 UTC, alemangui commented on frontend/src/views/CanteenEditor/PublicationForm/CentralKitchen.vue
> +    <!-- TODO: does central publish itself if not a site? -->
Pour la publication en masse : https://github.com/betagouv/ma-cantine/issues/2141

2022-12-06 10:19 UTC, alemangui approved these changes

2022-12-06 10:44 UTC, merged