Page chiffres : ne pas afficher les mesures si aucun diag
betagouv/ma-cantine pull request #2244
Opened 2023-01-20 11:59 UTC by hfroot

closes #2239

2023-01-20 16:01 UTC, alemangui requested changes

2023-01-20 16:01 UTC, alemangui commented on frontend/src/views/PublicCanteenStatisticsPage/index.vue
> +          Nous n'avons pas des données sur les mesures EGAlim atteindues par ces cantines parce que aucune cantine n'a
T'en penses quoi de :
`Aucune cantine n'a renseigné ces données pour l'année {{ year }}`

2023-01-24 11:49 UTC, hfroot commented on frontend/src/views/PublicCanteenStatisticsPage/index.vue
> +          Nous n'avons pas des données sur les mesures EGAlim atteindues par ces cantines parce que aucune cantine n'a
Je trouve 'données' trop vague, c'est à dire, quelles données ? En tant qu'utilisateur je me demande, pourquoi est-ce que ce message est affiché ? 

Alternative :

"Un __ sera disponible au moment où au moins une cantine remplit des données de leurs achats de {{ year }}."

Pour __ j'imagine "un recapitulatif"... un bilan EGAlim... un état de lieu EGAlim.... ?

2023-01-24 14:50 UTC, alemangui commented on frontend/src/views/PublicCanteenStatisticsPage/index.vue
> +          Nous n'avons pas des données sur les mesures EGAlim atteindues par ces cantines parce que aucune cantine n'a
Aucune cantine n'a renseigné des données relatives à la loi EGAlim pour l'année {{ year }}

2023-01-25 10:30 UTC, alemangui approved these changes

2023-01-25 11:22 UTC, merged