Ajouter le composant liens d’évitement du DSFR pour accéder au contenu
betagouv/ma-cantine pull request #2246
Opened 2023-01-20 14:14 UTC by hfroot

closes #2237 

Test by loading page then hitting 'tab'

2023-01-20 16:06 UTC, alemangui requested changes

2023-01-20 16:06 UTC, alemangui commented on frontend/src/App.vue
> +      <v-main id="contenu" style="width: 100%" class="mb-10">
Vu qu'on a les autres ids en anglais (_footer_, _header_, etc) on peut l’appeler plutôt "content" ?

2023-01-20 16:06 UTC, alemangui commented on frontend/src/components/AppHeader.vue
> +// focus-within not currently supported by IE but I think skiplinks are mostly helpful for people
On a quel comportement en IE ? Les liens invisibles ou toujours dans l'écran ?

2023-01-24 11:30 UTC, hfroot commented on frontend/src/App.vue
> +      <v-main id="contenu" style="width: 100%" class="mb-10">
J'ai suit les conseils du site DSFR pour les noms : https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/liens-d-evitement

Mais je suis d'acc que le mélange est un peu bizarre, avec un pref pour français.

2023-01-24 11:30 UTC, hfroot commented on frontend/src/components/AppHeader.vue
> +// focus-within not currently supported by IE but I think skiplinks are mostly helpful for people
Liens invisibles

2023-01-24 14:48 UTC, alemangui approved these changes

2023-01-24 15:32 UTC, merged