Dialog pour préciser les externalités environnementales
betagouv/ma-cantine pull request #2261
Opened 2023-01-25 15:17 UTC by alemangui

![image](https://user-images.githubusercontent.com/1225929/214601408-9098a351-9288-4418-af66-cd935b00b1f8.png)

![image](https://user-images.githubusercontent.com/1225929/214601442-95954294-2c39-419a-842d-9640f6d34179.png)

2023-01-25 18:13 UTC, hfroot commented
@alemangui j'ai ajouté un titre mais je trouve le texte en général difficile à lire, avec des phrase super longs, des grandes paragraphes, et le vocabulaire très légale. Est-ce qu'on peut créer qqch bcp plus simple et ajouter un lien vers le texte legal officiel ?

2023-01-25 18:20 UTC, hfroot requested changes
Voir mon commentaire au-dessus

2023-01-26 09:17 UTC, alemangui commented
@hfroot  Partant pour le titre.

Par contre concernant le texte je préfère le laisser comme ça pour cette PR. Il s'agit du même texte qui se trouve dans la section "à propos de la loi EGAlim" - et cette PR vient de https://github.com/betagouv/ma-cantine/issues/2204 où ça parle de la reprise de ce texte.

Cela dit, je suis d'accord avec toi que ce n'est pas très claire, mais pour moi c'est un réflexion hors le scope de cette PR : car il faudra aussi modifier les autres endroits de l'application qui l'ont.

2023-01-26 15:44 UTC, hfroot approved these changes

2023-01-26 15:55 UTC, merged