Ajouter garde-fous pour le nombre de jours ouvert par an
betagouv/ma-cantine pull request #2357
Opened 2023-02-14 16:49 UTC by hfroot

Selected the min by assuming it is normal to be open at least one day of the week every year (rounded down from holidays), and the max by number of days per year

Changes to the phrasing are most welcome

https://ma-cantine-metabase.cleverapps.io/question/472

![Screenshot 2023-02-14 at 17 47 32](https://user-images.githubusercontent.com/9282816/218802869-ae15aac0-e705-437b-876a-3eb2b9f926a1.png)

2023-02-16 13:17 UTC, alemangui commented on frontend/src/components/TeledeclarationPreview.vue
> +      if (!this.canteen.dailyMealCount) return
On est surs que les cantines qui arrivent ici ont `yearlyMealCount` ? En DB on a 18,864 cantines sans cette donnée. En même temps les seuls moyen d'arriver ici sont via l’éditeur diagnostic ou via les actions, et dans les deux cas je crois qu'on fait le check :thinking: Sinon on aurait un message _"Votre établissement sert des repas environ **null** jours par an."_

D'un coté, vu qu'on fait déjà un check pour cette donnée dans la ligne 615, si on se dit que le composant TeledeclarationPreview n'a pas à savoir quelle donnée est obligatoire, on peut rajouter le check. Comme ça si demain on décide de le rendre facultatif ce composant n'a pas à changer.

D'un autre, potentiellement yagni.

2023-02-16 13:32 UTC, alemangui commented on frontend/src/components/TeledeclarationPreview.vue
>        }
Fait ici : https://github.com/betagouv/ma-cantine/pull/2357/commits/12010885a0d7f4c88723af8268056b6b1eae7ced
N'hésites pas à revert si tu n'est pas d'accord

2023-02-16 13:32 UTC, alemangui commented on frontend/src/components/TeledeclarationPreview.vue
> +      if (!this.canteen.dailyMealCount) return
Fait ici: https://github.com/betagouv/ma-cantine/pull/2357/commits/32fa0570eb3a6665708bfda935c96b6ebc7da4b7

N'hésites pas à revert si tu n'es pas d'accord

2023-02-16 13:33 UTC, alemangui commented
@hfroot proposition de texte : https://github.com/betagouv/ma-cantine/pull/2357/commits/324f5e5e1ef3516f886580dfe8688cb37be2b2bb
Les chiffres renseignées pour « nombre de repas par jour » et « nombre de repas par an » donnent une moyenne de ${this.daysOpenPerYear} jours de service par an. S'il s'agit d'une erreur, veuillez modifier ces chiffres.

2023-02-16 13:33 UTC, alemangui approved these changes

2023-02-17 11:33 UTC, hfroot commented
> @hfroot proposition de texte : [324f5e5](https://github.com/betagouv/ma-cantine/commit/324f5e5e1ef3516f886580dfe8688cb37be2b2bb) _Les chiffres renseignées pour « nombre de repas par jour » et « nombre de repas par an » donnent une moyenne de ${this.daysOpenPerYear} jours de service par an. S'il s'agit d'une erreur, veuillez modifier ces chiffres._

Je préfère avoir l'info d'interet au debut pour rendre la phrase plus facile de lire rapidement. Quoi penses toi ? Ça suit l'exemple de cout denrées

![Screenshot 2023-02-17 at 12 32 00](https://user-images.githubusercontent.com/9282816/219641036-68760e0d-4354-4a27-a538-716be67ec49d.png)

2023-02-17 14:01 UTC, alemangui requested changes

2023-02-17 14:01 UTC, alemangui commented on frontend/src/components/TeledeclarationPreview.vue
> +          `Vos jours de service est estimé à ${this.daysOpenPerYear} par an. S'il s'agit d'une erreur, veuillez modifier les chiffres pour « nombre de repas par jour » et/ou « nombre de repas par an
```suggestion
          `Vos jours de service sont estimés à ${this.daysOpenPerYear} par an. S'il s'agit d'une erreur, veuillez modifier les chiffres « nombre de repas par jour » et/ou « nombre de repas par an ».`
```

2023-02-17 14:02 UTC, alemangui commented on frontend/src/components/TeledeclarationPreview.vue
> +          `Vos jours de service est estimé à ${this.daysOpenPerYear} par an. S'il s'agit d'une erreur, veuillez modifier les chiffres pour « nombre de repas par jour » et/ou « nombre de repas par an
@hfroot ça t'irait comme ça ?

2023-02-17 16:47 UTC, alemangui approved these changes

2023-02-17 16:59 UTC, merged