Page actions : vérifier le ministère avant donner l'option de TD
betagouv/ma-cantine pull request #2366
Opened 2023-02-17 17:00 UTC by hfroot

J'ai suit https://stackoverflow.com/a/51351406/3845770 pour les migrations

2023-02-20 10:07 UTC, alemangui requested changes

2023-02-20 10:07 UTC, alemangui commented on api/views/canteen.py
>          is_satellite_query = Q(production_type=Canteen.ProductionType.ON_SITE_CENTRAL)
Excellente idée de requeter la table intermédiaire .

Par contre, sauf erreur de ma part il n'y a pas besoin de créer la relation `CanteenSectorRelation` si on n'ajoute pas d'autre information dedans à part les `pk` de la cantine et le secteur. Par exemple, cette ligne pourrait se faire aussi en important le modèle _data.models.canteen.Canteen_sectors_ qui est créé automatiquement par Django :

```python
from django.apps import apps
canteen_sector_relation = apps.get_model(app_label="data", model_name="Canteen_sectors")
has_sector_requiring_line_ministry = canteen_sector_relation.objects.filter(
    canteen=OuterRef("pk"), sector__has_line_ministry=True
)
```
De plus, comme ça on n'aurait pas besoin de migrations ni du modèle additionnel créé

2023-02-21 09:00 UTC, alemangui commented on data/models/canteen.py
> +    sectors = models.ManyToManyField(Sector, through="CanteenSectorRelation")
Suite à https://github.com/betagouv/ma-cantine/pull/2366#discussion_r1111732056 ce changement n'est peut-être pas nécessaire

2023-02-21 12:17 UTC, hfroot commented
Ah oui merci @alemangui je ferme cette branche et recrée une autre

2023-02-21 12:17 UTC, closed without merging