Suivi achats : visualisation d'achats par catégorie et famille
betagouv/ma-cantine pull request #2406
Opened 2023-03-03 10:13 UTC by hfroot

Closes #2404

2023-03-06 16:59 UTC, alemangui commented
Après discussion avec le produit, on va créer une page dédiée aux stats, cela permettra de ne pas alourdir la page actuelle (et donc de rendre difficile à trouver les différents éléments), et aussi d'éditorialiser la page de synthèse des achats.

Afin de rendre cette page découvrable, on mettra une carte à la place de l'illustration qui servira de lien vers cette nouvelle page stats :

![image](https://user-images.githubusercontent.com/1225929/223174363-6035f734-c792-4f48-ae9e-28b2d017e548.png)

Si l'utilisateur n'a pas d'achats l'illustration s'affiche comme avant :

![image](https://user-images.githubusercontent.com/1225929/223174133-eea32901-b8c7-45e5-8e08-fccd8448ab2a.png)

Ceci emmène l'utilisateur dans la page de synthèse, qu'on pourra par la suite continuer à développer et à ajuster.

![image](https://user-images.githubusercontent.com/1225929/223178805-b9fb4d64-9bb7-4e33-a8b3-6b5590bc4ca4.png)

Ces changements sont dans le commit https://github.com/betagouv/ma-cantine/pull/2406/commits/cc43651ec39edce4c00a7056ec3a6ad1cfd2ac00 on peut en discuter demain :+1:

2023-03-07 09:53 UTC, alemangui requested changes

2023-03-07 09:53 UTC, alemangui commented on frontend/src/constants.js
> +      colorHex: "#9C27B0",
On peut obtenir le code Hex des couleurs vuetify programmatiquement :
```javascript
import colors from "vuetify/lib/util/colors"
...
console.log(colors["red"]["base"])
// #f44336
console.log(colors["red"]["lighten1"])
// #ef5350
```
donc on pourrait les utiliser plutôt comme ça pour éviter d'avoir à hard-coder le code Hex ici

2023-03-07 14:35 UTC, hfroot commented
Améliorations pour une deuxième PR:
- filtrer la liste de cantines pour afficher que les cantines avec des achats
- filtrer les années selon la cantine selectionnée
- URL historique

2023-03-07 15:54 UTC, alemangui approved these changes

2023-03-07 15:57 UTC, alemangui commented
@hfroot J'ai enlevé les `colorHex` restants dans le code, si t'es OK avec ça tu peux merger

2023-03-08 09:54 UTC, merged