Améliorations affichage
betagouv/ma-cantine pull request #2424
Opened 2023-03-10 19:45 UTC by hfroot

Mon but c'est de simplifier l'affichage et souligner les éléments le plus importants aux convives

2023-03-14 15:47 UTC, hfroot commented
@alemangui I changed the logo a bit to fix the bug where the aspect ratio wasn't respected. This does mean that the heading no longer looks like those in the PDFs I've generated. I can generate new ones but I'm feeling lazy, so here is just one example of the difference for high content posters:
[logo-change.pdf](https://github.com/betagouv/ma-cantine/files/10970655/logo-change.pdf)

2023-03-16 09:40 UTC, alemangui commented
J'aime bien en général, mais j'ai quelques retours (on peut en discuter de vive voix)
- Je ne suis pas convaincu de l'entête  « Manger plus saine et écolo », pas sur que ça ajoute quelque chose à l'affiche et ça prend bcp de place
- Je trouve qu'il y a beaucoup de typos différentes (huit par exemple pour le high-content) - ce qui rend un peu compliqué de savoir où se focaliser. Je pense qu'on peut simplifier un peu la typographie.
- Est-ce que ça vaut la peine qu'on mette les secteurs ? (dans le sens où les convives savent qu'iels sont dans une cuisine / hôpital, etc). Pas sur que ça soit une info intéressante

2023-03-16 09:51 UTC, alemangui requested changes

2023-03-16 09:51 UTC, alemangui commented on frontend/src/views/GeneratePosterPage/CanteenPoster.vue
> +      let linesOfVariableContent = 0
Vu qu'on n'est pas vraiment en train de compter des lignes, est-ce que renommer cette variable à `contentWeight` ou qqchose comme ça aurait plus de sense ? On peut déterminer que le "poids" du contenu va de 0 - 25 et qu'on fait des calculs par rapport à ce poids. Mais l’appeler "linesOfVariableContent" peut induire en erreur

2023-03-16 09:51 UTC, alemangui commented on frontend/src/views/GeneratePosterPage/CanteenPoster.vue
> +      const charactersPerLine = 90 // estimate, changes based on font size
Je ne pense pas que ça soit nécessaire de traduire en lignes approximatives, on peut laisser la valeur crue - de toute façon cette fonction n'est utilisée que par "isHighContent" et "isLowContent", donc on changerait nos thresholds en fonction.

2023-03-16 09:51 UTC, alemangui commented on frontend/src/views/PublicCanteenStatisticsPage/index.vue
> +              <router-link :to="{ name: 'CanteensHome' }">nos cantines</router-link>).
:thinking: on peut regarder après nos configs eslint

2023-03-20 10:28 UTC, alemangui commented
Utilisation des catégories au lieu des secteurs dans l'affiche (et éventuellement dans la publication aussi).

2023-03-20 10:31 UTC, alemangui commented on frontend/src/views/GeneratePosterPage/CanteenPoster.vue
> +      const charactersPerLine = 90 // estimate, changes based on font size
Au temps pour moi

2023-03-20 14:38 UTC, alemangui commented
@hfroot Created card for category use instead of sectors. I did a few adjustments and approved, feel free to merge if you agree!

2023-03-20 14:38 UTC, alemangui approved these changes

2023-03-20 16:54 UTC, merged