Rendre la page pour publier la cantine plus clair
betagouv/ma-cantine pull request #2435
Opened 2023-03-14 16:10 UTC by hfroot

Changements faits :

Tous:
- Ajouter coche dans le nav à côté du mot "Publication"
- MAJ titre de la page en fonction d'état

Cantines CC avec site:
- deplacer le PublicationStateNotice au debut de la page

2023-03-14 17:30 UTC, hfroot commented
Pour une deuxième PR: améliorer la page de publication pour les CC et les CC serving
![Screenshot from 2023-03-14 18-29-55](https://user-images.githubusercontent.com/9282816/225089221-4efc44f3-3296-4954-b8bb-667f1d69a887.png)
![Screenshot from 2023-03-14 18-29-40](https://user-images.githubusercontent.com/9282816/225089224-f60762fa-f08e-4ca4-b721-d9386781d0aa.png)

2023-03-16 14:21 UTC, hfroot commented
TODO: move the satellites to a separate tab like diagnostics years

2023-03-21 09:17 UTC, alemangui requested changes

2023-03-21 09:17 UTC, alemangui commented on frontend/src/components/CanteenNavigation.vue
> +              <v-list-item-title class="text-body-2 pl-6 d-flex align-center">
Je préfère quand les éléments du sidebar sont en bold, ça donne moins de variation de typographie et ça permet de comprendre que ce sont des éléments cliquables tout comme leurs parents

2023-03-21 12:44 UTC, alemangui commented on frontend/src/router/index.js
> +        path: "publier-satellites",
Suggestion ici : https://github.com/betagouv/ma-cantine/pull/2435/commits/abc8f8298ef53b0785316bcafd45e7b8681b4ec8

2023-03-21 12:44 UTC, alemangui commented on frontend/src/views/CanteenEditor/PublishSatellites.vue
>      <h1 class="font-weight-black text-h4 my-4">Publier mes satellites</h1>
Petit ajustement ici : https://github.com/betagouv/ma-cantine/pull/2435/commits/7cb438eae89adb1dbe97c103575f0e93fb450a94

2023-03-22 09:31 UTC, hfroot commented
![Screenshot from 2023-03-22 10-29-12](https://user-images.githubusercontent.com/9282816/226860355-0192aa5f-a9e6-40c4-a15a-a52170e5800a.png)

2023-03-23 09:06 UTC, alemangui approved these changes

2023-03-24 08:26 UTC, merged