Allows empty values for quality-products validation (#244)
betagouv/ma-cantine pull request #247
Opened 2021-06-07 09:46 UTC by alemangui

Closes #244

2021-06-07 10:15 UTC, hfroot requested changes

2021-06-07 10:15 UTC, hfroot commented on frontend/src/validators.js
> +  positiveNumberOrEmpty(input) {
Peut-être on veut avoir l'option de mettre 0 - comme Val a dit c'est different que si on ne sais pas les chiffres.

2021-06-07 10:15 UTC, hfroot commented on frontend/src/validators.js
>      const errorMessage = "Ce champ doit contenir une chiffre supérieure à zéro"
"Ce champ doit contenir une chiffre supérieure à zéro ou être vide" peut-être ?

2021-06-07 10:15 UTC, hfroot commented on frontend/src/views/PublishPage/CanteenInfo.vue
> -            :rules="[validators.positiveNumber]"
Je pense qu'ici on veut avoir une chiffre, alors `positiveNumber` est mieux

2021-06-07 10:21 UTC, Forster-Groux approved these changes

2021-06-07 14:11 UTC, alemangui commented on frontend/src/views/PublishPage/CanteenInfo.vue
> -            :rules="[validators.positiveNumber]"
Mais il faut aussi que l'utilisateur puisse ne rien mettre non ?

2021-06-07 14:19 UTC, alemangui commented on frontend/src/validators.js
>      const errorMessage = "Ce champ doit contenir une chiffre supérieure à zéro"
Je partirai sur un truc comme "Ce champ doit contenir un nombre positif ou rester vide", ça me semble plus simple :thinking:

2021-06-07 15:00 UTC, hfroot commented on frontend/src/validators.js
> +    if (!input || input.length === 0 || parseFloat(input) === 0) return true
`parseFloat(input) >= 0` plutôt ?

2021-06-07 15:00 UTC, hfroot commented on frontend/src/views/PublishPage/CanteenInfo.vue
> -            :rules="[validators.positiveNumber]"
À mon avis c'est obligatoire à ce point du parcours, et 0 est invalide - mais peut-être on veut vérifier avec Jenn/Val coté métier

2021-06-07 15:01 UTC, hfroot requested changes

2021-06-07 15:01 UTC, hfroot commented on frontend/src/validators.js
> +    if (!input || input.length === 0 || parseFloat(input) === 0) return true
`parseFloat(input) >= 0` plutôt ?

2021-06-07 15:16 UTC, alemangui commented on frontend/src/validators.js
> +    if (!input || input.length === 0 || parseFloat(input) === 0) return true
:facepalm: décidément il ne faut pas coder vacciné :smile:

2021-06-07 15:34 UTC, alemangui commented
@hfroot Merci de tes feedbacks :+1:  du coup on a deux validators différents : `nonNegativeOrEmpty` et `greaterThanZero`, ce dernier étant utilisé pour _CanteenInfo.vue_

2021-06-07 15:51 UTC, hfroot commented
Quand je suis sur /publication/, et il y a un nom, SIRET, et mode de gestion mais rien d'autre, et je click sur "Valider", il me rediriger au la prochaine page malgré les données manquantes.

2021-06-07 19:34 UTC, alemangui commented
Très bien vu @hfroot, c'est un bug provenant de la réécriture de l'app : deux formulaires n'avaient pas leur `v-model` de validation lié, du coup la validation ne faisait rien.

2021-06-08 11:11 UTC, hfroot approved these changes

2021-06-08 11:52 UTC, merged