Créer diagnostics pré-remplis dans un clic
betagouv/ma-cantine pull request #2641
Opened 2023-05-23 14:26 UTC by hfroot

2023-05-23 14:34 UTC, hfroot commented
@alemangui j'ai oublié qu'on a dit qu'on va au début faire le multi-preview de TDs. Je pense que tu pourrais reviewer quand même ce code mais p-e on le merge que quand c'est fait

2023-05-23 15:59 UTC, alemangui requested changes

2023-05-23 15:59 UTC, alemangui commented on api/tests/test_purchases.py
> +        self.assertEqual(body["valueFruitsEtLegumesCommerceEquitable"], 0.0)
Note à discuter éventuellement : ceci induit un petit changement de comportement (qui est d'ailleurs peut-être voulu). Précédemment, lorsqu'une valeur était `None` pour le purchases summary on ne mettait pas de valeur numérique dedans.

Cela dit, `0.0` est peut être plus proche de la vérité : si je n'ai pas des achats d'un type, c'est que j'ai zéro. Et d'ailleurs cela n'a pas d'impact sur les étiquettes UI pour remplir les montants, donc ça n'induit pas une régression.

2023-05-23 15:59 UTC, alemangui commented on api/tests/test_purchases.py
> +        self.assertEqual(errors[0], "Inconnue cantine : 666")
```suggestion
        self.assertEqual(errors[0], "Cantine inconnue : 666")
```

2023-05-23 15:59 UTC, alemangui commented on api/tests/test_purchases.py
> +        self.assertEqual(errors[1], f"Vous ne gerez pas la cantine : {not_my_canteen.id}")
```suggestion
        self.assertEqual(errors[1], f"Vous ne gérez pas la cantine : {not_my_canteen.id}")
```

2023-05-23 15:59 UTC, alemangui commented on data/models/canteen.py
> +        PREFILL_DIAGNOSTIC = "18_prefill_diagnostic", "Créer et pre-remplir le diagnostic"
```suggestion
        PREFILL_DIAGNOSTIC = "18_prefill_diagnostic", "Créer et pré-remplir le diagnostic"
```

2023-05-24 08:15 UTC, hfroot commented on api/tests/test_purchases.py
> +        self.assertEqual(body["valueFruitsEtLegumesCommerceEquitable"], 0.0)
Oui - je suis d'acc que c'est un changement mais je pense que c'est juste. En plus on a fait le pré-remplissage avec 0 côté front, alors je pense pas que les utilisateurs vont voir un difference

2023-05-25 15:05 UTC, alemangui approved these changes

2023-05-25 15:07 UTC, alemangui commented on api/urls.py
> +        "diagnosticsFromPurchases/<int:year>",
@hfroot J'ai fait ce changement ici : https://github.com/betagouv/ma-cantine/pull/2641/commits/4eb061a5d891e1fd27001983b53a349a609e72e2
Si tu es d'accord on peut merger, sinon on peut en discuter davantage et éventuellement faire un revert dessus

2023-05-30 09:41 UTC, merged