Ajouter un filtre pour la measure appro pour les cantines publiées
betagouv/ma-cantine pull request #2688
Opened 2023-06-15 12:43 UTC by hfroot

2023-06-15 13:14 UTC, hfroot commented
Relié : #2683

2023-06-16 11:59 UTC, alemangui requested changes

2023-06-16 11:59 UTC, alemangui commented on frontend/src/views/CanteensPage/CanteensHome.vue
> +              Measure EGAlim réalisée
```suggestion
              Mesure EGAlim réalisée
```

2023-06-16 11:59 UTC, alemangui commented on frontend/src/views/CanteensPage/CanteensHome.vue
Les requêtes partent en double à chaque fois qu'on change les filtres :
![image](https://github.com/betagouv/ma-cantine/assets/1225929/17ba69cb-05bf-40e4-b0a8-aff84b228e83)

2023-06-22 08:24 UTC, alemangui approved these changes

2023-06-26 08:04 UTC, merged