Nouveau tableau de bord : Quelques widgets pour la gestion de l'établissement
betagouv/ma-cantine pull request #2729
Opened 2023-06-30 13:27 UTC by hfroot

![Screenshot 2023-06-30 at 15-26-59 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/f9b946db-9e72-4a45-947b-1e72b2b485b9)

Pas exactement comme dans la maquette, mais c'est quelques pas dans la direction

2023-07-03 15:00 UTC, alemangui requested changes

2023-07-03 18:51 UTC, hfroot commented on frontend/src/views/DashboardManager/index.vue
> +      return this.canteenPreviews[5]?.id
Haha déso, c'était pour tester en locale

2023-07-03 19:58 UTC, hfroot commented on frontend/src/views/DashboardManager/index.vue
> +      <v-row>
J'ai fait un entre-deux pour l'instant
![Screenshot 2023-07-03 at 21-58-28 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/db31abc9-c74e-48e5-9b41-e110c45153c3)

2023-07-04 15:05 UTC, alemangui commented on frontend/src/views/DashboardManager/index.vue
> +          .then((response) => (this.centralKitchen = response))
Y a t'il une raison pour laquelle l'échec de `fetchPurchases` montre un message d'erreur à l'utilisateur et celui de `getCentralKitchen` est silencieux ?

2023-07-04 15:08 UTC, alemangui commented on frontend/src/views/DashboardManager/index.vue
> +      characteristics.splice(displayCount, Infinity)
Normalement on n'a pas besoin d'`Infinity` car si la valeur n'est pas présente splica supprime tous ce qui vient après. Ce n'est pas bloquant.

2023-07-04 15:41 UTC, alemangui requested changes

2023-07-04 15:41 UTC, alemangui commented on frontend/src/views/DashboardManager/index.vue
> +      const id = this.canteenId
Si l'utilisateur n'a pas de cantine, l'erreur est affiché (requête vers `undefined`)
![image](https://github.com/betagouv/ma-cantine/assets/1225929/e2410e3b-72b2-4b3b-856c-474a84f191d8)

2023-07-05 11:01 UTC, hfroot commented on frontend/src/views/DashboardManager/index.vue
> +      <v-row>
Ça marche, il me semble que c'est DSFR
![Screenshot 2023-07-05 at 12-44-43 Carte - Card - Système de Design de l'État](https://github.com/betagouv/ma-cantine/assets/9282816/981ca2f9-29d2-42cd-bfc9-7955d29877d1)

J'ai ajouté des changements pour mieux aligner le contenu https://github.com/betagouv/ma-cantine/pull/2729/commits/2c6a019ef093a6acadb76025f832add422feb943

![Screenshot 2023-07-05 at 12-59-32 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/07a83e4a-be51-4f4c-9aa9-619fca33ca3c)
![Screenshot 2023-07-05 at 12-59-11 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/ee5ee04e-6283-4592-b81e-1e1847471314)

2023-07-05 11:03 UTC, hfroot commented on frontend/src/views/DashboardManager/index.vue
> +      characteristics.splice(displayCount, Infinity)
En vrai j'ai copié collé le truc sans trop le lire (la honte)

2023-07-05 11:08 UTC, hfroot commented on frontend/src/views/DashboardManager/index.vue
> +          .then((response) => (this.centralKitchen = response))
À mon avis, c'est moins important que `getCentralKitchen` marche, vu que c'est plutôt utilisé comme lien pour être pratique, et on peut voir que c'est un satellite sans ces infos. Mais les achats sont peut-être plus grave - on veut pas donner l'impression que la cantine n'a pas des achats quand en vrai c'est un pb de reseaux. Mais avec ça en tête, je préférais de laisser le message d'erreur en dur dans le widget achats... j'ajoute ça

2023-07-05 11:26 UTC, hfroot commented on frontend/src/views/DashboardManager/index.vue
> +          .then((response) => (this.centralKitchen = response))
![Screenshot 2023-07-05 at 13-23-02 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/feb0dedc-2635-4aa0-8bac-7f01ceffc594)

f9bb4281

2023-07-05 12:00 UTC, hfroot commented on frontend/src/views/DashboardManager/index.vue
> +      const id = this.canteenId
![Screenshot 2023-07-05 at 13-55-09 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/4669baca-f839-48c6-ae53-c48d5cd65d05)
https://github.com/betagouv/ma-cantine/pull/2729/commits/279b6307a8277160a7312e24bb35e5b8fbec802f
J'ai finalement ajouté l'option de changer établissement. L'UX n'est pas encore défini dans la maquette alors je me suis permets de le créer.
![Screenshot 2023-07-05 at 13-58-48 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/08bf4eef-016a-4b8d-8bc2-7a9816218944)
![Screenshot 2023-07-05 at 13-59-39 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/c8b5a579-dc33-44ee-a626-91fd97d4935b)

2023-07-06 15:02 UTC, alemangui approved these changes

2023-07-07 10:09 UTC, merged