Fournir des ressources pour les débutant.e.s de la plateforme
betagouv/ma-cantine pull request #2734
Opened 2023-07-03 19:14 UTC by hfroot

2023-07-04 14:35 UTC, alemangui requested changes

2023-07-04 14:35 UTC, alemangui commented on frontend/src/views/ManagementPage/index.vue
> +          // TODO: ajouter une photo
On met une carte pour cet élément ?

2023-07-04 14:35 UTC, alemangui commented on frontend/src/views/ManagementPage/index.vue
> +            "Les mesures pour la restauration collective de la loi EGAlim en restauration collective sont un volet important dans l’ensemble de la loi EGAlim. Celles-ci ont vocation à...",
C'est juste moi ou la phrase est répétitive / difficile à comprendre ? "restauration collective" et "loi EGAlim" sont répétés deux fois dans le premier énoncé. Je mettrais simplement : 
"_Les mesures pour la restauration collective sont un volet important dans l'ensemble de la loi EGAlim. Celles-ci ont vocation à..._"
@arthurkleindesign t'en penses quoi ?

2023-07-04 14:35 UTC, alemangui commented on frontend/src/views/ManagementPage/index.vue
> +          title: "Comment utiliser la plateforme « ma cantine » ?",
Peut-être mettre des non-breaking spaces `&nbsp` pour éviter de couper les guimets ? 
![image](https://github.com/betagouv/ma-cantine/assets/1225929/758ef4ae-5623-4ef4-93a3-053065d1c049)

2023-07-05 12:05 UTC, hfroot commented on frontend/src/views/ManagementPage/index.vue
> +          title: "Comment utiliser la plateforme « ma cantine » ?",
déso j'ai pas poussé les derniers changements avant ton review

2023-07-05 12:09 UTC, hfroot commented on frontend/src/views/ManagementPage/index.vue
> +            "Les mesures pour la restauration collective de la loi EGAlim en restauration collective sont un volet important dans l’ensemble de la loi EGAlim. Celles-ci ont vocation à...",
C'est le texte de l'article. En tous les cas, peut-être on le remplace avec l'article sur 'pourquoi utiliser ma cantine' à ce stade quand il est écrit (discuté en mattermost) ?

2023-07-05 12:10 UTC, hfroot commented on frontend/src/views/ManagementPage/index.vue
> +          // TODO: ajouter une photo
J'ai pas encore poussé le changement avec la photo, c'était pour l'ajouter à la carte. Mais en fait je crois que je vais l'enlever pour l'instant vu que le DSFR conseil d'avoir toutes les cartes d'une ligne du même hauteur

2023-07-05 12:15 UTC, hfroot commented on frontend/src/views/ManagementPage/index.vue
> +            "Les mesures pour la restauration collective de la loi EGAlim en restauration collective sont un volet important dans l’ensemble de la loi EGAlim. Celles-ci ont vocation à...",
![Screenshot 2023-07-05 at 14-12-55 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/a6935ed5-6475-49bc-bedf-d1ee51bf44de)

2023-07-06 14:59 UTC, alemangui approved these changes

2023-07-07 10:09 UTC, merged