Bloquer l'import des achats si le fichier a déj éŧé
betagouv/ma-cantine pull request #2764
Opened 2023-07-11 15:24 UTC by hfroot

2023-07-12 13:11 UTC, alemangui requested changes

2023-07-12 13:11 UTC, alemangui commented on api/views/purchaseimport.py
> +        # self.purchases = purchases
On n'a plus besoin de cette ligne j'imagine non ?

2023-07-12 13:11 UTC, alemangui commented on data/models/purchase.py
> +        indexes = [models.Index(fields=["canteen"]), models.Index(fields=["import_source"])]
Normalement Django crée automatiquement des index pour les `ForeignKey`, pas besoin d'en avoir celle pour le champ "canteen"
https://docs.djangoproject.com/en/3.2/ref/models/fields/#foreignkey

> A database index is automatically created on the ForeignKey

2023-07-13 09:03 UTC, hfroot commented on api/views/purchaseimport.py
> +        self.purchases = []
C'est une bonne question. J'ai trouvé ça : https://stackoverflow.com/questions/40253562/does-django-reuse-the-same-instance-of-class-views-per-request et ici https://docs.djangoproject.com/en/4.2/ref/request-response/ on dit que "When a page is requested, Django creates an [HttpRequest](https://docs.djangoproject.com/en/4.2/ref/request-response/#django.http.HttpRequest) object that contains metadata about the request." qui est pas super clair à mon avis mais je crois que ça soutien le réponse dans stackoverflow. Aussi, on utilise `self.request` partout

2023-07-17 11:56 UTC, qloridant commented on api/views/purchaseimport.py
> +            self.purchases = matching_purchases.all()[:10]
Pourquoi on affecte ces deux paramètres maintenant ?

2023-07-17 12:24 UTC, hfroot commented on data/models/purchase.py
> +        indexes = [models.Index(fields=["canteen"]), models.Index(fields=["import_source"])]
https://github.com/betagouv/ma-cantine/pull/2764/commits/b4d0d87b9a0096815ab306154437d438e010e5de

2023-07-17 14:05 UTC, merged

2023-07-17 14:05 UTC, hfroot commented on api/views/purchaseimport.py
> +            self.purchases = matching_purchases.all()[:10]
discuté par visio