Partner form
betagouv/ma-cantine pull request #2789
Opened 2023-07-26 05:51 UTC by hfroot

![Screenshot 2023-07-26 at 00-36-55 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/16cebd55-dd03-4a19-8a72-80c150f71526)

2023-07-26 05:54 UTC, hfroot commented
@gauthierandre est-ce que tu peux regarder l'image au-dessus et donner des retours ici ? Sur le texte etc. Il y a des champs manquants comme localisation et la troisième option pour le prix de service - est-ce qu'il y a d'autres ?

2023-07-31 09:21 UTC, alemangui requested changes

2023-07-31 09:21 UTC, alemangui commented on api/tests/test_partnertypes.py
> +    def test_get_sectors(self):
```suggestion
    def test_get_partner_typesself):
```

2023-07-31 09:21 UTC, alemangui commented on api/views/partnertype.py
> +    include_in_documentation = True
Je ne crois pas qu'on ait envie d'exposer la ressource Partner aux utilisateurs business de l'API :thinking:

2023-07-31 09:21 UTC, alemangui commented on frontend/src/store/index.js
>        return Promise.all([
À ajouter une carte/issue pour avoir un seul call API avec les infos initiales - ça peut aider considérablement pour la performance initiale.

2023-08-01 08:14 UTC, alemangui commented
Ajouter un champ numéro téléphone

2023-08-01 08:14 UTC, alemangui commented
Lié à #2775

2023-08-01 14:53 UTC, alemangui commented on api/views/partnertype.py
> +    include_in_documentation = True
Enlevé ici : https://github.com/betagouv/ma-cantine/pull/2789/commits/5d488666c0d6f68dc08d6e8672cdefd38ad5a90a

2023-08-01 14:53 UTC, alemangui commented on frontend/src/store/index.js
>        return Promise.all([
Carte créée

2023-08-01 14:59 UTC, alemangui commented
J'ai ajouté une carte dans le jardin pour l'ajout du champ _national_ ou _choisissez votre département_. Ça se fera donc dans un deuxième temps.

2023-08-01 15:25 UTC, merged