Ajouter l'option de sous-titrer les webinaires
betagouv/ma-cantine pull request #2891
Opened 2023-08-09 16:55 UTC by hfroot

Il existe un nombre de services pour générer un fichier VTT https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API qui est nécessaire pour sous-titrer des vidéos.

https://language-tools.ec.europa.eu/SpeechServices/Transcription (compte requise)
https://scribe.cemea.org/
https://alphacephei.com/vosk/install

La discussion : https://mattermost.incubateur.net/betagouv/pl/dk1hau3aojrt78dwgefpwdnjfe

Il reste à faire le sous-titrage de 3 autres vidéos sur notre site.

![Screenshot 2023-08-09 at 18-47-33 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/b7ab2bfc-f89e-43c4-ba34-4056edad568d)
![Screenshot 2023-08-09 at 18-47-01 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/40f2fcb8-95cf-4187-83bc-73e8f61108ee)

2023-08-10 20:29 UTC, alemangui commented on frontend/src/views/CommunityPage/VideoTutorials.vue
> +              <track v-if="video.subtitles" label="Français" kind="subtitles" srclang="fr" :src="video.subtitles" />
Cette partie sera changée avec https://github.com/betagouv/ma-cantine/pull/2892, normalement on n'aura plus besoin de le spécifier à ce niveau là.

2023-08-10 20:33 UTC, alemangui requested changes

2023-08-10 20:33 UTC, alemangui commented on frontend/src/views/WebinairePage.vue
> +        pour qu'on puisse prioriser le sous-titrage de ce contenu.
Peut-être un peu plus concis ?
```suggestion
        pour prioriser le sous-titrage de ce contenu.
```

2023-08-10 20:33 UTC, alemangui commented on frontend/src/views/WebinairePage.vue
> +    <v-alert v-if="!mainVideo.subtitles" type="error" outlined>
Personnellement je trouve le style `error` un peu trop agressif pour ce message. Ça a l'air d'être un erreur de la part de l'utilisateur. Je serai en faveur d'un style `info`, mais partant pour en discuter.

2023-08-10 20:33 UTC, alemangui commented on frontend/src/views/WebinairePage.vue
> +        Pour plus d'info sur le status de l'accessibilité de ce site, consultez notre
Peut-être plus concis par ex "_Pour plus d'informations consultez notre déclaration d'accessibilité_" ?

2023-08-16 13:12 UTC, hfroot commented on frontend/src/views/WebinairePage.vue
> +    <v-alert v-if="!mainVideo.subtitles" type="error" outlined>
![Screenshot 2023-08-16 at 15-12-24 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/892cc1e6-91e7-4a29-8a60-4a2db665d61e)

2023-08-17 14:53 UTC, merged