Widget "mon établissement"
betagouv/ma-cantine pull request #3015
Opened 2023-09-29 12:20 UTC by hfroot

![Screenshot 2023-09-29 at 14-20-12 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/09d619b6-0c4b-4e83-9e10-e12f9c1ab7f9)

2023-09-29 12:42 UTC, alemangui requested changes

2023-09-29 12:42 UTC, alemangui commented on frontend/src/views/DashboardManager/index.vue
> +                    <p class="mb-0">
Ça serait intéressant de voir si en base de données on a des cantines sans commune, type de production, secteur, etc... et gérer l'affichage de ces cas. En gros deux options : 
- Le plus simple serait d'afficher un « inconnu » ou « pas renseigné », qui a en plus l'avantage d'attirer l'attention au gestionnaire du fait qu'il y a des infos à compléter, 
- Sinon on peut ne pas montrer le segment `<p>` correspondant à cette donnée.

2023-09-29 15:31 UTC, hfroot commented on frontend/src/views/DashboardManager/index.vue
> +                    <p class="mb-0">
J'ai ajouté "Non renseigné" au niveau de computed attributes (commune, prod type, sector, management type), mais pas pour le nom vu que c'est obligatoire niveau BDD.

2023-09-29 16:00 UTC, alemangui requested changes

2023-09-29 16:00 UTC, alemangui commented on frontend/src/views/DashboardManager/index.vue
> +      return capitalise(type?.title) || "Non renseigné"
Je peux me tromper, mais je crois que ça crash si on n'a pas de production type non ?

`type?.title` peut être évalué à `null`, et puis on envoie ça a la fonction `capitalise`:

```javascript
export const capitalise = (str) => {
  return str.charAt(0).toUpperCase() + str.slice(1)
}
```
qui appellerait `charAt` sur l'objet `null`

Ce serait plus safe de faire : 
```javascript
return type?.title ? capitalise(type.title) || "Non renseigné" 
```

2023-09-30 07:55 UTC, alemangui approved these changes

2023-10-02 08:44 UTC, merged