Publication widget
betagouv/ma-cantine pull request #3025
Opened 2023-10-02 16:55 UTC by hfroot

![Screenshot 2023-10-02 at 18-34-16 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/b08c9b86-8098-4cac-83aa-e19a4520675e)
![Screenshot 2023-10-02 at 18-33-53 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/abccdd6f-4499-4a40-8bf8-edf74081c9b0)
![Screenshot 2023-10-02 at 18-33-35 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/ce93dd70-9c17-47e3-b672-b444b9f37a4b)

2023-10-03 15:14 UTC, alemangui requested changes

2023-10-03 15:14 UTC, alemangui commented on frontend/src/views/DashboardManager/index.vue
> +    getPublishedPageViewCount() {
Si on décide d'avoir ce widget sur un fichier indépendant, ce call irait dedans

2023-10-04 08:50 UTC, hfroot commented on frontend/src/views/DashboardManager/index.vue
> +      // purchases widget
Vu qu'on a dit qu'au debut on va les mettre tous dans le même fichier, j'ai mis ça temporairement pour aider avec la refactorisation après

2023-10-04 11:33 UTC, alemangui requested changes

2023-10-04 11:33 UTC, alemangui commented on frontend/src/views/DashboardManager/index.vue
> +                    {{ isPublished && viewCount >= 0 ? viewCount : "-" }}
Si jamais `isPublished` est `true` et `viewCount` est `null`, la condition sera vraie et on afficherait `null` dans l'écran non ? Car `null >= 0` est `true`

2023-10-04 12:36 UTC, hfroot commented on frontend/src/views/DashboardManager/index.vue
> +                    {{ isPublished && viewCount >= 0 ? viewCount : "-" }}
why javascript, why

2023-10-04 13:07 UTC, alemangui approved these changes

2023-10-04 13:15 UTC, merged