Achats
betagouv/ma-cantine pull request #3026
Opened 2023-10-02 19:58 UTC by hfroot

2023-10-02 19:59 UTC, hfroot commented
En attente de validation des trois boutons quand on a des achats

2023-10-03 15:54 UTC, alemangui requested changes

2023-10-03 15:54 UTC, alemangui commented on api/serializers/purchase.py
> +            "import_source",
Sachant qu'on peut potentiellement avoir des infos d'équipe sur les `import_source` (ou bien des campagnes, etc), on pourrait avoir une passe pour simplement retourner `hasImportSource` ou mieux encore `massImported` - qu'on remplit avec la logique qu'existe aujourd'hui dans https://github.com/betagouv/ma-cantine/pull/3026/files#diff-c52974edfadc67e5d4fcaf46b06639c96a88036c72b32681715eac6a358f9ae2R393

2023-10-03 15:54 UTC, alemangui commented on frontend/src/views/DashboardManager/index.vue
> +                <p v-else>Source des données : {{ purchaseDataSourceString }}.</p>
Question... si on a des achats qui sont importés et d'autres non, pourquoi on prend seulement le premier `purchases[0]` ? Je rate peut-être un truc, mais on pourrait avoir `import en masse`, `ajout manuel` et `import en mass et ajout manuel` non ?

2023-10-03 15:54 UTC, alemangui commented on frontend/src/views/DashboardManager/index.vue
> +                  class="dsfr-table"
Il y a deux props `class`, on peut les merger pour n'avoir qu'une seule. Sauf erreur de ma part les browsers gèrent le cas de plusieurs tags identiques différement

2023-10-03 15:54 UTC, alemangui commented on frontend/src/views/DashboardManager/index.vue
> +              <v-card-title class="pb-0"><h3 class="fr-h4 mb-0">Mes achats</h3></v-card-title>
Je pense que ça pourrait être un fichier à part ce widget, pour ne pas mélanger les calls/comportements dans l'`index`

2023-10-03 15:54 UTC, alemangui commented on frontend/src/views/DashboardManager/index.vue
>              <!-- How relevant are purchases to satellites? -->
On a eu la discussion pour les satellites avec Arthur. En DB prod on n'a que 5 satellites avec achats. Pour l'instant je laisserais le widget pour tout le monde (comme aujourd'hui). Je pense qu'on peut enlever ce commentaire.

2023-10-04 08:55 UTC, hfroot commented on frontend/src/views/DashboardManager/index.vue
> +                <p v-else>Source des données : {{ purchaseDataSourceString }}.</p>
P-e on pourrait en discuter, je savais pas trop comment decider, vu que qqn peut changer comportement ou voilà. Aussi il y aura un troisième, API ou qqch

2023-10-04 10:37 UTC, hfroot commented on frontend/src/views/DashboardManager/index.vue
> +      // TODO: if the latest purchase source is API show that too
https://github.com/betagouv/ma-cantine/issues/3035

2023-10-04 10:40 UTC, hfroot commented on frontend/src/views/DashboardManager/index.vue
> +                <p v-else>Source des données : {{ purchaseDataSourceString }}.</p>
ça te va si on fait ça en deuxième temps ?

2023-10-04 11:41 UTC, alemangui commented on data/models/purchase.py
> +        return True if self.import_source else False
T'en penses quoi de `return bool(self.import_source)` ?

2023-10-04 11:41 UTC, alemangui approved these changes

2023-10-04 13:00 UTC, merged