Modifications dashboard pour les cuisines centrales et satellites
betagouv/ma-cantine pull request #3062
Opened 2023-10-11 15:07 UTC by hfroot

2023-10-12 22:00 UTC, alemangui requested changes

2023-10-15 17:33 UTC, alemangui commented on frontend/src/views/MyProgress/index.vue
> +                <v-btn
Pour une autre PR : Cette logique d'affichage devra être placée à l'intérieur des composants individuels

2023-10-15 17:48 UTC, alemangui requested changes

2023-10-15 17:48 UTC, alemangui commented on frontend/src/views/MyProgress/index.vue
> +    usesOtherDiagnosticForMeasure(index) {
Petit détail : ça pourrait être plus lisible avec une var pour ne pas manipuler directement l'index dans les conditions. Par ex :
```javascript
const isApproTab = index === 0
...
   if (isApproTab) return !!this.centralDiagnostic
....
```

2023-10-15 17:48 UTC, alemangui commented on frontend/src/views/MyProgress/index.vue
> +    usesSatelliteDiagnosticForMeasure(tabItem) {
Détail pas obligatoire, peut-être que ça sera plus simple à suivre avec quelques variables intermédiaires genre :
```javascript
const isCentralCuisine = this.canteen?.productionType === "central" || this.canteen?.productionType === "central_serving"
if (!isCentralCuisine || tabItem.urlSlug === "qualite-des-produits" || tabItem.urlSlug === "etablissement") return false
return this.diagnostic?.centralKitchenDiagnosticMode === "APPRO"
```
T'en penses quoi ?

2023-10-15 17:48 UTC, alemangui commented on frontend/src/views/DashboardManager/ProductionTypeTag.vue
> +  /* --hover: var(--background-contrast-grey-hover);
Peut-on supprimer les lignes commentées ?

2023-10-15 17:48 UTC, alemangui commented on frontend/src/views/DashboardManager/index.vue
> +    <ProductionTypeTag v-if="canteen" :canteen="canteen" />
À discuter et potentiellement pour une autre PR : 
Sur le breakpoints `smAndUp` on pourrait le placer à droite pour éviter de prendre les premiers pixels verticaux sur ce tag : 
![image](https://github.com/betagouv/ma-cantine/assets/1225929/b9a4397e-c853-40f5-9cf3-d5d2ec95d2c9)

2023-10-16 07:44 UTC, alemangui requested changes

2023-10-16 07:44 UTC, alemangui commented on frontend/src/views/DashboardManager/EgalimProgression.vue
> +    <!-- <div class="d-flex" style="height: auto;">
On peut supprimer ces lignes

2023-10-16 14:03 UTC, hfroot commented on frontend/src/views/DashboardManager/DiversificationCard.vue
>        <p>{{ cardBody }}</p>
![Screenshot 2023-10-16 at 15-59-33 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/bd6ba9e5-616f-433e-aafb-09c9a8695621)

2023-10-16 14:08 UTC, hfroot commented on frontend/src/views/DashboardManager/DiversificationCard.vue
> +      if (this.delegatedToSatellite) {
![Screenshot 2023-10-16 at 16-08-19 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/6f1fb0b4-81df-4fec-a35a-da88be8438e3)

2023-10-16 14:39 UTC, hfroot commented on frontend/src/views/DashboardManager/ProductionTypeTag.vue
> +  /* --hover: var(--background-contrast-grey-hover);
Je les ai laissé dedans pour souvenir le nom de la couleur utilisé si jamais c'est utile avec la migration, mais p-e c'est pas nécessaire. Tu penses quoi ?

2023-10-16 14:40 UTC, hfroot commented on frontend/src/views/DashboardManager/EgalimProgression.vue
> +    <!-- <div class="d-flex" style="height: auto;">
Whoops merci

2023-10-16 14:40 UTC, hfroot commented on frontend/src/views/MyProgress/index.vue
> +    usesSatelliteDiagnosticForMeasure(tabItem) {
https://github.com/betagouv/ma-cantine/pull/3062/commits/f579b42e1485e6c9536d3fe0397a0be1ca023c9c

2023-10-16 14:56 UTC, alemangui approved these changes

2023-10-16 15:05 UTC, merged