Ma progression - enchaufage et info gaspi
betagouv/ma-cantine pull request #3096
Opened 2023-10-18 16:12 UTC by hfroot

Scope : mettre en place un structure pour les onglets ma progression.

Il y a un bug avec l'affichage du carré gris avec les infos de la CC dans le cas où la CC déclare que les données appro. Je trouve que ça sort du scope de cette PR alors j'ai créé un autre issu : https://github.com/betagouv/ma-cantine/issues/3098

Tip testing : j'ai un satellite qui a :

- un diag pour 2021
- une CC diag APPRO pour 2022
- une CC diag ALL pour 2023
- pas de diag pour 2024

Comme ça je peux tester tous les cas (presque) sur une page ma progression.

![Screenshot 2023-10-19 at 14-41-54 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/26d65c7c-8db7-40ae-b66c-7296129eca38)
![Screenshot 2023-10-19 at 14-41-42 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/3a213fa4-cb0a-4745-955f-669392db3b2f)
![Screenshot 2023-10-19 at 14-41-30 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/6e202369-7770-43c2-94f1-5307a49ba740)

2023-10-19 08:55 UTC, alemangui requested changes

2023-10-19 08:55 UTC, alemangui commented on frontend/src/views/MyProgress/ProgressTab.vue
> +    <p><i>Sauf mention contraire, toutes les questions sont obligatoires.</i></p>
Le texte _Sauf mention contraire, toutes les questions sont obligatoires_ n'est pas dans tous les tabs, notamment pas dans _Info Convives_ ni _Établissement_. À voir si c'est une omission du design ou s'il faut ajouter la logique nécessaire pour cacher cette section

2023-10-19 08:55 UTC, alemangui commented on frontend/src/views/MyProgress/ProgressTab.vue
> +<style></style>
P-e pas besoin du tag `style` pour l'instant

2023-10-19 08:55 UTC, alemangui commented on frontend/src/views/MyProgress/ProgressTab.vue
> +    measureIndex: {
En envoyant l'index on créé un couplement entre l'ordre de `progressComponents` dans ce fichier, et celui de `tabHeaders` dans l'autre. Autrement dit, un changement d'ordre dans les tabs nécessite la modification dans ces deux endroits.

On pourrait à la place de l'index envoyer l'id (ou `urlSlug`) et avoir un objet reliant ces IDs aux composants, par ex:
```javascript
components: {
    appro: ApproProgress,
    waste: WasteProgress,
    ...
}
```

Ceci rendrait aussi plus facile de trouver le `keymeasure` ici : https://github.com/betagouv/ma-cantine/pull/3096/files#diff-7643cc74e236e7279e60cf4420433e9abd3300b2a1a4ecdf3c879a6d38288924R76

2023-10-19 08:55 UTC, alemangui commented on frontend/src/views/MyProgress/ProgressTab.vue
> +      progressComponents: [
Est-ce que `progressComponents` duplique le `components` de la ligne 55 ?

2023-10-19 10:06 UTC, hfroot commented on frontend/src/views/MyProgress/ProgressTab.vue
> +    <p><i>Sauf mention contraire, toutes les questions sont obligatoires.</i></p>
AMA ça doit appliquer au tous formulaires dans le même tunnel pour être le meilleur UX

2023-10-20 12:26 UTC, alemangui requested changes

2023-10-20 12:37 UTC, alemangui approved these changes

2023-10-20 12:43 UTC, merged