Introduction mesure appro
betagouv/ma-cantine pull request #3100
Opened 2023-10-20 14:06 UTC by hfroot

Petit difference par rapport aux maquettes : j'ai intégrer les difference de seuils entre régions comme on a déjà fait sur d'autres endroits du site

![Screenshot 2023-10-20 at 16-05-08 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/51c949de-8ed9-4728-9335-0e5f44b4cf23)

2023-10-20 14:23 UTC, alemangui requested changes

2023-10-20 14:23 UTC, alemangui commented on frontend/src/views/MyProgress/information/QualityMeasureInfo.vue
> +      totales d’achats bios, de qualité, et durables. Sauf mention contraire, toutes les questions sont obligatoires.
Vu qu'on a déjà "Sauf mention contraire, toutes les questions sont obligatoires" dans la ligne suivante, ça ne me semble  pas nécessaire 

```suggestion
      totales d’achats bios, de qualité, et durables.
```

2023-10-20 14:23 UTC, alemangui commented on frontend/src/views/MyProgress/information/QualityMeasureInfo.vue
> +      pour les cantines {{ regionDisplayName ? `dans la région de ${regionDisplayName}` : "en France métropolitaine" }}.
Pour éviter des soucis avec les régions qui commencent par une voyelle et donc devraient être affichés avec `d'` au lieu de `de`.
```suggestion
      pour les cantines {{ regionDisplayName ? `dans la région « ${regionDisplayName} »` : "en France métropolitaine" }}.
```

2023-10-20 14:23 UTC, alemangui commented on frontend/src/views/MyProgress/information/QualityMeasureInfo.vue
> +    regionDisplayName() {
Pas obligatoire, mais ça me semble un peu contre-intuitif d'avoir une computed property appellé `regionDisplayName` qui retourne un string vide même quand la région est présente dans la cantine. On pourrait faire deux choses :

1. Mettre quelque chose dans le nom qui montre qu'il s'agit de la region ayant une exception, genre  `exemptedRegionName`, ou `regionExcetionDisplayName`
2. Changer la condition dans le template (L:6) pour dire :
```
// template
{{ applicableRules.hasQualityException ? `dans la région de ${regionDisplayName}` : "en France métropolitaine" }}. 
```
Et donc avoir cette fontion simplement retournant simplement le nom de la région : 
```
regionDisplayName() {
    return regions.find((r) => r.regionCode === this.canteen.region).regionName
}
```

2023-10-25 13:03 UTC, hfroot commented on frontend/src/views/MyProgress/information/QualityMeasureInfo.vue
> +      pour les cantines {{ regionDisplayName ? `dans la région de ${regionDisplayName}` : "en France métropolitaine" }}.
https://github.com/betagouv/ma-cantine/pull/3100/commits/aa5d57b4566cc2c7c0d3b1325f36317a940c81a5

2023-10-25 13:03 UTC, hfroot commented on frontend/src/views/MyProgress/information/QualityMeasureInfo.vue
> +    regionDisplayName() {
https://github.com/betagouv/ma-cantine/pull/3100/commits/aa5d57b4566cc2c7c0d3b1325f36317a940c81a5

2023-10-26 07:54 UTC, alemangui approved these changes

2023-10-26 07:54 UTC, merged