Ajout du appro-summary pour la page « ma progression »
betagouv/ma-cantine pull request #3138
Opened 2023-10-30 16:11 UTC by hfroot

![Screenshot 2023-10-30 at 17-09-56 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/a749d5bd-7410-4563-962b-3c2dd4b477b8)
![Screenshot 2023-10-30 at 17-10-04 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/0fa4d067-518d-40b0-a787-bb427048fcdc)

et quand il manque des données

![Screenshot 2023-10-30 at 17-10-54 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/0e5f5f09-adb5-4c5f-ba1f-51bfd049db22)

2023-10-30 21:14 UTC, alemangui requested changes

2023-10-30 21:14 UTC, alemangui commented on frontend/src/views/MyProgress/summary/QualityMeasureSummary.vue
> +      Complèter mes données
```suggestion
      Compléter mes données
```

2023-10-30 21:14 UTC, alemangui commented on frontend/src/views/MyProgress/summary/QualityMeasureSummary.vue
> +      return this.centralDiagnostic?.centralKitchenDiagnosticMode === "ALL"
On utilise aussi le central diagnostic si le mode est `APPRO` non ? Vu qu'on est sur le volet appro. Il suffit que le `centralDiagnostic` existe pour qu'on le prenne :thinking:

2023-10-31 08:10 UTC, alemangui requested changes

2023-10-31 08:10 UTC, alemangui commented on frontend/src/views/MyProgress/summary/QualityMeasureSummary.vue
> +            :value="diagnostic[field.key]"
On ne devrait pas utiliser `displayDiagnostic`? (Pareil pour d'autres endroits `QualityDiagnosticValue`)
![image](https://github.com/betagouv/ma-cantine/assets/1225929/4e44c09d-1a16-425e-8d86-f231c9125f63)

2023-10-31 08:26 UTC, alemangui requested changes

2023-10-31 08:26 UTC, alemangui commented on frontend/src/views/MyProgress/summary/QualityMeasureSummary.vue
> +                year: diagnostic.year,
`displayDiagnostic.year`? Dans le cas où le diagnostic n'est pas présent pour une satellite (quoique normalement ce bouton ne sera pas affiché, donc p-e pas nécessaire)

2023-10-31 08:26 UTC, alemangui commented on frontend/src/views/MyProgress/summary/QualityMeasureSummary.vue
Vu que maintenant on affiche cette section aussi pour les satellites, il faudra que la carte appro du dashboard soit cliquable même si la cuisine centrale gère l'appro du satellite. Aujourd'hui elle n'est pas cliquable
![image](https://github.com/betagouv/ma-cantine/assets/1225929/a7eb129b-c2e9-4cd4-a587-a5bb4c7ffc81)

2023-10-31 08:26 UTC, alemangui commented on frontend/src/views/MyProgress/summary/QualityMeasureSummary.vue
> +        Math.round(this.diagnostic.percentageValueBioHt * 100) ||
On utiliserait plutôt `displayDiagnostic` non ? (Pareil pour les autres méthodes)

2023-10-31 09:28 UTC, hfroot commented on frontend/src/views/MyProgress/summary/QualityMeasureSummary.vue
> +                year: diagnostic.year,
oui, ce bouton devrait pas être affiché dans ce cas

2023-10-31 09:33 UTC, hfroot commented on frontend/src/views/MyProgress/summary/QualityMeasureSummary.vue
https://github.com/betagouv/ma-cantine/pull/3138/commits/af87a8cb20ab45c4eac760b43d3b65588dfd60c9

2023-10-31 12:55 UTC, alemangui commented on frontend/src/views/MyProgress/summary/QualityMeasureSummary.vue
> +      Une synthèse de données sera disponible dès que votre cuisine centrale remplit leur diagnostic.
Ce bloc est affiché même si la cuisine centrale a déjà rempli le diagnostic, est-ce normale?

2023-10-31 12:55 UTC, alemangui commented on frontend/src/views/MyProgress/summary/QualityMeasureSummary.vue
> +    <v-expansion-panels v-if="!usesCentralDiagnostic" hover accordion tile flat class="mt-10">
On veut pas afficher les chiffres de la cuisine centrale ? C'est pour une autre PR ?

2023-10-31 13:43 UTC, alemangui approved these changes

2023-10-31 14:22 UTC, merged