Lien avec l'outil suivi achats et page ma progression pour l'année en cours
betagouv/ma-cantine pull request #3158
Opened 2023-11-03 16:13 UTC by hfroot

Figma 2310 & 3200

![Screenshot 2023-11-03 at 17-12-10 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/9936ee46-f734-44c7-b94d-46e585b358da)

![Screenshot 2023-11-03 at 17-11-40 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/1eb932ed-475c-4d98-8f57-64ed87e4ad59)

2023-11-06 16:13 UTC, alemangui requested changes

2023-11-06 16:13 UTC, alemangui commented on frontend/src/views/MyProgress/summary/QualityMeasureSummary.vue
> +      return !this.diagnostic.id
Je suis partagé concernant l'idée de déterminer si les données viennent des achats en prenant l'ID du diag, principalement car :
- Si on utilise ce composant ailleurs pour un diagnostic draft (non sauvegardé) ce ne serait plus adapté
- Si on utilise ce composant pour des données compilés d'ailleurs (par ex, pour visualiser des TD) ce ne serait plus adapté non plus

J'aurais une petite préférence pour être très explicite dessus, par ex en ajoutant le paramètre dans les props de la source de données : 
```javascript
  props: {
    diagnostic: {},
    usesCentralDiagnostic: {},
    usesPurchaseData: {
        default: false
    },
    ...
  },
```
Et donc dans _PurchasesSummary.vue_ on peut ajouter ce param `<QualityMeasureSummary :canteen="canteen" :diagnostic="purchasesSummary" usesPurchaseData="true" />`

Ce pattern pourrait être étendu pour d'autres sources de données (par ex `usesTeledeclarationData`, `usesLastYearData`, etc) si jamais on a besoin d'un comportement spécial dans ce composant.

2023-11-06 16:13 UTC, alemangui commented on frontend/src/views/MyProgress/summary/PurchasesSummary.vue
> +    noPurchases() {
**Optionnel** (j'approuverais qd même) :
En général j'ai une préférence pour ne pas utiliser des variables/propriétés négatives (par ex `isNotActive` ou `notAuthenticated`), car je les trouve un peu plus complexes à manipuler vu qu'on est très habitués à la négation `!` dans le développement logiciel.

Une alternative serait 
```javascript
hasPurchases() {
    return !!this.purchasesSummary?.valueTotalHt
}
```  
Ça serait aussi cohérent avec les autres nommages ailleurs dans l'appli comme `hasCanteens`, `hasViewRights`, `hasDepartments` etc

2023-11-16 11:25 UTC, hfroot commented
![Screenshot 2023-11-16 at 12-25-22 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/75e48452-04fc-44f9-b22c-50763655c932)

2023-11-16 11:42 UTC, alemangui approved these changes

2023-11-16 12:40 UTC, merged