Ma progression : sans diag de l'année choisie, essaye de montrer les données de l'année précendente et donner l'option de créer le diag avec ces données préremplies
betagouv/ma-cantine pull request #3162
Opened 2023-11-03 17:40 UTC by hfroot

Figma vue 2320

![Screenshot 2023-11-03 at 18-37-07 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/812fe750-b954-46e5-8f0e-7258b7e24fee)

2023-11-06 14:47 UTC, alemangui requested changes

2023-11-06 14:47 UTC, alemangui commented on frontend/src/views/MyProgress/ProgressTab.vue
> +              Méttre à jour
```suggestion
              Mettre à jour
```

2023-11-06 14:47 UTC, alemangui commented on frontend/src/views/MyProgress/ProgressTab.vue
> +      if (this.hasCentralDiagnosticForMeasure) return this.centralDiagnostic
Suite à notre discussion on ne devrait pas faire cette opération pour l'appro

2023-11-06 14:47 UTC, alemangui commented on frontend/src/views/MyProgress/ProgressTab.vue
> +      const payload = JSON.parse(JSON.stringify(this.lastYearDiagnostic))
Lié au commentaire sur l'appro, on ne devrait pas envoyer les champs appro dans la création de ce diag. 

Peut-être on devrait envoyer seulement les champs du volet en question

2023-11-06 14:47 UTC, alemangui commented on frontend/src/views/MyProgress/ProgressTab.vue
> +              <p class="mb-0">Données de {{ displayDiagnostic.year }}</p>
`text-uppercase`

2024-01-19 11:23 UTC, hfroot commented
Je crois qu'il faut avoir https://github.com/betagouv/ma-cantine/issues/3421 en place avant, surtout pour souligner quand il y a des nouveaux champs qui n'ont pas remplit

2024-02-08 09:30 UTC, closed without merging

2024-02-08 09:31 UTC, hfroot commented
J'ai fermé cette PR car on a décidé de prendre un autre approche