Tunnel : bouton sauvegarder et quitter
betagouv/ma-cantine pull request #3173
Opened 2023-11-08 13:56 UTC by hfroot

2023-11-09 08:36 UTC, alemangui requested changes

2023-11-09 08:36 UTC, alemangui commented on frontend/src/views/DiagnosticTunnel/index.vue
> +      })
On ajoute un catch avec un message d'erreur ?

2023-11-09 12:46 UTC, alemangui approved these changes

2023-11-09 15:35 UTC, merged

2023-11-29 10:27 UTC, Tdauvet89 commented
Hello @hfroot , il y a un soucis d'intégration sur ce bouton. La croix n'est pas bien placé par rapport au wording 
<img width="1115" alt="image" src="https://github.com/betagouv/ma-cantine/assets/145361544/f542687a-00ee-4edc-ba4f-c3fb8884a362">