Améliorations pied de page tunnel
betagouv/ma-cantine pull request #3175
Opened 2023-11-08 14:40 UTC by hfroot

2023-11-09 08:54 UTC, alemangui requested changes

2023-11-09 11:46 UTC, hfroot commented on frontend/src/views/DiagnosticTunnel/index.vue
Oui, c'est hors le scope de cette PR ama - c'est la responsabilité de chaque composant d'indiquer si le bouton est activé. Alors à voir avec le dév du tunnel appro

2023-11-09 12:45 UTC, alemangui approved these changes

2023-11-09 15:14 UTC, merged

2023-11-29 12:51 UTC, hfroot commented
@Tdauvet89 est-ce que tu as des retours du pied de page du tunnel ?

2023-11-29 15:24 UTC, Tdauvet89 commented
Il est lié au ticket https://github.com/betagouv/ma-cantine/issues/3252 @hfroot