Tunnel : ajouter les icones de tous les tunnels, et naviguer vers le prochain onglet sur la page ma progression à la fin d'un tunnel
betagouv/ma-cantine pull request #3192
Opened 2023-11-16 14:48 UTC by hfroot

Dans un deuxième temps, ajouter les champs progrès dans le back et les utiliser pour determiner si on affiche une synthèse ou l'introduction

![Screenshot 2023-11-16 at 15-47-57 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/cf971c21-4eaf-4e6f-9f6f-53b8696a8fa9)
![Screenshot 2023-11-16 at 15-47-44 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/c5f3cc84-71e1-4573-8c9d-ce5f823a895f)

2023-11-18 19:22 UTC, alemangui requested changes

2023-11-18 19:22 UTC, alemangui commented on frontend/src/views/DiagnosticTunnel/index.vue
> +      <v-row class="mx-auto constrained align-center py-6">
Personnellement je mettrais ce bloc seulement sur `smAndUp` pour ne pas occuper de l'espace en mobile.

![image](https://github.com/betagouv/ma-cantine/assets/1225929/ddd3ff9d-bd23-4d81-9d1c-e7010d5285f1)

2023-11-18 19:26 UTC, alemangui requested changes

2023-11-18 19:26 UTC, alemangui commented on frontend/src/views/DiagnosticTunnel/index.vue
> +          <v-row>
Pas besoin de ce `v-row`, ça rajoute seulement le flex. Donc si on met la classe `d-flex` sur le `v-col` d'en haut on peut l’enlever.

2023-11-18 19:27 UTC, alemangui commented on frontend/src/views/DiagnosticTunnel/index.vue
> +      <v-row class="mx-auto constrained align-center py-6">
https://github.com/betagouv/ma-cantine/pull/3192/commits/088680e8814a07eeeff79bfea4395495e5bb1957

2023-11-18 19:27 UTC, alemangui commented on frontend/src/views/DiagnosticTunnel/index.vue
> +          <v-row>
https://github.com/betagouv/ma-cantine/pull/3192/commits/088680e8814a07eeeff79bfea4395495e5bb1957

2023-11-18 19:28 UTC, alemangui commented
@hfroot Pour simplicité j'ai créé un commit avec mes deux petites remarques et approuvé la PR : https://github.com/betagouv/ma-cantine/pull/3192/commits/088680e8814a07eeeff79bfea4395495e5bb1957

Si tu es d'accord tu peux merger, sinon revert-le et on pourra en parler davantage.

2023-11-18 19:28 UTC, alemangui approved these changes

2023-11-19 16:00 UTC, hfroot commented on frontend/src/views/DiagnosticTunnel/index.vue
> +      <v-row class="mx-auto constrained align-center py-6">
merci !

2023-11-20 14:43 UTC, merged