{DRAFT] Tunnel : sauvegarder le progrès
betagouv/ma-cantine pull request #3193
Opened 2023-11-16 15:39 UTC by hfroot

2023-11-18 20:06 UTC, alemangui commented on frontend/src/views/MyProgress/ProgressTab.vue
> +            this.$router.push(this.modificationLink)
J'ai un peu peur du lag entre le click et l'ouverture du tunnel pour les personnes dans des connexions pas top - qui pourrait emmener à l'utilisateur cliquant plusieurs fois dans le bouton et à envoyer plusieurs requêtes. P-e désactiver le bouton et/ou mettre un spinner? (peut-être fait dans un second temps).

2023-11-18 20:50 UTC, alemangui requested changes

2023-11-18 20:50 UTC, alemangui commented on data/models/diagnostic.py
> +        SEVERAL = (
Je pense que c'est une erreur de formatting. La ligne fait moins de 119 chars, notre limite.

Dans cette même PR, on peut ajouter dans `.vscode/setttings.json`:
```"black-formatter.args": ["--line-length=119"]```

Pour éviter ce souci.

2023-11-18 21:32 UTC, alemangui commented on frontend/src/views/MyProgress/ProgressTab.vue
> +            this.$router.push(this.modificationLink)
Suggestion : https://github.com/betagouv/ma-cantine/pull/3193/commits/2d648668250c44112fbfa810e9a5019d3721456d

2023-11-18 21:33 UTC, alemangui approved these changes

2023-11-19 15:56 UTC, hfroot commented on frontend/src/views/MyProgress/ProgressTab.vue
> +            name: "DiagnosticTunnel",
Je pense que maintenant qu'on a les tunnels et alors on peut changer les données là, on n'a plus besoin de ce workaround

2023-11-20 14:44 UTC, merged