Tunnel appro : Améliorer la gesion d'erreurs
betagouv/ma-cantine pull request #3204
Opened 2023-11-22 12:29 UTC by hfroot

I've limited the scope of my changes to the total field for now, so that we can validate the changes before I make them to the other files.

Changes made
- I think it's bad practice for child components to modify props, so I've started the refactor on ErrorHelper to send changes to the payload via an event instead
- if a field fails validation for format reasons, then that error should be shown instead of the checkTotal error
- the number fields shouldn't silently do things like convert "80...70" to 80. Hence the `isBase10Number` check. More importantly, we need to be making sure that the decimal separator is behaving as we want it to, given that it could be a comma. I'm not conviced my fix so far is ideal, but at least it is erroring instead of silently converting things in the background.
- I've grouped the error messages together to take up less space and because I assume it is jarring to have multiple alerts for people using screen readers ([more on alerts](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Alert_Role))
- if the error helper was used (a value was updated from it) then keep all the fields on screen even after resolution. I think this is important given that so many errors come from sums of multiple fields.

![Screenshot 2023-11-22 at 12-16-08 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/c0627b9f-055d-4ff8-a1bd-e66445195056)
![Screenshot 2023-11-22 at 12-15-48 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/860de0b0-b2ae-4dd7-91c6-7ff362644561)
![Screenshot 2023-11-22 at 13-02-30 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/0ca4b78e-cb29-42d1-957a-889a54f24208)

2023-11-22 21:59 UTC, alemangui commented
@hfroot J'imagine que ce n'est plus en draft non ?

2023-11-22 22:45 UTC, alemangui requested changes

2023-11-22 22:45 UTC, alemangui commented on frontend/src/views/DiagnosticTunnel/QualityMeasureSteps/QualityTotalStep.vue
> +        <p class="ma-0">Il y a des erreurs dans le formulaire :</p>
```suggestion
        <p class="ma-0">Merci de vérifier les erreurs ci dessous :</p>
```

2023-11-22 22:45 UTC, alemangui commented on frontend/src/views/DiagnosticTunnel/QualityMeasureSteps/QualityTotalStep.vue
> +    updatePayloadFromComponent(componentPayload) {
Je renommerais cette fonction en quelque chose qui rend évident que la source n'est pas n'importe quel composant externe, mais plus précisément le composant ErrorHelper. Par exemple `onErrorHelperChange` ou `onErrorHelperUpdate`.

Ceci à cause de la ligne `this.errorHelperUsed = true`

2023-11-22 22:45 UTC, alemangui commented on frontend/src/views/DiagnosticTunnel/QualityMeasureSteps/ErrorHelper.vue
Je suis d'accord avec les changements de ce fichier, je tiens juste à donner un peu de contexte sur le pourquoi ça marchait avant sans erreur console. Depuis la doc sur les [mutations d'objets Vue](https://vuejs.org/guide/components/props.html#mutating-object-array-props) on peut lire : 

> When objects and arrays are passed as props, while the child component cannot mutate the prop binding, it will be able to mutate the object or array's nested properties. This is because in JavaScript objects and arrays are passed by reference, and it is unreasonably expensive for Vue to prevent such mutations

> ... As a best practice, you should avoid such mutations **unless the parent and child are tightly coupled by design**.

On pourrait dire que le composant `ErrorHelper` est "tightly coupled" avec son parent car ce sont des champs additionnels sur le même formulaire, et donc leur permettre de le modifier, mais c'est aussi bien d'avoir l'architecture d'événements comme écrite ici.

2023-11-22 22:45 UTC, alemangui commented on frontend/src/views/DiagnosticTunnel/QualityMeasureSteps/QualityTotalStep.vue
> +    addErrorHelperFields() {
Je renommerais ça à `updateErrorHelperFields` car on peut en enlever dans le cas où  `errorHelperUsed` est false.

D'ailleurs. pourquoi ce n'est plus une computed-property ? Ça pourrait simplement être `errorHelperFields` et être computed non ?

2023-11-22 22:45 UTC, alemangui commented on frontend/src/validators.js
> +function isBase10Number(input) {
Je ne mettrais pas cette fonctionnalité sur cette PR car :
- C'est déjà un souci en prod, non pas une régression 
- Ceci empêche les utilisateurs de mettre une chiffre décimale avec comma (le séparateur le plus utilisé en français). Sur cette capture d'écran on a à gauche la branche actuelle, à droite la plateforme main. Ce serait donc une régression fonctionnelle.
![image](https://github.com/betagouv/ma-cantine/assets/1225929/350d1d76-4a5c-446d-bc79-5bfcd745c552)

Éventuellement ce serait une tâche pour après, surtout que - sauf erreur de ma part - on n'a pas eu des soucis remontés des utilisateurs mettant plusieurs points sur leurs champs.

2023-11-23 13:05 UTC, hfroot commented
I am breaking this PR down into smaller separate PRs to separate concerns

2023-11-23 13:05 UTC, closed without merging