Tunnel appro : refacto de composant
betagouv/ma-cantine pull request #3211
Opened 2023-11-23 12:52 UTC by hfroot

2023-11-23 13:06 UTC, hfroot commented
Après ça et #3209 je vais faire le changement pour garder les champs sur l'écran si l'utilisateur les utilises. J'ai commencé ça en locale déjà.

2023-11-24 10:07 UTC, alemangui requested changes

2023-11-24 10:07 UTC, alemangui commented on frontend/src/views/DiagnosticTunnel/QualityMeasureSteps/ErrorHelper.vue
>            :class="$vuetify.breakpoint.mdAndUp ? 'narrow-field' : ''"
On n'a pas besoin de la classe `narrow-field` - d'ailleurs elle n'a aucun effet car le CSS correspondant manque. C'était un faute de copié/collé de la PR précédente. 

De plus, si on voulait dans le futur réduire la taille de ces champs dans les grands écrans, ça serait plus logique de le faire dans le container plutôt que dans chaque champ individuel.

2023-11-24 10:08 UTC, alemangui commented on frontend/src/views/DiagnosticTunnel/QualityMeasureSteps/ErrorHelper.vue
>            :class="$vuetify.breakpoint.mdAndUp ? 'narrow-field' : ''"
Fix ici : https://github.com/betagouv/ma-cantine/pull/3211/commits/2d01276e0b7711920a501103f2a47f0355221f9a

Si tu es d'accord n'hésite pas à merger

2023-11-24 10:09 UTC, alemangui approved these changes

2023-11-24 13:57 UTC, merged