Tunnel : UI synthèses
betagouv/ma-cantine pull request #3219
Opened 2023-11-23 16:57 UTC by hfroot

![Screenshot 2023-11-23 at 17-48-37 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/3da93104-16eb-4e7d-959d-5d83447d76a6)

2023-11-23 18:29 UTC, alemangui requested changes

2023-11-23 18:29 UTC, alemangui commented on frontend/src/views/DiagnosticTunnel/DiversificationMeasureSteps/index.vue
> +        <span class="fr-hint-text mt-2">Optionnel</span>
Note to self: Je ne comprends pas pourquoi je vois ces modifs qui ne sont pas dans la branche de la PR

2023-11-23 18:29 UTC, alemangui commented on frontend/src/views/DiagnosticTunnel/index.vue
> +.summary {
Est-ce que ces classes ne seraient pas plus adaptés étant dans `SummaryWrapper.vue` ? Car ce se charge justement de préparer les différents summaries pour le display ici, donc ça me semblerait plus adapté de tout regrouper sous `SummaryWrapper`. De plus, ce n'est réutilisé ailleurs (et ça ne le sera probablement jamais car dépendant de la UI du tunnel).

Pour moi `class="mx-auto constrained pa-10 summary scroll"` porrait être plutôt dans le `<div>` racine du `SummaryWrapper`.

2023-11-23 18:29 UTC, alemangui commented on frontend/src/views/DiagnosticTunnel/DiversificationMeasureSteps/index.vue
> +  <v-form @submit.prevent>
La PR ajoute le `v-form` ici et dans InformationMeasure, c'est parce que les autres l'ont et on avait oublié de les mettre sur ces deux là?

2023-11-24 09:17 UTC, hfroot commented on frontend/src/views/DiagnosticTunnel/DiversificationMeasureSteps/index.vue
> +  <v-form @submit.prevent>
Oui, on avait oublié

2023-11-24 14:52 UTC, alemangui commented on frontend/src/views/DiagnosticTunnel/index.vue
> +.summary {
https://github.com/betagouv/ma-cantine/pull/3219/commits/c811402c2dc8fc8e62d4074c1c772479ae472eea

2023-11-24 15:51 UTC, alemangui commented
@hfroot Le merge avec staging était assez mouvementé car les modifs pour centrer le contenu ainsi que le bug #3221 modifiait le CSS dans cette zone. J'ai donc pris en compte tous les trois dans le merge-commit

2023-11-24 16:09 UTC, merged