Appro : gestion d'erreurs saisi détaillé
betagouv/ma-cantine pull request #3266
Opened 2023-12-01 11:08 UTC by hfroot

2023-12-01 11:33 UTC, hfroot commented
Après une démo :
- pour une 2e PR : gerer les erreurs sur étape 1
- souligner tous les champs avec une valeur si il y a une erreur total
- afficher tous les messages d'erreur si il y a plusieurs (max trois : total, viandes, poissons)
- bug étape France erreur contre le total viandes saisi

2023-12-03 21:29 UTC, alemangui requested changes

2023-12-03 21:29 UTC, alemangui commented on frontend/src/views/DiagnosticTunnel/QualityMeasureSteps/FamilyFieldsStep.vue
> +          const message = `Le total de vos achats produits aquatiques ${char.text} (${toCurrency(
P-e : « _Les montants détaillés des produits aquatiques (x €) excédent le total des produits aquatiques saisi dans la troisième étape (y €)_ »

2023-12-04 14:14 UTC, alemangui commented
@hfroot cette PR ferme #[3241](https://github.com/betagouv/ma-cantine/issues/3241) non ? Si c'est le cas on peut l'ajouter dans _Development_

2023-12-05 11:22 UTC, hfroot commented on frontend/src/views/DiagnosticTunnel/QualityMeasureSteps/FamilyFieldsStep.vue
> +      this.lastUpdatedFieldName = fieldName
que pour la nostalgie

2023-12-05 11:47 UTC, hfroot commented on frontend/src/views/DiagnosticTunnel/QualityMeasureSteps/FamilyFieldsStep.vue
> +          const message = `Le total de vos achats viandes et volailles ${char.text} (${toCurrency(
Pas tout à fait d'acc que "Les montants détaillés" et la bonne phrase ici car il y a qu'un champ pris en compte. Je propose 

« Le total des viandes et volailles Provenance France (x €) excédent le total des viandes et volailles saisi dans la troisième étape (y €) »

bien sûr "Provenance France" change selon les trois onglets hors de loi EGAlim : "Provenance France", "local" et "Circuit Court"

2023-12-05 11:49 UTC, hfroot commented on frontend/src/views/DiagnosticTunnel/QualityMeasureSteps/FamilyFieldsStep.vue
> +          const message = `Le total de vos achats produits aquatiques ${char.text} (${toCurrency(
Voir mon réponse sur le prochain commentaire

2023-12-05 11:56 UTC, hfroot commented on frontend/src/views/DiagnosticTunnel/QualityMeasureSteps/FamilyFieldsStep.vue
> +        this.meatTotalErrorMessage = `Le total des achats viandes et volailles (${toCurrency(
Je propose :

![Screenshot 2023-12-05 at 12-55-27 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/d7d32bfc-d92c-40d4-91b8-22f510c97e79)

2023-12-05 11:59 UTC, hfroot commented on frontend/src/views/DiagnosticTunnel/QualityMeasureSteps/FamilyFieldsStep.vue
> +          const message = `Le total de vos achats viandes et volailles ${char.text} (${toCurrency(
![Screenshot 2023-12-05 at 12-59-35 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/6b0ae0c4-6821-4fee-a9a0-7b651942c16c)

2023-12-05 12:02 UTC, hfroot commented on frontend/src/views/DiagnosticTunnel/QualityMeasureSteps/FamilyFieldsStep.vue
> +          const message = `Le total de vos achats viandes et volailles ${char.text} (${toCurrency(
![Screenshot 2023-12-05 at 13-02-25 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/56f08324-168d-4a96-8440-7fefec8a78b1)

2023-12-05 15:59 UTC, alemangui requested changes

2023-12-05 15:59 UTC, alemangui commented on frontend/src/views/DiagnosticTunnel/QualityMeasureSteps/FamilyFieldsStep.vue
> +        return `Le total ${familyText}${characteristicText}(${problemValue}) excédent le total ${familyText}saisi ${stepText}(${totalValue})`
Dans ce cas on parle d'un seul champ non ? (ou d'un seul _total_ ?) dans ce cas on peut conjuguer à la troisième personne
 ```suggestion
        return `Le total ${familyText}${characteristicText}(${problemValue}) excède le total ${familyText}saisi ${stepText}(${totalValue})`
```

2023-12-05 16:03 UTC, alemangui approved these changes

2023-12-06 14:28 UTC, merged