Ajouter le fonctionnalité pour plusieurs gestionnaires par cantine
betagouv/ma-cantine pull request #340
Opened 2021-06-29 14:37 UTC by hfroot

#325 

À faire:

- [ ] Notifications aux utilisateurs
- [ ] Créer un nouveau page authentification sans cantine infos et relier l'utilisateur à la cantine si il y a un object dans `ProvisionalManagers` associé. (NB: même si l'utilisateur utilise le fonctionnalité existant pour inscription, on doit relier le nouveau compte)

2021-07-02 12:03 UTC, alemangui commented on frontend/src/views/CanteenEditor.vue
> +          this.managers.push({ email: this.newManagerEmail })
Une idée à discuter aussi : avoir les gestionnaires et les invités sous deux propriétés différentes. Par ex, cette view "CanteenEditor" peut avoir une _computed property_ managers qui retourne `this.canteen.managers`, ainsi qu'une propriété dans `data` pour `pendingInvitations`.

Ce qu'on gagnerait serait plus de simplicité (car pas besoin du `accountExists`) ainsi qu'une gestion plus naturel car on pourrait séparer les listes de gestionnaires et invités. On pourrait même à terme (pas pour cette PR) ajouter un bouton "_Renvoyer l'email d'invitation_" pour les invités, etc.

----

Option numéro 2 :

Mettre dans l'objet cantine du store les invitations en cours sous une propriété. Ça voudrait dire qu'on enrichit l'objet frontend de la cantine au retour du call  ``/api/v1/provisionalManagers/${canteen.id}`` (fait aujourd'hui dans le _beforeMount_, mais qui passerait sous le store), L'objet finirait par avoir :

```json
{
  "name": "Canteen qqchose",
  ...
  "managers": [{}, {}, ],
  "pendingInvitations": [
    {
      "email": "a@example.com",
      "creationDate": "..." 
    }, 
    {
      ...
    }
  ]
}
```

L'avantage c'est qu'on évite de faire le call API à chaque fois que la view est rendue - on la ferait seulement si la cantine n'a pas déjà l'info. En l'état actuel, à chaque fois que j'ouvrirai le _CantineEditor_ le call API sera fait (même si les infos ont déjà été obtenus).

----

Option numéro 3 :

Ajouter les _pending invitations_ dès la sérialisation de l'objet `Canteen` dans le backend, un peu comme on fait avec les managers. Avantage : pas besoin de faire le call additionnel lors de l'ouverture de cette view. Inconvénient : une jointure en plus lors du get _user canteens_.

2021-07-02 12:03 UTC, alemangui commented on frontend/src/store/index.js
> +
Je ferme cette conversation car ça touche mon commentaire ci-dessous (https://github.com/betagouv/ma-cantine/pull/340#discussion_r662961405)

2021-07-04 15:13 UTC, hfroot commented on api/views.py
> -        new_publication_status = serializer.validated_data.get('data_is_public', False)
Oui je pensais ça aussi... est-ce qu'on a des configurations differentes ? On peut voir ensemble mardi

2021-07-04 15:17 UTC, hfroot commented on data/models/provisionalmanager.py
> +
Je comprends pourquoi `provisional` est un peu confusant. Je pense aussi que le concept du "Manager" est important dans le nom parce-que il y a d'autre fonctionnalité qui relie les gestionnaires des cantines directement avec les objets dans ce tableur. Alors qu'est-ce que tu penses du `InvitedManager` ?

2021-07-04 15:20 UTC, hfroot commented on data/models/provisionalmanager.py
> +        return f"{self.email}"
Haha merci mais je peux pas m'attribuer le mérite de ça - j'ai suit ton exemple dans `/models/canteen.py`

2021-07-06 13:14 UTC, alemangui requested changes

2021-07-06 13:14 UTC, alemangui commented on frontend/src/views/CanteenEditor/index.vue
>      <DiagnosticList :canteen="canteen" v-if="canteen && originalCanteen && !isNewCanteen" />
J'ai un rendu bizarre sur mobile dans lequel les dates de création des diagnostics sautent jusqu'à la section de gestionnaires :thinking: 

![image](https://user-images.githubusercontent.com/1225929/124605407-272c9700-de6c-11eb-8c32-2ad49e003de1.png)

2021-07-06 13:22 UTC, alemangui commented on frontend/src/views/CanteenEditor/index.vue
> +          <ManagerItem
Il y a un petit bug UI lorsqu'on ajoute deux fois le même email (d'un utilisateur non-existant) : la liste devient vide. Je n'ai pas encore creusé d'où ça vient

2021-07-06 13:29 UTC, alemangui commented on api/views.py
> +            return JsonResponse(CanteenManagerSerializer(canteen).data, status=status.HTTP_200_OK)
Vu qu'on fait le rendu de la réponse nous mêmes, on aura du _snake_case_. Pour l'éviter voici ce qu'on peut faire : 

1. importer le CamelCase renderer en haut du fichier

```python
from djangorestframework_camel_case.render import CamelCaseJSONRenderer
``` 

2. Utiliser le CamelCase renderer pour faire le rendu des données du serializer : 

```python
data = CanteenManagerSerializer(canteen).data
return JsonResponse(CamelCaseJSONRenderer().render(data), status=status.HTTP_200_OK)
```

2021-07-06 13:54 UTC, hfroot commented on api/tests/test_signals.py
> +        self.assertEqual(len(ManagerInvitation.objects.all()), 0)
Je suis un peu étonnée que le `pre-commit` n'a pas trouvé ça

2021-07-06 14:24 UTC, alemangui commented on web/templates/auth/manager-invitation.html
> +<p>
J'ai ajouté un petit paragraphe de description car cet email sera envoyé à des gens qui n'ont pas de compte, et donc qui ne connaissent pas forcément _ma cantine_. D'autres modifications mineures du texte d'email ont aussi été commitées dans https://github.com/betagouv/ma-cantine/pull/340/commits/3d45611fc685a754fd14c93d236e4f5326263db6

2021-07-06 14:29 UTC, alemangui commented on data/models/managerinvitation.py
> +        verbose_name = "nouveau gestionnaire"
Top merci. Vu que la migration existante a été modifiée il faudra rollbacker et la refaire pour que ça prenne effet. 

Vu que le changement est petit il n'y a pas de souci, mais pour des changements plus importants il n'y a pas de souci pour ajouter des migrations de plus si besoin.

2021-07-06 16:35 UTC, alemangui approved these changes
:clap:  Super PR

2021-07-07 08:26 UTC, merged