Ajouter deux nouvelles valeurs mesures gaspi
betagouv/ma-cantine pull request #3417
Opened 2024-01-09 18:07 UTC by hfroot

QUESTION : in the waste summary, if the value entered is 0, today we just show the same as not filled in, `-`. Should we show `0 kg/an` instead?

![Screenshot 2024-01-09 at 19-02-57 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/ad83e29d-6872-4efa-abbc-e6c1473d7afe)
![Screenshot 2024-01-09 at 18-59-32 teledeclaration-2023--cantine-du-tunnel--2024-01-09 pdf](https://github.com/betagouv/ma-cantine/assets/9282816/b0a5a614-19df-4253-b9a2-11282a402be4)
[teledeclaration-2023--cantine-du-tunnel--2024-01-09.pdf](https://github.com/betagouv/ma-cantine/files/13877482/teledeclaration-2023--cantine-du-tunnel--2024-01-09.pdf)
![Screenshot 2024-01-09 at 18-58-40 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/7ea772f6-9f18-4666-ada2-f821a898cd8e)

2024-01-09 18:08 UTC, hfroot commented
@qloridant ça va introduire deux nouveaux champs, alors p-e impact tes analyses

2024-01-11 13:57 UTC, alemangui commented
> QUESTION : in the waste summary, if the value entered is 0, today we just show the same as not filled in, -. Should we show 0 kg/an instead?
Pour moi oui, il faudra montrer zéro et non pas `-`

2024-01-11 14:01 UTC, alemangui requested changes

2024-01-11 14:01 UTC, alemangui commented
> En attente de confirmation si on a besoin de garder le diagnostic non-connecté à jour aussi.

Pas sur de comprendre, c'est quoi un diagnostic non-connecté ?

2024-01-11 19:41 UTC, hfroot commented
https://github.com/betagouv/ma-cantine/pull/3417/commits/cdb1679774c7dab3355fca89f1caff773fa63595 et https://github.com/betagouv/ma-cantine/pull/3417/commits/a596aa44698e5b042363b006f1c8af29095af514
![Screenshot 2024-01-11 at 20-39-53 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/c7daed99-3ba7-4882-8f75-d322b8697970)

2024-01-11 19:41 UTC, hfroot commented
> Pas sur de comprendre, c'est quoi un diagnostic non-connecté ?

https://ma-cantine.agriculture.gouv.fr/diagnostic @alemangui 

Thomas a dit qu'il y a pas besoin

2024-01-15 10:47 UTC, alemangui approved these changes

2024-01-18 09:49 UTC, merged