Le champ total déchets prend la valeur en kilogram, pas en ton
betagouv/ma-cantine pull request #3494
Opened 2024-01-29 17:51 UTC by hfroot

2024-01-30 10:32 UTC, alemangui requested changes

2024-01-30 10:32 UTC, alemangui commented on api/serializers/diagnostic.py
> +                            "Vous avez découvert une erreur inconnue. Assurez-vous que cette valeur est un chiffre décimal, et contactez-nous si l'erreur persiste."
```suggestion
                            "Une erreur est survenue. Assurez-vous que cette valeur est un chiffre décimal, et contactez-nous si l'erreur persiste."
```

2024-01-30 10:32 UTC, alemangui approved these changes

2024-01-30 10:46 UTC, merged

2024-02-06 09:31 UTC, Tdauvet89 commented
Ok sur staging, go pour pour prod ✅