3456 le compte des cantines filtrées par epci dans la page ma collectivité est faux
betagouv/ma-cantine pull request #3506
Opened 2024-02-02 10:29 UTC by qloridant

2024-02-02 14:45 UTC, alemangui requested changes

2024-02-02 14:45 UTC, alemangui commented on api/views/canteen.py
>              logger.warning(f"Error when fetching postcodes for EPCI for canteen stats: {str(e)}")
```suggestion
            logger.warning(f"Error when fetching INSEE codes for EPCI for canteen stats: {str(e)}")
```

2024-02-02 14:45 UTC, alemangui commented on data/factories/canteen.py
>      city = factory.Faker("city")
On peut laisser les deux dans le factory ? Code postale et INSEE

2024-02-05 11:41 UTC, hfroot commented
J'ai créé un issu relié : https://github.com/betagouv/ma-cantine/issues/3520

2024-02-05 13:41 UTC, alemangui approved these changes

2024-02-05 13:41 UTC, merged