Ajouter des messages d'avertissement pour les dévs qui utilisent notre API pour rappeler d'utiliser démo pour des tests
betagouv/ma-cantine pull request #3529
Opened 2024-02-06 12:10 UTC by hfroot

Pour les templates django je voulais pas mettre le message dans `base.html` car on a un view pour les utilisateurs là - `authorize.html`. Est-ce que tu penses qu'on doit le mettre quand même dans d'autres templates ?

![Screenshot 2024-02-06 at 12-54-52 Screenshot](https://github.com/betagouv/ma-cantine/assets/9282816/751dc2bc-040b-4d75-bbf5-521b3bd6abee)
![Screenshot 2024-02-06 at 12-55-15 Screenshot](https://github.com/betagouv/ma-cantine/assets/9282816/8c00d00a-3f5d-432c-a9e9-5e77adb2d587)

![Screenshot 2024-02-06 at 13-09-24 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/7b5a33da-9470-4c9f-a1e3-79c42d76c453)
![Screenshot 2024-02-06 at 13-09-58 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/3503c69e-ac96-4fa5-a9f5-f0be3a0dce62)

2024-02-07 10:09 UTC, qloridant commented on templates/oauth2_provider/prod_warning.html
> +        pour ne pas embrouiller notre base de données.
Je pinaille sur le français :
"pour ne pas compromettre la qualité des données en production."

2024-02-08 09:03 UTC, hfroot commented on templates/oauth2_provider/prod_warning.html
> +        pour ne pas embrouiller notre base de données.
J'accepte toujours les retours sur le français que j'écris, merci !

2024-02-08 09:53 UTC, alemangui requested changes

2024-02-08 09:53 UTC, alemangui commented on frontend/src/views/DeveloperPage.vue
> +        Vous êtes dans l'environnement de
```suggestion
        Vous êtes dans l'environnement
```

2024-02-08 09:53 UTC, alemangui commented on frontend/src/views/DeveloperPage.vue
> +        Vous êtes dans l'environnement de
```suggestion
        Vous êtes dans l'environnement
```

2024-02-08 09:53 UTC, alemangui commented on frontend/src/views/DeveloperPage.vue
> +        . Ici vous pouvez envoyer des données fausses pour les tests.
```suggestion
        . Cet environnement est un bac à sable dédié pour les tests.
```

2024-02-08 09:53 UTC, alemangui commented on templates/oauth2_provider/prod_warning.html
> +    <p>Vous êtes dans l'environnement de <b>production</b> de <i>ma cantine</i>.</p>
```suggestion
    <p>Vous êtes dans l'environnement <b>production</b> de <i>ma cantine</i>.</p>
```

2024-02-08 09:53 UTC, alemangui commented on templates/oauth2_provider/prod_warning.html
> +    <p>Vous êtes dans l'environnement de <b>démo</b> de <i>ma cantine</i>.</p>
```suggestion
    <p>Vous êtes dans l'environnement <b>démo</b> de <i>ma cantine</i>.</p>
```

2024-02-08 09:53 UTC, alemangui commented on templates/oauth2_provider/prod_warning.html
> +        Si vous êtes en train de tester votre intégration, veuillez utiliser
Je mettrais :
> Pour effectuer des tests, veuillez utiliser notre environnement démo : un bac a sable permettant de manipuler des données sans risque.

2024-02-09 09:19 UTC, alemangui approved these changes

2024-02-09 09:20 UTC, merged