Supprimer les messages de warning avec les tests open data
betagouv/ma-cantine pull request #3596
Opened 2024-02-20 15:22 UTC by hfroot

Messages genre
`RuntimeWarning: DateTimeField Teledeclaration.creation_date received a naive datetime (2023-06-30 00:00:00) while time zone support is active.`

@qloridant est-ce que tu pourrais vérifier que ça casse rien ?

D'ailleurs, qu'est-ce que tu penses de déplacer `test_extraction_open_data` dans `macantine/tests` plutôt que `/data/tests` qui est censé de tester les modèles dans la BDD ?

2024-02-22 09:52 UTC, alemangui approved these changes

2024-02-22 09:55 UTC, alemangui commented
@hfroot @qloridant Pas sur du déplacement des tests... d'une certaine façon ça a du sens que l'extraction des données soit dans l'_app_ « data », c'est qqchose lié directement aux données. De plus c'est là qu'on a les schemas. Éventuellement je dirais plutôt de déplacer `extract_open_data` dans l'app « data »  :thinking: 

Sur `ma-cantine/tests` je vois plus de choses d'intégration générale.

2024-02-22 09:55 UTC, alemangui approved these changes

2024-02-22 15:55 UTC, alemangui requested changes

2024-02-22 15:55 UTC, alemangui commented on macantine/extract_open_data.py
> +    2021: {
Petite remarque : j'utiliserais `tzinfo=pytz.timezone("Europe/Paris")` pour les dates de la campagne

2024-02-23 14:13 UTC, hfroot commented on macantine/extract_open_data.py
> +    2021: {
@alemangui merci - j'ai MAJ d'autres instances de UTC. Même si c'est que dans des tests je voulais rendre le code coherent

2024-02-23 14:22 UTC, alemangui approved these changes

2024-02-23 14:25 UTC, merged