Bug fix, cas rare : ne pas montrer le CTA données appro si le bilan est TDé
betagouv/ma-cantine pull request #3623
Opened 2024-02-26 09:23 UTC by hfroot

Closes #3432

Vu qu'on devrait ne pas arriver dans ce cas, j'ai choisit de faire quelque chose très petit

2024-02-26 16:56 UTC, alemangui requested changes

2024-02-26 16:56 UTC, alemangui commented on frontend/src/components/DiagnosticSummary/QualityMeasureSummary.vue
> +      v-if="showEditButton && !hasActiveTeledeclaration"
Je te propose qu'on le fasse au niveau de l'appelant car ça pourrait être bizarre de passer un paramètre `showEditButton` qui ne garanti pas que le bouton sera affiché.

Sauf erreur de ma part, le changement est aussi minuscule car on a déjà la fonction `hasActiveTeledeclaration` dans le seul appelant qui utilise ce paramètre, ce serait seulement au niveau du `ProgressTab.vue` en changeant ça :
```javascript
<component
     ...
     :showEditButton="true"
/>
```
en 
```javascript
<component
     ...
     :showEditButton="hasActiveTeledeclaration"
/>
```

2024-02-27 13:25 UTC, hfroot commented on frontend/src/components/DiagnosticSummary/QualityMeasureSummary.vue
> +      v-if="showEditButton && !hasActiveTeledeclaration"
Bien vu

2024-02-27 14:58 UTC, alemangui approved these changes

2024-02-27 14:59 UTC, merged