Après avoir révendiquer une cantine sur la page SIRET, rediriger l'utilisateur vers la page modification de la cantine
betagouv/ma-cantine pull request #3633
Opened 2024-02-26 11:29 UTC by hfroot

![Screenshot 2024-02-26 at 12-29-07 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/b35cad4e-97d1-4305-8c3b-f433aeac7bc9)
![Screenshot 2024-02-26 at 12-29-23 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/bf9fac52-027a-459c-82d8-20313d376321)

2024-02-26 11:32 UTC, hfroot commented on frontend/src/views/DashboardManager/index.vue
> +          this.$router.replace({ name: "ManagementPage" })
Rien à voir mais dans le cas où t'es sur une cantine que tu gère pas, je pense que c'est mieux de rediriger vers la page de gestion de tous les établissements ?

2024-02-29 11:10 UTC, alemangui commented on frontend/src/views/DashboardManager/index.vue
> +          this.$router.replace({ name: "ManagementPage" })
Merci pour le comment et pour le fix ;)  #3634

2024-02-29 11:15 UTC, alemangui requested changes

2024-02-29 11:15 UTC, alemangui commented on frontend/src/views/CanteenEditor/SiretCheck.vue
> +            message: "Vous gérez maintenant cette cantine.",
```suggestion
            message: "Vous gérez maintenant cet établissement.",
```
Pinaillage... mais dans le cas d'une CC potentiellement ça sera plus clair ?

2024-02-29 14:19 UTC, hfroot commented on api/tests/test_published_canteens.py
> +        canteen = CanteenFactory.create(publication_status=Canteen.PublicationStatus.DRAFT)
Avant, on a permit que les cantines publiées d'être revendiquées. Aujourd'hui, c'est pas le cas, mais les tests ne réflectent ça explicitement (surtout pcq on a dans un fichier `test_published_canteens`). En vrai, je pense que ces tests devraient être déplacés mais je voulais voir avec toi avant, ou le faire dans un deuxième temps pour rendre le CR plus facile.

2024-03-04 08:48 UTC, alemangui approved these changes

2024-03-04 08:48 UTC, merged