RGAA 1.1 Chaque image porteuse d’information a-t-elle une alternative textuelle ?
betagouv/ma-cantine pull request #3661
Opened 2024-03-04 12:18 UTC by hfroot

J'ignore les chartes (aujourd'hui qui ont un role="img" qui va p-e changer avec le travail sur les graphiques (e.g. 10.8, 10.13?)

2024-03-05 10:42 UTC, hfroot commented
J'ai mis une question dans mattermost pour comprendre les bonnes pratiques pour rendre les images fournis par nos utilisateurs accessibles

2024-03-05 12:11 UTC, hfroot commented
Comme pour les logos cantine - je pense que l'image pour un acteur de l'éco-système est décoratif.

2024-03-05 12:16 UTC, hfroot commented
En plus je me suis dit que l'utilisation de la première image pour le widget "Mon établissement" et la carte d'une cantine publiée est purement décorative, même si la même image contient un text alt quand elle est affichée dans la galerie sur la page publique

2024-03-06 10:42 UTC, alemangui requested changes

2024-03-06 10:42 UTC, alemangui commented on data/models/canteen.py
> +        verbose_name="texte alternatif pour les utilisateurs qui voient pas l'image",
On pourrait utiliser "Texte descriptif pour malvoyants ou non-voyants", comme ça l'intention est plus clair

2024-03-06 10:42 UTC, alemangui commented on frontend/src/components/KeyMeasureDescriptionLabels.vue
> +        <img :src="`/static/images/quality-labels/${label.src}`" alt="" />
Est-ce nécessaire de le mettre à `""` ? Ou l'omettre complètement serait mieux ? (même question pour `WidgetHeader.vue`)

2024-03-06 10:42 UTC, alemangui commented on frontend/src/views/CanteenEditor/ImagesField.vue
> +          hint="Si l'image contient d'information pertinante, pensez à ajouter une description pour les personnes malvoyantes"
```suggestion
          hint="Si l'image contient de l'information pertinente, pensez à ajouter une description pour les personnes malvoyantes"
```

2024-03-06 11:10 UTC, hfroot commented on frontend/src/components/KeyMeasureDescriptionLabels.vue
> +        <img :src="`/static/images/quality-labels/${label.src}`" alt="" />
quand on utilise `img` faut avoir un `alt=""` pour indiquer que l'image est décoratif : https://www.w3.org/WAI/tutorials/images/decorative/
c'est pas le même comme `v-img` qui crée un `div` avec un `background-image` dans le DOM.

2024-03-06 11:15 UTC, hfroot commented on data/models/canteen.py
> +        verbose_name="texte alternatif pour les utilisateurs qui voient pas l'image",
j'ai utilisé cette phrase parce que le texte alternatif est aussi affiché dans d'autres cas (par ex l'image ne télécharge pas pour une raison ou l'autre). Après si ce niveau de détail est pas nécessaire pour notre équipe (je pensais que c'est le cas pour les gestionnaires qui uploadent l'image) on pourrait faire `texte descriptif pour les personnes malvoyantes` ?

2024-03-07 09:20 UTC, alemangui approved these changes

2024-03-07 09:21 UTC, merged