RGAA 1.1 s'assurer que les icônes pertinates ont de texte alternatif
betagouv/ma-cantine pull request #3679
Opened 2024-03-07 14:05 UTC by hfroot

Souvent les icônes sont à côté du texte alors pas besoin dans ces cas.

2024-03-14 11:12 UTC, alemangui requested changes

2024-03-14 11:12 UTC, alemangui commented on frontend/src/views/AccessibilityDeclaration.vue
> +        title="GitHub issus - ouvre une nouvelle fenêtre"
`issu` veut plutôt dire venant de quelque part
```suggestion
        title="GitHub issues - ouvre une nouvelle fenêtre"
```

2024-03-14 11:12 UTC, alemangui commented on frontend/src/components/AppFooter.vue
Pas obligatoire, mais est-ce que si on utilise `dans` ce serait plus clair ? D'ailleurs j'imagine que ça sera presque toujours dans un nouvel onglet plutôt que fenêtre ?
> ouvre dans un nouvel onglet

> ouvre dans une nouvelle fenêtre

> ouvre dans une nouvelle fenêtre ou un nouvel onglet

2024-03-14 11:12 UTC, alemangui commented on frontend/src/views/DashboardManager/TeamWidget.vue
> +              <span class="d-sr-only">{{ manager.isInvite ? "(Compte pas encore créé)" : "(Compte créé)" }}</span>
```suggestion
              <span class="d-sr-only">{{ manager.isInvite ? "(création de compte en attente)" : "(compte créée)" }}</span>
```

2024-03-14 11:12 UTC, alemangui commented on frontend/src/views/ManagementPage/UserTools.vue
> +              title="Decouvrir nos ressources - ouvre une nouvelle fenêtre"
Petite coquille (en bas aussi)... _d**é**couvrir_

```suggestion
              title="Découvrir nos ressources - ouvre une nouvelle fenêtre"
```

2024-03-18 09:29 UTC, hfroot commented on frontend/src/components/AppFooter.vue
@alemangui j'ai pris le texte du DSFR : https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/lien je suis plutôt d'acc mais en même temps je suis pour suivre le DSFR

2024-03-19 07:07 UTC, alemangui approved these changes

2024-03-19 07:08 UTC, merged