[DRAFT] Améliorer a11y et design de la barre de navigation
betagouv/ma-cantine pull request #3735
Opened 2024-03-20 22:22 UTC by hfroot

2024-03-22 20:12 UTC, hfroot commented
L'audit n'a pas listé tous les pbs avec la navigation, alors je voudrais faire un rdv avec pole numerique inclusif quand c'est en staging pour voir quels sont les pbs restants

2024-04-02 13:02 UTC, alemangui requested changes

2024-04-02 13:02 UTC, alemangui commented on frontend/src/components/AppHeader/index.vue
Pas sur pourquoi mais le menu devient inaccessible dans des écrans mobiles (pas de bouton d'accès en haut à droite) : 
![image](https://github.com/betagouv/ma-cantine/assets/1225929/cbee2d5a-0034-4408-81ca-9ea7e1a4748f)

Par comparaison, côté staging :
![image](https://github.com/betagouv/ma-cantine/assets/1225929/5275438d-7aba-4ecb-a86e-27baf5d86f5d)

ou bien : 
![image](https://github.com/betagouv/ma-cantine/assets/1225929/5c4eee90-8c0f-4adc-b24e-6d16afe76d42)

2024-04-02 13:03 UTC, alemangui commented
Au passage, j'imagine que ce n'est pas très grave mais l'outline bleu pour les boutons manque la bordure droite, j'imagine car l'élément d'après est dessus (c'est quand même mieux qu'en staging par contre)
[Screencast from 02-04-24 14:59:19.webm](https://github.com/betagouv/ma-cantine/assets/1225929/efaf79ba-e1d3-4765-b18a-a5cb3ac58fe3)

2024-04-04 12:48 UTC, hfroot commented on frontend/src/components/AppHeader/index.vue
@alemangui je vois ça quand j'active le mode dév sur firefox, mais si je refraichit une fois dans ce mode, je vois encore l'icone. Je pensais alors que c'est pas grâve, mais je sais pas le comportement en live (par exemple si on utilise un tablet et on passe le seuil de sm/md quand on change vertical/horizontal. Tu penses quoi ?

2024-04-04 12:50 UTC, hfroot commented on frontend/src/components/AppHeader/index.vue
Je demande si il y a qqn sur notre équipe avec un tablet pour tester

2024-04-04 12:54 UTC, hfroot commented on frontend/src/components/AppHeader/index.vue
En fait j'ai déplacer le v-if et ça marche maintenant (je teste en mode ipad pour voir le change entre md et sm)

2024-04-04 12:57 UTC, hfroot commented
> Au passage, j'imagine que ce n'est pas très grave mais l'outline bleu pour les boutons manque la bordure droite, j'imagine car l'élément d'après est dessus (c'est quand même mieux qu'en staging par contre) [Screencast from 02-04-24 14:59:19.webm](https://github.com/betagouv/ma-cantine/assets/1225929/efaf79ba-e1d3-4765-b18a-a5cb3ac58fe3)

J'ai créé un nouveau issue vu qu'un pb similaire existe déjà sur staging, et car c'est pas urgent

2024-04-04 14:58 UTC, alemangui approved these changes

2024-04-05 13:55 UTC, merged