Toutes les cantines qui manquent si un code INSEE si un code postal devront être des candidats pour le geobot
betagouv/ma-cantine pull request #3773
Opened 2024-04-01 18:27 UTC by hfroot

2024-04-02 08:07 UTC, qloridant requested changes

2024-04-02 08:07 UTC, qloridant commented on macantine/tests/test_geolocation_bot.py
>              CanteenFactory.create(city=None, geolocation_bot_attempts=0, postal_code="69003"),
Cette cantine ne devrait plus ressortir comme candidate normalement

2024-04-05 14:08 UTC, hfroot commented on macantine/tests/test_geolocation_bot.py
>              CanteenFactory.create(city=None, geolocation_bot_attempts=0, postal_code="69003"),
@qloridant pourquoi ?

2024-04-05 19:46 UTC, hfroot commented on macantine/tests/test_geolocation_bot.py
>              CanteenFactory.create(city=None, geolocation_bot_attempts=0, postal_code="69003"),
Je crois qu'on a decidé de faire `Canteen.objects.filter(Q(city=None) | Q(department=None))` car on utilise `city` pour afficher la localisation en plusieurs endroits de notre site (e.g. page vitrine). Alors si on a un code INSEE mais pas le `city` on veut bien le recuperer.
Par contre, je remarque qu'on ne filtre pas pour les cantines sans code INSEE qui est maintenant important pour les filtres EPCI et l'open data. Alors j'ajoute un commit pour elargir encore plus le scope

2024-04-05 19:50 UTC, hfroot commented on macantine/tests/test_geolocation_bot.py
>              CanteenFactory.create(city=None, geolocation_bot_attempts=0, postal_code="69003"),
Est-ce qu'on veut aussi retrouver les cantines qui n'ont pas un code postal, même si il y a les autres données ?

2024-04-05 20:22 UTC, hfroot commented on macantine/tests/test_geolocation_bot.py
>              CanteenFactory.create(city=None, geolocation_bot_attempts=0, postal_code="69003"),
Je trouve les noms des méthodes difficile à suivre maintenant, alors je les ai renommé : https://github.com/betagouv/ma-cantine/pull/3773/commits/b9c249958c79f408f82e14fe5ad3e17d615e7f23

2024-04-22 14:32 UTC, qloridant approved these changes

2024-04-22 14:32 UTC, merged