Affiche : afficher l'aperçu dans le formulaire de publication et rendre la description modifiable en place
betagouv/ma-cantine pull request #3820
Opened 2024-04-19 21:18 UTC by hfroot

Il y a surement des conflits avec l'autre PR mais je vais les resoudre après le merge de l'une ou l'autre

![Screenshot 2024-04-19 at 23-16-41 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/20facffd-e8ef-4ed1-b2a4-6d9213234d30)

2024-04-23 13:59 UTC, alemangui requested changes

2024-04-23 13:59 UTC, alemangui commented on frontend/src/components/CanteenPublication.vue
> +              Si vous le souhaitez, personnalisez votre affiche en écrivant quelques mots sur votre établissement : son
On a le break du `:` en pleine ligne
![image](https://github.com/betagouv/ma-cantine/assets/1225929/258cd2e7-74c7-436c-82b5-f65eddf5b2b0)
```suggestion
              Si vous le souhaitez, personnalisez votre affiche en écrivant quelques mots sur votre établissement&nbsp;: son
```

2024-04-23 13:59 UTC, alemangui commented on frontend/src/components/CanteenPublication.vue
Le champ devient non-editable après le premier caractère
[Screencast from 23-04-24 15:53:19.webm](https://github.com/betagouv/ma-cantine/assets/1225929/2b49f941-ecac-4c89-a8c5-a6a860abb911)

2024-04-30 08:37 UTC, hfroot commented
Todo

- [ ] bug fix description editing
- [ ] instead of synthèse, show a sentence when unfolding the accordion
- [ ] appro accordion to be unfolded by default (if there is data?)

2024-04-30 09:16 UTC, alemangui approved these changes

2024-04-30 09:52 UTC, merged

2024-05-06 10:22 UTC, Tdauvet89 commented
Ok sur staging @hfroot , go pour prod