Améliorer le structure des pages
betagouv/ma-cantine pull request #386
Opened 2021-07-22 17:20 UTC by hfroot

2021-07-27 14:56 UTC, alemangui requested changes

2021-07-27 14:59 UTC, alemangui commented
La taille des titres dans les mesures phares a changé, mais je trouve que c'est une bonne chose :+1: Si tu es d'accord gardons les titres plus petits (ce qui est déjà fait dans cette branche)

Avant :
![image](https://user-images.githubusercontent.com/1225929/127177148-5bdeb021-2617-4627-83e3-4388c39722e3.png)

Après :
![image](https://user-images.githubusercontent.com/1225929/127177213-cc2c5712-8a25-48ec-b06c-6bbae9700ccd.png)

2021-07-27 16:15 UTC, hfroot commented
> La taille des titres dans les mesures phares a changé, mais je trouve que c'est une bonne chose 👍 Si tu es d'accord gardons les titres plus petits (ce qui est déjà fait dans cette branche)

Ah oui, c'était un peu difficile a tester et j'ai pensé que la taille plus petite était la taille existante, mais bof, j'aime la deuxième option aussi.

2021-07-29 13:38 UTC, alemangui approved these changes

2021-07-29 13:38 UTC, merged