[DRAFT] Améliorer l'accessibilité du composant Select
betagouv/ma-cantine pull request #3864
Opened 2024-05-02 16:37 UTC by hfroot

relié #3849

2024-05-03 12:44 UTC, alemangui requested changes

2024-05-03 12:44 UTC, alemangui commented on frontend/src/views/PurchasesSummary.vue
> +        .map((year) => ({ text: year, value: year })),
Est-ce que le map est nécessaire si le `text` et le `value` sont identiques ?

2024-05-06 08:53 UTC, hfroot commented on frontend/src/views/AccountSummaryPage/AccountEditor.vue
> -              placeholder="Choisir une fonction"
Oui, en générale les [placeholders sont deconseillés niveau accessibilité](https://www.smashingmagazine.com/2018/06/placeholder-attribute/). Pour les listes déroulantes, le DSFR propose un "placeholder" specifique de ["Sélectionner une option"](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/liste-deroulante)

2024-05-06 08:54 UTC, hfroot commented on frontend/src/views/PurchasesSummary.vue
> +        .map((year) => ({ text: year, value: year })),
Avec vuetify non. Je pourrais reproduire la fonctionnalité de vuetify dans le nouveau composant

2024-05-06 09:05 UTC, hfroot commented on frontend/src/components/DsfrNativeSelect.vue
> +      <option v-if="!items.length" disabled selected value="">{{ noDataText || "Pas d'options" }}</option>
AMA le mieux sera de le remplacer dans chaque utilisation qui pourrait remonter ce message, alors je vois ça que comme fallback

2024-05-23 09:43 UTC, alemangui commented on frontend/src/views/PurchasesSummary.vue
> +        .map((year) => ({ text: year, value: year })),
Nah ce n'est pas nécessaire je pense,

2024-06-02 16:59 UTC, hfroot commented on frontend/src/views/CanteenEditor/CanteenForm.vue
> -            <DsfrSelect
Bien vu, c'est reglé

2024-06-03 12:27 UTC, alemangui approved these changes

2024-06-03 12:27 UTC, merged