[DRAFT] Affiche, appro : option pour dépublier diagnostics non-TDés
betagouv/ma-cantine pull request #3913
Opened 2024-05-13 12:41 UTC by hfroot

closes #3888

2024-05-20 15:07 UTC, alemangui requested changes

2024-05-20 15:07 UTC, alemangui commented on frontend/src/components/CanteenPublication/ResultsComponents/QualityMeasureResults.vue
>      graphDiagnostics() {
Une question sur cette propriété :

- Aujourd'hui on a bien les `approDiagnostics`, donc ceux qu'on veut montrer dans le tab « Comparer »
- Par contre, dans le composant `MultiYearSummaryStatistics` on fait un check additionnel sur ces bilans qui s'appelle "hasDiagnosticApproData"

Donc on a des cas comme celui-ci, où l'on a quatre diagnostics appro dans `canteen.approDiagnostics`, mais on ne montre que deux dans le tab « Comparer » :

![image](https://github.com/betagouv/ma-cantine/assets/1225929/4d24cd0e-29d1-4f66-9816-adbb2f89d4a0)

Est-ce que c'est voulu ? Ou bien le check `hasDiagnosticApproData` n'a plus du sens dans le composant `MultiYearSummaryStatistics` ?

2024-05-20 15:26 UTC, hfroot commented on frontend/src/components/CanteenPublication/ResultsComponents/QualityMeasureResults.vue
> +      if (!this.canteen.approDiagnostics || this.canteen.approDiagnostics.length === 0) return null
à faire en deuxième temps ? Ce comportement existe déjà pour les cantines sans diagnostics sur staging - lié au #3892

2024-05-20 15:31 UTC, hfroot commented on api/serializers/canteen.py
Oui c'est moche - je pense que c'est parce qu'on query diagnostics bcp plus maintenant, et les properties ne cache pas les resultats entre eux. Je veux bien le régler en deuxième temps si c'est ok - https://github.com/betagouv/ma-cantine/issues/3937

2024-05-20 15:33 UTC, hfroot commented on data/models/canteen.py
> +
En vrai, entre ce commentaire et le commentaire perf, peut-être c'est mieux de faire comme tu proposes en premier temps, vu que le cas où les deux sont en décalage est rare.

2024-05-20 15:49 UTC, alemangui commented on data/models/canteen.py
> +
Moi ça me va de rester comme tu l'as fait, je voulais juste comprendre si c'était voulu ou non

2024-05-21 09:23 UTC, hfroot commented
en deuxieme temps : p-e au lieu de `queryset.exclude(redacted_appro_years__contains=[publication_year])` le `exclude` pourrait être effectué sur `qs_diag` comme `.exclude(canteen__redacted_appro_years__contains...` pour éviter avoir les diagnostics inutils dès le debut. Mais aussi ce query est un peu moche car les cartes pourrait montrer le badge dès une année n-2 etc mais cette logique vérifie que n-1... bof c'est un pb pour une autre PR vu que ce comportement existe déjà

2024-05-21 10:03 UTC, alemangui approved these changes

2024-05-21 10:48 UTC, merged