Import des diagnostics avec fichier CSV
betagouv/ma-cantine pull request #392
Opened 2021-07-23 15:57 UTC by hfroot

2021-07-26 16:16 UTC, hfroot commented
Il y a un commentaire qui est assez important en générale, mais aussi peut-être pas nécessaire pour un démo, alors on peut commencer avec le revue, si tu est d'acc :
`# TODO: test that can't create diagnostics for existing canteen if you aren't a manager of it`

2021-07-27 09:37 UTC, alemangui commented on api/views.py
> +
J'imagine qu'ici on pourrait faire le check pour vérifier que l'utilisateur a bien le droit de modifier la cantine car l'objet cantine est déjà rempli... qqchose du style (en pseudo-code) :

```
if self.request.user not in canteen.managers.all():
    raise AuthError("Vous n'êtes pas gestionnaire de la cantine ... ") # Pas sur quel type d'erreur
```

2021-07-27 09:38 UTC, alemangui commented on data/models/canteen.py
> +    # TODO: index by siret if it exists?
Would be good once we know the SIRET format we will use (and we have them all normalized)

2021-07-27 09:40 UTC, alemangui commented on frontend/src/store/index.js
> +      state.userCanteens.prepend(userCanteen)
À terme on pourra indiquer un ordre dans la view (par ex. par date de création). Pas nécessaire pour cette PR.

2021-07-27 15:06 UTC, alemangui requested changes

2021-07-27 15:06 UTC, alemangui commented on api/views.py
> +                            errors.append(
Ça marche bien. Par curiosité, pourquoi ne pas lancer une exception ? Disons qu'au lieu de faire un `errors.append` et `continue` directement ici, on pourrait lancer une exception avec le message :

```python
raise Exception(f"Vous n'êtes pas un gestionnaire de la cantine avec SIRET {siret}")
```
Qui serait traité en ligne 505, ici :

```python
except Exception as e:
    errors.append({"row": row_number, "status": 400, "message": str(e)})
```

Ce serait pareil non ?

2021-07-27 15:20 UTC, alemangui commented
Lorsqu'un fichier non encodé en utf-8 est sélectionné on a un 500, par exemple :

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 17
```

Vu que souvent on aura des utilisateurs de Windows avec des logiciels pas ça vaudrait peut-être la peine de retourner une erreur décrivant le problème dans un premier temps, cela peut se faire avec un petit try/catch.

Probablement à terme on pourrait supporter plusieurs encodages avec libmagic ou un truc comme ça.

2021-07-27 15:31 UTC, alemangui commented
Un autre détail, à voir si on le fait maintenant ou dans un second temps : la gestion de messages d'erreur.

Aujourd'hui nous mettons directement l'erreur dans l'objet de réponse. Il y a un risque sécurité et potentiellement une incompréhension de l'utilisateur, par ex :

![image](https://user-images.githubusercontent.com/1225929/127182541-a47e2ebf-a7ff-4e79-afce-bf11b4d0dd93.png)

Si on retourne des messages plus claires (par ex "_Un diagnostic pour cette cantine et cette année existe déjà_" il faudra quand même qu'on puisse savoir ce qui s'est vraiment passé... j'imagine en mettant en logs quelque part l'erreur brut, ça aidera à faire du debug. À voir si le add-on "Logs extended storage" de Clevercloud peut aider.

2021-07-30 14:55 UTC, alemangui approved these changes

2021-07-30 14:57 UTC, merged