Utiliser les tags pour les filtres actifs
betagouv/ma-cantine pull request #4015
Opened 2024-06-05 14:11 UTC by hfroot

- [ ] text pour badge tag
- [ ] text pour ville/commune

closes #4007 

![Screenshot 2024-06-05 at 16-09-57 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/12f82996-6e8b-49b2-b78c-b1dc8cbc3571)

2024-06-05 15:17 UTC, alemangui commented on frontend/src/views/CanteenEditor/CityField.vue
> -    inseeCode() {
This was in the previous PR I think, it might have a conflict

2024-06-05 15:47 UTC, alemangui requested changes

2024-06-05 15:47 UTC, alemangui commented on frontend/src/views/CanteensPage/CanteensHome.vue
> +          displayName(value) {
Je crois que c'est ici qu'il y a un problème de parsing lors qu'on accède à cette page (ça affiche un tag "Secteurs : Nan" et la requête API échoue avec `sectors	[ "« NaN » n’est pas une valeur correcte." ]`)

```javascript
 populateParameters() {
      this.searchTerm = this.$route.query.recherche || null
      Object.values(this.filters).forEach((f) => {
        f.value = this.$route.query[f.param]     // <- Ici f.value est `undefined` pour les secteurs
        if (f.transformToFrontend) f.value = f.transformToFrontend(f.value)
      })
```

Donc la variable `values` ici devient `[+undefined]` donc `[NaN]`

[Screencast from 05-06-24 17:31:46.webm](https://github.com/betagouv/ma-cantine/assets/1225929/642bcc59-59dd-480d-b59d-844906526428)

2024-06-05 19:17 UTC, hfroot commented on frontend/src/views/CanteensPage/CanteensHome.vue
> +          displayName(value) {
bien vu https://github.com/betagouv/ma-cantine/pull/4015/commits/ba0e4feab6919c094f24c1cb29cd0f27b982a6f4

2024-06-05 19:38 UTC, hfroot commented
J'ai ajouté qqch pour afficher le nom de la commune mais ça ne marche pas si on a le commune dans le query quand on télécharge la page. Vu que c'est déjà le comportement du CityField sur cette page je me suis dit que c'est hors du scope de cette PR

2024-06-10 10:35 UTC, hfroot commented
rappel pour moi même

> "Au niveau du message d'indication du nombre de résultats de recherche :

> 1. Ajouter un attribut aria-live=""polite"" à la balise `<p>` encadrant le résultat.
> 2. Ajouter également un attribut aria-atomic=""true"" à cette même balise `<p>`.

> Pour obtenir concrètement :
> `<p aria-live=""polite"" aria-atomic=""true""> XXX établissements correspondent à votre recherche </p>"`

2024-06-10 10:49 UTC, hfroot commented on frontend/src/views/CanteensPage/CanteensHome.vue
> +              </h2>
à noter  qu'on bascule vers `h3` pour les cartes ici https://github.com/betagouv/ma-cantine/pull/4017 alors ça va avoir du sense quand c'est ensemble (CAD, h1 titre de la page, h2 rechercher + h3s et h4s filtres, h2 resultats + h3s titres des cantines, h2 formule de contact en bas)

2024-06-10 11:10 UTC, alemangui approved these changes

2024-06-10 11:13 UTC, merged