Utilisation du dashboard public pour la page stats
betagouv/ma-cantine pull request #413
Opened 2021-07-29 16:38 UTC by alemangui

Avant : 

![image](https://user-images.githubusercontent.com/1225929/127531062-2ceabe86-11bd-4a5b-9f13-ece9ee34ccfa.png)

Après :

![image](https://user-images.githubusercontent.com/1225929/127531012-2768e975-fd9b-4d8d-9fc1-e1f1201b8a9a.png)

2021-08-05 08:58 UTC, alemangui commented
Coucou @JenniferStephan, tu en penses quoi de cette PR ?

2021-08-07 18:27 UTC, hfroot requested changes

2021-08-07 18:27 UTC, hfroot commented on frontend/src/views/StatsPage.vue
> +    <h3 class="text-left my-3">Pages visitées (total)</h3>
```suggestion
    <h3 id="pages" class="text-left my-3">Pages visitées (total)</h3>
```
pour le `aria-labelledby`

2021-08-07 18:27 UTC, hfroot commented on frontend/src/views/StatsPage.vue
> +    <h3 class="text-left my-3">Canaux d'acquisition</h3>
```suggestion
    <h3 id="channels" class="text-left my-3">Canaux d'acquisition</h3>
```
pour le `aria-labelledby`

2021-08-07 18:27 UTC, hfroot commented on frontend/src/views/StatsPage.vue
> +      allowtransparency
```suggestion
      allowtransparency
      title="Chartes avec le pourcentage de cantines de chaque type de gestion, et le nombre de nouveaux utilisateurs par jour"
```
Les iframes sont difficile a rendre accessible, je pense qu'on peut merger cette PR et discuter ça après

2021-08-09 08:49 UTC, JenniferStephan commented
Hello !! très bonne idée, la page infogram date en effet, et c'est de la mise à jour à la mano... ca me va totalement de mettre le dashboard metabase ! d'ailleurs, on peut carrément mettre tous les graphes de notre dashboard interne non ? rien à cacher

2021-08-09 12:33 UTC, alemangui commented on frontend/src/views/StatsPage.vue
> +    <h3 class="text-left my-3">Pages visitées (total)</h3>
Ce n'est plus d'actualité depuis qu'on fait un lien vers le dashboard externe : https://github.com/betagouv/ma-cantine/pull/413/commits/e46be6048ea4a642c3de6253cf48b4ff95d2b98b

2021-08-09 12:33 UTC, alemangui commented on frontend/src/views/StatsPage.vue
> +    <h3 class="text-left my-3">Canaux d'acquisition</h3>
Ce n'est plus d'actualité depuis qu'on fait un lien vers le dashboard externe : https://github.com/betagouv/ma-cantine/pull/413/commits/e46be6048ea4a642c3de6253cf48b4ff95d2b98b

2021-08-09 12:33 UTC, alemangui commented on frontend/src/views/StatsPage.vue
> +      allowtransparency
Plus d'iframe :)  Lien vers la page metabase externe : https://github.com/betagouv/ma-cantine/pull/413/commits/e46be6048ea4a642c3de6253cf48b4ff95d2b98b

2021-08-09 12:55 UTC, hfroot approved these changes

2021-08-09 13:41 UTC, merged