Division de api/views.py en plusieurs fichiers
betagouv/ma-cantine pull request #428
Opened 2021-08-03 15:36 UTC by alemangui

J'ai profité pour ajouter des logs dans la gestion d'erreurs des views (nécessaire car ces exceptions sont gérées et donc n'arrivent pas à Sentry)

2021-08-03 15:37 UTC, alemangui commented on api/views/blog.py
> +logger = logging.getLogger(__name__)
Dans ce fichier le logger n'est pas utilisé, mais je l'ai laissé au cas où l'on aurait besoin de logs après. C'est discutable.

2021-08-03 15:39 UTC, alemangui commented on api/views/canteen.py
> +            raise Exception("Error occurred : the mail could not be sent.") from e
En ajoutant `from e` on utilise l'_exception chaining_ de Python (https://docs.python.org/3/reference/simple_stmts.html#the-raise-statement)

2021-08-03 15:42 UTC, alemangui commented on api/views/utils.py
> +def camelize(data):
J'en profite pour créer le fichier `utils`. En règle générale j'aime placer les fichier utilitaires au niveau ou ils sont utilisés. Dans ce cas, `camelize` est utilisé par plusieurs fichiers de ce directory, d'où son placement.

2021-08-03 15:44 UTC, alemangui commented on api/views/canteen.py
> +    @staticmethod
Précédemment ces fonctions étaient au niveau 0 - au même titre que la classe. Si une fonction est utilisée par une seule classe j'ai une préférence par la mettre en tant que `@staticfunction`, comme ça la classe a tout ce qu'il le faut à l'intérieur. Puis si jamais une fonction est utilisée par plusieurs classes à l'intérieur d'un fichier, donc on le met au niveau 0.

2021-08-04 14:12 UTC, alemangui commented on api/views/diagnostic.py
> -            canteen.full_clean()  # validate choice fields
Désormais `full_clean` fait d'autres vérifications aussi (celles mises dans la méthode `clean`)

2021-08-04 14:23 UTC, alemangui commented
C'est un peu hors du scope de cette PR, mais vu que j'étais déjà sur cette zone j'ai profité dans le deuxième commit pour ajouter quelques éléments de validation/refacto pour l'import des CSV, notamment :

1- **Validation de SIRET**

Le SIRET doit contenir 14 caractères et être conforme à l'[algorithme de Luhn](https://www.geeksforgeeks.org/luhn-algorithm/). Cette validation est faite dans le `clean` du modèle `Canteen.py`

2- **Possibilité de retourner plusieurs erreurs pour la même ligne**

Si une ligne présente deux erreurs dans des champs différents (par exemple `year` et `siret`, les deux erreurs sont affichées dans la UI.

![image](https://user-images.githubusercontent.com/1225929/128196178-f1529b59-8727-4a4a-b3f8-fba4e19f639b.png)

3- **Validation dynamique de l'année**

Désormais la validation de l'année d'un diagnostic est faite dans la méthode `clean` du modèle `Diagnostic.py`. Ça permet de dynamiquement ajuster l'année maximale en fonction de la date.

4- **Usage de message_dict pour les ValidationError**

Normalement il n'y a plus besoin de `validation_error_regex` car tous les erreurs seront répertoriées dans le _message_dict_ de l'exception.

2021-08-05 15:39 UTC, hfroot requested changes

2021-08-05 15:39 UTC, hfroot commented on api/views/diagnostic.py
> +# flake8: noqa: C901
Pourquoi est-ce qu'on a ça ?

2021-08-05 15:39 UTC, hfroot commented on api/views/diagnostic.py
> +            status=status.HTTP_200_OK,
Peut-être maintenant qu'on rejet le fichier si il y a des erreurs, on doit retourner un 400 ici, et afficher un succes/erreur `notify` au coté front ?

2021-08-05 15:39 UTC, hfroot commented on api/views/diagnostic.py
> +            canteen.full_clean()
Hors de cette PR : est-ce que tu penses que ça doit être le comportement defaut quand on utilise `objet.save()` ?

2021-08-05 15:55 UTC, alemangui commented on data/models/canteen.py
> +        Canteen.validate_siret(self.siret, "siret")
Oui tout à fait, mais pour l'instant ce boulot est fait coté view dans le `_normalise_siret`

2021-08-05 15:58 UTC, alemangui commented on data/models/canteen.py
> +    def clean(self):
Oui c'est un peu bizarre car le `clean` n'est pas appelé quand on sauvegarde un modèle ([doc](https://docs.djangoproject.com/en/3.2/ref/models/instances/#django.db.models.Model.clean)):

> Note, however, that like Model.full_clean(), a model’s clean() method is not invoked when you call your model’s save() method.

Ce qui veut dire qu'il faut l'inclure dans les calls API aussi. Vu qu'il y avait quelques difficultés à saisir le SIRET je me suis dit que je n'allait pas trop bouger cette partie là pour l'instant, mais on peut en parler et la peaufiner dans un second temps.

2021-08-05 16:00 UTC, alemangui commented on api/views/diagnostic.py
>          elif isinstance(e, Sector.DoesNotExist):
Oui, au début j'avait fait en sorte que tout soit affiché, par contre après j'ai pensé que c'était bizarre de dire "Vous n'avez pas le droit sur cette cantine, et l'année n'est pas bonne". Peut-être que si l'utilisateur n'a pas le droit les autres erreurs n'ont pas trop de sens, mais ça se discute.

2021-08-05 16:07 UTC, alemangui commented on api/views/diagnostic.py
> +# flake8: noqa: C901
Ce n'est pas nécessaire en effet, je l’enlèverai

2021-08-05 16:09 UTC, alemangui commented on data/models/diagnostic.py
> +                    "year": f"L'année doit être comprise entre 2019 et {current_year + 1}."
Oui, je vais ajouter un `lower_limit_year` et `upper_limit_year`, ça sera plus clair dans le code

2021-08-05 16:16 UTC, alemangui commented on data/models/diagnostic.py
> +        if self.year < 2019 or self.year > (current_year + 1):
Oui ça permet de déclarer l'erreur une seule fois :+1:

2021-08-05 16:20 UTC, alemangui commented on api/views/diagnostic.py
> +            status=status.HTTP_200_OK,
Même je me demande si le `notify` est nécessaire... Vu qu'on a le feedback du fichier immédiatement en bas du file-input, est-ce que ça ne fait pas duplication d'information ? (Ce qui posserait aussi la question d’enlever le temps de traitement de la réponse).

2021-08-05 16:23 UTC, alemangui commented on api/views/diagnostic.py
> +            canteen.full_clean()
Le full-clean ? On peut oui. En vrai comme on commence à utiliser les SIRET comme une sorte d'identificateur unique externe, vite on va devoir se poser la question d'être plus stricts là-dessus. Ça peut passer par un full_clean à chaque save, ou bien par un [validator custom](https://docs.djangoproject.com/en/3.2/ref/validators/) qui vérifierait le SIRET avant de le mettre en base de données. 

Chaud pour en discuter lors du planning.

2021-08-05 16:24 UTC, alemangui commented on data/models/canteen.py
> +        odd_digits = [int(n) for n in siret[-1::-2]]
Fait dans le commit : https://github.com/betagouv/ma-cantine/pull/428/commits/fddd819d03e2de5991bd084312fb5007d5e9dae5

2021-08-05 16:26 UTC, alemangui commented on data/models/diagnostic.py
> +                    "year": f"L'année doit être comprise entre 2019 et {current_year + 1}."
Fait dans le commit : https://github.com/betagouv/ma-cantine/pull/428/commits/fddd819d03e2de5991bd084312fb5007d5e9dae5

2021-08-05 16:26 UTC, alemangui commented on data/models/diagnostic.py
> +        if self.year < 2019 or self.year > (current_year + 1):
Fait dans le commit : https://github.com/betagouv/ma-cantine/pull/428/commits/fddd819d03e2de5991bd084312fb5007d5e9dae5

2021-08-05 16:26 UTC, alemangui commented on api/views/diagnostic.py
> +# flake8: noqa: C901
Fait dans le commit : https://github.com/betagouv/ma-cantine/pull/428/commits/fddd819d03e2de5991bd084312fb5007d5e9dae5

2021-08-08 16:38 UTC, hfroot commented on api/views/diagnostic.py
> +# flake8: noqa: C901
Ah j'ai parlé du commentaire
```
# flake8: noqa: C901
```

2021-08-08 16:38 UTC, hfroot commented on data/models/canteen.py
> +        if siret is None:
```suggestion
        if siret is None or siret == "":
```
Quand on fait la modification dans `/admin` le siret est `""` (mais le siret_central_producer est None)

2021-08-09 06:19 UTC, alemangui commented on data/models/canteen.py
> +        if siret is None:
Merci !

2021-08-09 11:29 UTC, hfroot approved these changes

2021-08-09 12:14 UTC, merged