Ajout de la page "5 mesures-phare"
betagouv/ma-cantine pull request #49
Opened 2021-01-08 17:47 UTC by hfroot

#41

2021-01-11 09:27 UTC, Forster-Groux requested changes

2021-01-11 09:27 UTC, Forster-Groux commented on front-end/src/views/KeyMeasuresPage.vue
> +            </p>
Plutôt que `:style` peut être rajouter une class avec le title du tag. Ce qui permettrait de gérer la couleur au niveau css et non plus dans le js.

2021-01-11 09:27 UTC, Forster-Groux commented on front-end/src/views/KeyMeasuresPage.vue
> +              </p>
J'ai l'impression qu'on pourrait avoir un component pour les tags qu'est ce que tu en penses ?

2021-01-11 09:29 UTC, Forster-Groux commented on front-end/src/views/KeyMeasuresPage.vue
> +  content: "📅 ";
Pas possible de mettre ça directement fans le html ?

2021-01-11 16:33 UTC, Forster-Groux commented on front-end/src/components/SectorTags.vue
> +      validator(value) {
Quel intérêt du validator ici ?

2021-01-11 16:38 UTC, hfroot commented on front-end/src/components/SectorTags.vue
> +      validator(value) {
Il est recommandé par [le guide](https://v3.vuejs.org/style-guide/#prop-definitions-essential), je pensai que c'est aider à éviter un petit bogue si on ajoutera un nouveau tag sans un titre pour affichage

2021-01-11 16:57 UTC, Forster-Groux commented on front-end/src/components/SectorTags.vue
> +      validator(value) {
Ok je vois, ça me parait quand même un peu lourd, est-ce que c'est bien utile d'avoir un message custom alors que Vue nous prévient déjà ? Je pense qu'on peut se contenter de :
```
validator(value) {
  return value.every((v) => v in tagsInfo);
},
```
Qu'est ce que tu en penses ?

2021-01-12 09:55 UTC, hfroot commented on front-end/src/components/SectorTags.vue
> +      validator(value) {
Après notre discussion, j'ai supprimer la validation complètement

2021-01-12 10:54 UTC, Forster-Groux approved these changes
Pour moi c'est bon, par contre ça serait bien de rajouter les liens CNRC

2021-01-12 10:54 UTC, Forster-Groux commented on front-end/src/views/KeyMeasuresPage.vue
> +        </div>
Peut être désactiver ou cacher ces liens en attendant de les remplir.

2021-01-12 12:20 UTC, hfroot commented
@JenniferStephan pour ton information - j'ai caché les liens de CNRC pour la moment, parce que nous n'avons pas les URLs maintenant.

2021-01-12 12:20 UTC, merged