Installer pré-processeur SCSS
betagouv/ma-cantine pull request #62
Opened 2021-01-15 15:09 UTC by hfroot

#56

2021-01-15 16:05 UTC, hfroot commented
Est-ce que tu as un preference de l'utilisation des noms descriptifs pour les variables CSS (orange, orangeLight, etc) ou quelque chose plus general (primary, primaryLight, secondary etc)?

2021-01-18 08:58 UTC, Forster-Groux approved these changes
Une légère préférence pour expliciter le nom de la couleur, je trouve ça plus simple de s'y retrouver au jour le jour quand on code.

2021-01-18 08:58 UTC, Forster-Groux commented on front-end/src/assets/styles/_variables.scss
> +$orange: #EB5B25;
Je sais pas si j'aurais mis ça dans 'assets', j'ai l'impression que c'est plus pour des ressources non-codée (image, pdf, etc).

2021-01-19 16:01 UTC, hfroot commented on front-end/src/assets/styles/_variables.scss
> +$orange: #EB5B25;
Je pense que j'ai essayé d'ajouter styles/ dans src/ et ça ne marche pas mais je essaye de nouveau, je suis d'accord en principe

2021-01-19 16:16 UTC, Forster-Groux requested changes
Je pense qu'il y a eu quelques soucis dans le rebase, le fichier LandingPage.vue n'est plus censé exister et l'exemple de variable ($orange) n'a pas été propagé aux différents sous-components de LandingPage.

2021-01-19 17:30 UTC, Forster-Groux approved these changes

2021-01-20 15:51 UTC, merged