Ajout de la pagination des cantines et diagnostics
betagouv/ma-cantine pull request #743
Opened 2021-11-09 13:56 UTC by alemangui

La page de gestion de cantines/diagnostics n'est pas adaptée pour les comptes gérant beaucoup de cantines. Des changements à ce niveau-là sont devenus nécessaires depuis l'utilisation de l'import de masse (par ex., les cantines de Normandie).

Ceci est un premier pas - mais d'autres PRs devront être faits pour ajouter des filtres et recherche dans cette zone.

Pour l'instant une pagination s'affiche si l'utilisateur a plus de cinq cantines ou six diagnostics. Cela améliore déjà les temps de chargement et la lisibilité de cette page.

![image](https://user-images.githubusercontent.com/1225929/140936857-6f58245e-4c1a-45de-b798-35e6ce325326.png)

2021-11-09 15:39 UTC, hfroot requested changes

2021-11-09 15:39 UTC, hfroot commented on frontend/src/views/ManagementPage/CanteensPagination.vue
> +          </v-card-text>
On perd le lien vers l'importeur qui est maintenant en staging

2021-11-09 16:28 UTC, alemangui commented on frontend/src/views/ManagementPage/CanteensPagination.vue
> +          </v-card-text>
Woops, je fais le merge avec staging...

2021-11-09 16:31 UTC, alemangui commented on frontend/src/views/ManagementPage/CanteensPagination.vue
> +          </v-card-text>
C'est bon pour le merge :+1:

![image](https://user-images.githubusercontent.com/1225929/140964920-9ab5aab3-a63f-418c-a685-533560586d63.png)

2021-11-11 18:11 UTC, hfroot approved these changes

2021-11-12 08:27 UTC, merged