Répondre au retours 01/02/2021
betagouv/ma-cantine pull request #86
Opened 2021-02-02 11:30 UTC by hfroot

2021-02-02 11:34 UTC, hfroot commented
@Forster-Groux est-ce que tu pense que je dois créer un nouveau component pour le GitHub lien ? Je pense que c'est trop de code juste pour partager `https://jennifer-stephan.gitbook.io/ma-cantine-egalim/`, je pense peut-être je peux utiliser props ou Vuex plutôt.

2021-02-02 12:59 UTC, Forster-Groux requested changes

2021-02-02 12:59 UTC, Forster-Groux commented on front-end/src/views/KeyMeasuresPage/index.vue
> +          </a>
Il faut rajouter `target=_blank` pour que le lien s'ouvre dans un nouvel onglet.

La plupart des mesures sont encore vides dans le gitbook, vu qu'on commence déjà à partager le site, peut être attendre avant d'afficher ces liens ?

2021-02-02 13:05 UTC, Forster-Groux commented
> @Forster-Groux est-ce que tu pense que je dois créer un nouveau component pour le GitHub lien ? Je pense que c'est trop de code juste pour partager `https://jennifer-stephan.gitbook.io/ma-cantine-egalim/`, je pense peut-être je peux utiliser props ou Vuex plutôt.

Heu non je pense pas vu qu'il n'y a pas de duplication dans le code. Par contre pourquoi le mettre dans KeyMeasuresPage plutôt que dans InfoCard ?

Par contre utiliser une props ça me parait pertinent si on met l'url du gotbook dans une variable d'environnement oui.

J'ai pas compris la potentielle utilisation de Vuex par contre ?

2021-02-03 14:47 UTC, hfroot commented on front-end/src/views/KeyMeasuresPage/index.vue
> +          </a>
Pourquoi est-ce que tu pense que le lien doit s'ouvre dans un nouvel onglet ?
Je suis d'acc de cacher ces liens en attendant pour plus de contenu dans les pages, ou je peux déplacer les deux derniers commits dans une nouvelle branche si je peux fixer cet rebase...

2021-02-03 17:35 UTC, Forster-Groux commented on front-end/src/views/KeyMeasuresPage/index.vue
> +          </a>
Je trouve ça plus agréable quand un lien redirige en dehors du site que ça s'ouvre dans un nouvel onglet plutôt que remplacer la page existante. Tu en penses quoi toi ?

2021-02-03 17:35 UTC, Forster-Groux approved these changes

2021-02-05 08:33 UTC, merged