Mettre en avance la page nos cantines
betagouv/ma-cantine pull request #902
Opened 2022-01-12 17:07 UTC by hfroot

J'ai pensé à ça en relation des additions qu'on va faire ce sprint des stats régionales. Je vais envoyer un message pour recevoir des retours de l'équipe aussi

![Screenshot 2022-01-12 at 18 04 53](https://user-images.githubusercontent.com/9282816/149187523-520257c9-2359-4d1f-ae91-69c636cda04e.png)

2022-01-13 13:18 UTC, alemangui requested changes

2022-01-13 13:18 UTC, alemangui commented on frontend/src/views/LandingPage/PresentationBlock.vue
> +    <v-row>
J'ai un souci d'alignement en mobile : 
![image](https://user-images.githubusercontent.com/1225929/149337029-bf6ae283-8a3b-4231-8318-ffaa4ee88f41.png)

2022-01-13 13:18 UTC, alemangui commented on frontend/src/views/LandingPage/PresentationBlock.vue
> +      <v-btn x-large outlined color="primary" class="mt-8 mx-8" :to="{ name: 'CanteensHome' }">
:thinking: En ce qui concerne les margins je mettrais moins d'espace au milieu des boutons, par ex en mettant un `mr-8` ici (au lieu du `mx-8`) et en enlevant les `mx-8` de l'autre bouton... comme ci-dessous, qu'est-ce que t'en penses ?

```html
      <v-btn x-large outlined color="primary" class="mt-8 mr-8" :to="{ name: 'CanteensHome' }">
        Découvrir nos cantines
      </v-btn>
      <v-btn v-if="loggedUser" x-large class="primary mt-8" :to="{ name: 'ManagementPage' }">
        Accéder à mes cantines
      </v-btn>
      <v-btn v-else x-large class="primary mt-8" href="/creer-mon-compte">
        Créer mon compte
      </v-btn>
```

2022-01-13 13:55 UTC, hfroot commented on frontend/src/views/LandingPage/PresentationBlock.vue
> +    <v-row>
Ah ouiii ! Avec les vacances il me semble que j'ai oublié comment développer les sites 😳

2022-01-18 08:28 UTC, alemangui approved these changes

2022-01-18 09:39 UTC, merged