Dashboard statistiques publiques
betagouv/ma-cantine pull request #908
Opened 2022-01-17 14:27 UTC by hfroot

Page accessible vers "http://localhost:8000/statistiques-regionales/"

Est-ce que tu peux suggérer des améliorations du texte ? J'ai trouvé ça difficile cette fois...

Cette PR est pas encore complétée, mais tu peux commencer avec un revue du front.

TODO - Helen

- [ ] Lien vers page
- [ ] Completer calculs pour les badges sur le back

![Screenshot 2022-01-17 at 12 33 46](https://user-images.githubusercontent.com/9282816/149787641-18878420-ba6f-4616-9d24-90113a20b4c7.png)

2022-01-18 17:41 UTC, alemangui requested changes

2022-01-18 17:41 UTC, alemangui commented on frontend/src/views/PublicCanteenStatisticsPage/index.vue
> +              cantines dans {{ locationText }} sur ce site.
On peut utiliser `cantine` ou `cantines` en dépendant de canteenCount, pour éviter d'avoir "Aujourd'hui, il y a 1 cantine**s**"

2022-01-18 17:41 UTC, alemangui commented on frontend/src/views/PublicCanteenStatisticsPage/BadgeCard.vue
> +<template>
Un détail, mais j'ai l'impression que certaines cartes (mais pas toutes) ont des font baselines différentes entre le chiffre en `font-weight-black` et le reste du texte : 

Par ex, celle-ci a un décalage :
![image](https://user-images.githubusercontent.com/1225929/149989627-81531601-9833-493e-9f2c-e9efa7a02453.png)

Alors que celles-ci ont l'air OK :
![image](https://user-images.githubusercontent.com/1225929/149989760-c10d8c4b-3f79-4dea-8354-99c73d8f2119.png)

Celles en bas ont aussi un décalage : 
![image](https://user-images.githubusercontent.com/1225929/149989807-6cc28e4a-c53e-4f9d-999e-0b03fa27cee8.png)

2022-01-19 09:52 UTC, hfroot commented on frontend/src/views/PublicCanteenStatisticsPage/index.vue
> +        // TODO: what to do in this case?
Je pensais peut-être pour cette vue on peut montrer les statistiques pour toutes les régions, tu en penses quoi ?

2022-01-19 09:55 UTC, hfroot commented on frontend/src/views/PublicCanteenStatisticsPage/index.vue
> +</script>
Oui, je suis d'acc mais la PR est devenue un peu grande. Je l'ajouterai dans une deuxième.

2022-01-19 11:26 UTC, hfroot commented on frontend/src/views/PublicCanteenStatisticsPage/index.vue
> +      if (this.chosenDepartment) {
Bien vu ! J'ai écrit une solution juste un peu différente que ce que t'as proposé, dis-moi si tu penses qu'on a besoin de plus de ça

2022-01-19 12:19 UTC, hfroot commented on frontend/src/views/PublicCanteenStatisticsPage/BadgeCard.vue
> +<template>
Bien vu !

2022-01-20 19:45 UTC, alemangui requested changes

2022-01-20 19:45 UTC, alemangui commented on frontend/src/views/PublicCanteenStatisticsPage/index.vue
> +              cantine{{ statistics.canteenCount == 1 ? "" : "s" }} dans {{ locationText }} sur ce site.
Ici ça va être un peu plus compliqué malheureusement... pour les régions normalement on n'utilise pas _dans_ (par ex. **en** île-de-France, **en** Bourgogne, **au** Mayotte...) et pour les départements c'est aussi assez compliqué (**dans** les Vosges, **en** Essonne..) etc.

Perso j'opterai pour un affichage différent, pour éviter ces pièges de la langue française :

- En titre ne pas spécifier une préposition en utilisant des guillemets (par ex., Les statistiques pour « Bourgogne-Franche-Comté », Les statistiques pour « Mayotte », Les statistiques pour « Essone »)
- Dans le texte en dessous : " Au total, nous avons 1 cantine sur ce territoire. 1 cantine a publié ses données (répertoriés dans nos cantines)."

![image](https://user-images.githubusercontent.com/1225929/150408398-0d8f74f7-73b1-44f1-9a37-251387ced45f.png)

2022-01-20 19:45 UTC, alemangui commented on frontend/src/views/PublicCanteenStatisticsPage/index.vue
> +            <p>
Je pense qu'on peut diminuer l'espace entre ces deux lignes (les deux parlent des cantines dans le territoire)
```suggestion
            <p class="mb-0">
```

2022-01-20 19:45 UTC, alemangui commented on frontend/src/views/PublicCanteenStatisticsPage/index.vue
> +      <h2 class="text--darken-5 text-h4 mb-8">Les statistiques pour {{ locationText }}</h2>
Petite suggestion : Dans la plupart des pages on joue sur l’épaisseur du texte pour les titres. On peut le faire pour cette page aussi si ça te va. Du coup on n'aurait pas besoin du `text--darken-5`.
Si on prend cette voie, ce titre serait un `text-h5` et les autres un `text-h6` (mais avec le `font-weight-black` ça prend à peu près la même dimension).
```suggestion
      <h2 class="text-h5 font-weight-black mb-8">Les statistiques pour {{ locationText }}</h2>
```

2022-01-20 19:45 UTC, alemangui commented on frontend/src/views/PublicCanteenStatisticsPage/index.vue
> +      <h3 class="text-h5 mt-10 mb-8 text--darken-5">Qualité de produits en {{ year }}</h3>
Dans la même ligne que mon commentaire au-dessus par rapport à l'épaisseur des titres, ce niveau pourrait être un truc comme : 
```suggestion
      <h3 class="text-h6 font-weight-black mt-10 mb-8">Qualité de produits en {{ year }}</h3>
```

2022-01-20 19:45 UTC, alemangui commented on frontend/src/views/PublicCanteenStatisticsPage/index.vue
> +      <h3 class="text-h5 mt-10 mb-8">Ces cantines ont aussi réalisé les mesures suivantes en {{ year }}</h3>
Dans l'esprit des autres commentaires sur les titres au dessus ;)

```suggestion
      <h3 class="text-h6 font-weight-black mt-10 mb-8">Ces cantines ont aussi réalisé les mesures suivantes en {{ year }}</h3>
```

2022-01-20 19:45 UTC, alemangui commented on frontend/src/views/CanteensPage/CanteensHome.vue
> +    <!-- TODO: this page feels very busy, with a link to regional stats it will be even more so -->
D'après le call d'aujourd'hui j'ai imaginé un truc comme ça. Assez discret (mais c'est pas grave car on va partager le lien j'imagine). N'hésites pas à challenger le texte, je ne suis pas très inspiré :)
![image](https://user-images.githubusercontent.com/1225929/150410457-077cd973-0076-4aea-9a13-a8a9fedb7513.png)

2022-01-20 19:45 UTC, alemangui commented on frontend/src/views/CanteensPage/CanteensHome.vue
> +    <!-- Ideas: pagination should outline the number, not make the entire button green. Too attention grabbing -->
AMA la page a l'air trop occupé car elle l'est :smile:   Pour moi un quickwin serait mettre les filtres sous un drawer (éventuellement laissant ceux qui sont les plus utilisés dehors).

2022-01-20 19:45 UTC, alemangui commented on frontend/src/components/HeaderDropdownList.vue
> -          authenticationState: true,
:thinking: Pourquoi on avait ça ?

2022-01-20 19:47 UTC, alemangui requested changes

2022-01-20 19:47 UTC, alemangui commented on frontend/src/views/PublicCanteenStatisticsPage/index.vue
> +      year: 2021,
On le rend dynamique ? (on peut prendre `lastYear` de `@/utils` si besoin)

2022-01-21 10:45 UTC, hfroot commented on frontend/src/components/HeaderDropdownList.vue
> -          authenticationState: true,
Introduit ici ; https://github.com/betagouv/ma-cantine/commit/3d553dc9ecae69f2b48a4f5db1bf83acb5644662

Peut-être on a pensé que c'était assez accessible depuis l'autodiag ?

2022-01-21 10:51 UTC, hfroot commented
Je trouve les headings ici maintenant un peu trop accrocheurs, tu en penses quoi ?

![Screenshot 2022-01-21 at 11 49 32](https://user-images.githubusercontent.com/9282816/150514406-61584aa0-8858-4077-a0a6-6812f0e9808f.png)

2022-01-21 14:58 UTC, alemangui approved these changes

2022-01-21 15:16 UTC, merged