Étiquettes de blog
betagouv/ma-cantine pull request #922
Opened 2022-01-20 10:06 UTC by hfroot

2022-01-20 10:08 UTC, hfroot commented on frontend/src/views/BlogsPage/BlogCard.vue
> +        "yellow lighten-4",
J'ai ajouté plus de couleurs qu'étiquettes prévues en pensant qu'on peut laisser l'équipe d'ajouter plus d'étiquettes sans problème. Tous ces couleurs sont accessible en terme de contraste avec le texte du label.

![Screenshot 2022-01-20 at 10 55 35](https://user-images.githubusercontent.com/9282816/150317684-39364b01-8767-4514-9a94-25bec02837d5.png)
![Screenshot 2022-01-20 at 10 55 21](https://user-images.githubusercontent.com/9282816/150317694-a9fb3f4e-fe18-4edc-8144-967df09be6cf.png)

2022-01-21 09:07 UTC, alemangui requested changes

2022-01-21 09:07 UTC, alemangui commented on frontend/src/views/BlogsPage/BlogCard.vue
> +      let tags = this.$store.state.blogTags
La couleur est assignée par rapport à l'ordre de sérialisation, est-ce que du coup les tags changeraient tous de couleur si je supprime le premier tag créé ? (vu que tous les autres changeraient leur place). Après, est-ce que c'est grave ? - je ne pense pas...

2022-01-21 10:54 UTC, alemangui commented on frontend/src/views/BlogsPage/BlogCard.vue
> +      <v-chip v-if="tag" small :color="tag.colour">{{ tag.name }}</v-chip>
D'ailleurs ici on affiche seulement la première etiquette, alors qu'on peut y assigner plusieurs, je vais modifier cette partie là aussi

2022-01-21 11:12 UTC, alemangui commented on frontend/src/views/BlogsPage/BlogCard.vue
> +      <v-chip v-if="tag" small :color="tag.colour">{{ tag.name }}</v-chip>
Avec plusieurs étiquettes la place à coté du bouton ne suffit plus :( Je les ai replacé par ici :
![image](https://user-images.githubusercontent.com/1225929/150517472-f73e4004-2d8c-4d36-9af4-96ccfd8b70be.png)

2022-01-21 11:17 UTC, alemangui commented on frontend/src/views/BlogsPage/BlogCard.vue
> +      const colourIndex = Array.from(tag, (x) => x.charCodeAt(0)).reduce((a, b) => a + b) % (colours.length - 1)
@hfroot J'ai changé la façon de calcul pour la couleur de sorte que un string ait toujours la même couleur.

En gros je transforme chaque string à un chiffre (en transformant chaque _char_ à une valeur numérique puis en faisant l'addition de toutes ces valeurs), après je fais un modulo des couleurs qu'on a dispo. Ça permet de donner la même couleur à un tag indépendamment de son emplacement dans le tableau (ce qui est nécessaire puisqu'on n'a plus le tableau avec tous les tags).

2022-01-21 11:17 UTC, alemangui commented on api/urls.py
> +    path("blogTags/", BlogTagListView.as_view(), name="blog_tags_list"),
Changé dans : https://github.com/betagouv/ma-cantine/pull/922/commits/5746d52fd80840065b002d99ff64e854b68722f2

2022-01-21 11:18 UTC, alemangui commented on frontend/src/views/BlogsPage/BlogCard.vue
> +      let tags = this.$store.state.blogTags
Changé dans : https://github.com/betagouv/ma-cantine/pull/922/commits/5746d52fd80840065b002d99ff64e854b68722f2
Plus de détails : https://github.com/betagouv/ma-cantine/pull/922#discussion_r789573570

2022-01-21 11:18 UTC, alemangui commented on frontend/src/views/BlogsPage/BlogCard.vue
> +      <v-chip v-if="tag" small :color="tag.colour">{{ tag.name }}</v-chip>
Changé dans : https://github.com/betagouv/ma-cantine/pull/922/commits/5746d52fd80840065b002d99ff64e854b68722f2

2022-01-21 11:18 UTC, alemangui approved these changes

2022-01-21 11:24 UTC, hfroot commented on frontend/src/views/BlogsPage/BlogCard.vue
> +      const colourIndex = Array.from(tag, (x) => x.charCodeAt(0)).reduce((a, b) => a + b) % (colours.length - 1)
C'est possible qu'on va avoir des répétitions de couleur, mais je pense que ça marche pour l'instant

2022-01-21 11:25 UTC, merged